### ISSUE TITLE
ClinVar - error expanding toggle

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1004]
NC_000017.11:g.6398242_6408077dup

On my machine, I crash out on 

```
{% clinvar_stars clinvar.stars %}
.....
/home/dlawrence/localwork/variantgrid/annotation/models/models.py, line 159, in stars
return ClinVarReviewStatus(self.clinvar_review_status).stars()
        return ClinVarReviewStatus.STARS[self.value]
```

On VG test, expanding the "toggle individual clinvar records" gives:

ValueError: Couldn't determine Allele for clinvar_variation_id 157377

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4889](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4889)

```
Traceback (most recent call last):
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/annotation/views.py", line 518, in view_clinvar_records_detail
    ).fetch()
  File "/opt/variantgrid/annotation/clinvar_fetch_request.py", line 70, in fetch
    raise ValueError(f"Couldn't determine Allele for clinvar_variation_id {self.clinvar_variation_id}")
ValueError: Couldn't determine Allele for clinvar_variation_id 157377
```

------------

**Comment by davmlaw** [comment]
This is due to the code below calling first() which may retrieve a variant from 37 or 38, while you may be looking at the variant page for a different one, so allele will only be linked against that

```
                if variant_id := ClinVar.objects.filter(clinvar_variation_id=self.clinvar_variation_id)\
                        .filter(version__in=clinvar_versions).values_list('variant', flat=True).first():
                    if va_allele_id := VariantAllele.objects.filter(variant_id=variant_id).values_list('allele', flat=True).first():
                        allele_id = va_allele_id
```

Instead, we should just do something like:

```
Allele.objects.filter(variantallele__variant__clinvar__clinvar_variation_id=157377).first()
```

**Comment by davmlaw** [comment]
This hasn't turned up before, as usually by the time people click toggle, the variant page has linked alleles. Because this one failed clingen, it didn't link both variants to allele, and by chance the wrong one came back first

**Comment by davmlaw** [comment]
tested VG test - NC_000017.11:g.6398242_6408077dup used to crash, now works
