### ISSUE TITLE
Annotations with obsolete VEP versions should fail fast

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1006]
This annotation run was from an old VEP version - we should do the check before we even start

VEPVersionMismatchError: Annotation/VCF out of sync! Version 'v6. (21 July 2020) VEP: 100 / RefSeq/GRCh37' and VCF '/data/annotation/test_annotation_scratch/dump_5157_cnv.vep_annotated_GRCh37.vcf.gz' differ, KEY: 'cosmic' annotation: '90', vcf: '95'

The VCF file was written last night, and the annotation run when you visit the page is:

```
v9. (20 February 2024) VEP: 110 / RefSeq/GRCh38
```

So the problem is with the check, I think.

----------------

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4739](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4739)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/variantgrid/annotation/tasks/annotate_variants.py", line 77, in annotate_variants
    import_vcf_annotations(annotation_run)
  File "/opt/variantgrid/annotation/vcf_files/import_vcf_annotations.py", line 24, in import_vcf_annotations
    'vep_check_version_match(annotation_run.variant_..._version, annotation_run.vcf_annotated_filename)'
  File "/opt/variantgrid/annotation/vep_annotation.py", line 357, in vep_check_version_match
    raise VEPVersionMismatchError(msg)
VEPVersionMismatchError: Annotation/VCF out of sync! Version 'v7. (21 July 2020) VEP: 100 / RefSeq/GRCh38' and VCF '/data/annotation/test_annotation_scratch/dump_6502_cnv.vep_annotated_GRCh38.vcf.gz' differ, KEY: 'vep' annotation: '100', vcf: '110'
```

**Comment by davmlaw** [comment]
Had an issue with re-using the same fake VCF under heavy load, now we use a unique one per celery job (using uuid)
