### ISSUE TITLE
ValueError: 'A' is not a valid ColumnAnnotationLevel

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1010]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4937](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4937)

```
Traceback (most recent call last):
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/snpdb/views/views.py", line 958, in view_custom_columns
    return render(request, 'snpdb/settings/view_custom_columns.html', context_dict)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 1064, in render
    output = self.filter_expression.resolve(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 715, in resolve
    obj = self.var.resolve(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 847, in resolve
    value = self._resolve_lookup(context)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/template/base.py", line 914, in _resolve_lookup
    current = current()
  File "/opt/variantgrid/snpdb/models/models_columns.py", line 34, in get_css_classes
    annotation_level_class = ColumnAnnotationLevel(self.annotation_level).label
  File "/usr/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 'A' is not a valid ColumnAnnotationLevel
```

**Comment by davmlaw** [comment]
This was done in: snpdb/migrations/0108_one_off_move_alphamissense_dbnsfp.py:6

```
ANNOTATION_LEVEL = 'A'
```

**Comment by davmlaw** [comment]
This was manually patched to vg_aws

```
VariantGridColumn.objects.filter(grid_column_name='alphamissense_rankscore').update(annotation_level='V')
```

**Comment by davmlaw** [comment]
tested vg test, no longer occurs
