### ISSUE TITLE
Patient List page - mondo select broken

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1023]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4961](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4961)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 48, in get
    grid_obj = self._load_grid(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 44, in _load_grid
    return grid_klass(**kwargs)
  File "/mnt/variantgrid/patients/grids.py", line 34, in __init__
    ontology_term = OntologyTerm.objects.get(name=value, ontology_service=ontology_service)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/query.py", line 640, in get
    raise self.model.MultipleObjectsReturned(
MultipleObjectsReturned: get() returned more than one OntologyTerm -- it returned more than 20!
```

**Comment by davmlaw** [comment]
tested, works vg test
