### ISSUE TITLE
Analysis grid - sort by genotype is broken

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1036]
Create a sample/cohort, then click on a genotype column to sort.

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4774](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4774)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/views/decorators/vary.py", line 42, in inner_func
    response = func(*args, **kwargs)
  File "/mnt/variantgrid/analysis/views/views_grid.py", line 51, in get
    response = self.get_response(request, *args, **kwargs)
  File "/mnt/variantgrid/analysis/views/node_json_view.py", line 29, in get_response
    data = self._get_data(request, *args, node=node, **kwargs)
  File "/mnt/variantgrid/analysis/views/views_grid.py", line 77, in _get_data
    return grid.get_data(request)
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 339, in get_data
    'rows': list(items),
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 323, in iter_formatted_items
    for row in rows:
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/query.py", line 208, in __iter__
    for row in compiler.results_iter(
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1513, in results_iter
    results = self.execute_sql(
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/mnt/variantgrid/library/django_utils/django_queryset_sql_transformer.py", line 18, in as_sql
    sql, params = super().as_sql(**kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 85, in pre_sql_setup
    order_by = self.get_order_by()
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 460, in get_order_by
    resolved = expr.resolve_expression(self.query, allow_joins=True, reuse=None)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/expressions.py", line 285, in resolve_expression
    [
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/expressions.py", line 286, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/expressions.py", line 829, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1977, in resolve_ref
    join_info = self.setup_joins(
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1824, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1725, in names_to_path
    raise FieldError(
FieldError: Cannot resolve keyword '9588_samples_zygosity' into field. Choices are: allvariantsnode, alt, alt_id, classification, clinvar, cohortgenotype, cohortgenotype_915, commonvariantclassified, createdmanualvariant, end, global_variant_zygosity, id, importedalleleinfo, internally_classified, internally_classified_labs, intersectionnode, liftovererror, locus, locus_id, max_internal_classification, max_variant, min_variant, modifiedimportedvariant, nodevariant, packed_samples_allele_depth, packed_samples_allele_frequency, packed_samples_filters, packed_samples_genotype_quality, packed_samples_phred_likelihood, packed_samples_read_depth, packed_samples_zygosity, resolvedvariantinfo, svlen, tags_global, uploadedvcf, variantallele, variantannotation, variantcollectionrecord, variantgeneoverlap, varianttag, varianttranscriptannotation, variantwiki, variantzygositycount
```

**Comment by davmlaw** [comment]
Problem is ```get_grid_genotype_columns_and_overrides``` adds ```column_names.append(f"{sample.pk}_{column}")```

Which is not in the queryset annotation kwargs

I am not sure whether we should add this in  ```_get_grid_only_annotation_kwargs``` - or perhaps convert the ```get_grid_genotype_columns_and_overrides``` to work with cohort rather than samples

**Comment by davmlaw** [comment]
testing - verified sort by genotype (string) + other (array) columns works
