### ISSUE TITLE
AttributeError: 'AnalysisTemplate' object has no attribute 'version'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1052]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4995](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4995)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/mnt/variantgrid/analysis/views/views_json.py", line 443, in analysis_template_save
    return JsonResponse({"version": analysis_template.version})
AttributeError: 'AnalysisTemplate' object has no attribute 'version'
```

**Comment by davmlaw** [comment]
tested vg test - passed
