### ISSUE TITLE
ValueError: VCF header contig 'HSCHR10_1_CTG2' (length=309802) has different length than ref contig NW_003315934.1 (length=179254)

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1082]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5069](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5069)

```
Traceback (most recent call last):
  File "/opt/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 73, in run
    items_processed = self.process_items(upload_step)
  File "/opt/variantgrid/upload/tasks/vcf/import_vcf_tasks.py", line 30, in process_items
    preprocess_vcf(upload_step)
  File "/opt/variantgrid/upload/vcf/vcf_preprocess.py", line 95, in preprocess_vcf
    cleaned_vcf_header_filename = _write_cleaned_header(genome_build, upload_pipeline, vcf_filename)
  File "/opt/variantgrid/upload/vcf/vcf_preprocess.py", line 63, in _write_cleaned_header
    'write_cleaned_vcf_header(genome_build, vcf_file...ned_vcf_header_filename, new_info_lines=HEADERS)'
  File "/opt/variantgrid/library/genomics/vcf_utils.py", line 186, in write_cleaned_vcf_header
    raise ValueError(msg)
ValueError: VCF header contig 'HSCHR10_1_CTG2' (length=309802) has different length than ref contig NW_003315934.1 (length=179254)
```

**Comment by davmlaw** [comment]
This was fixed by implementing #1022 - no longer occurs
