### ISSUE TITLE
Retry variant import failing on shariant demo 

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1087]
https://demo.shariant.org.au/upload/view_upload_pipeline/9027

ScheduleMultiFileOutputTasksTask writes  "Warning: Empty VCF so no split VCF records" and doesn't 

I checked after re-running the pipeline and there is no file written

However, when I manually run it, there IS a file written!

```
/opt/variantgrid/data/import_processing/pipeline_9027/split_vcf/classification_import00.vcf.gz
```

**Comment by davmlaw** [comment]
OK, looks like celery executing a shell command that executes a manage command is not loading the virtualenv properly

There was a lot of confusing errors because some libraries were being loaded from the users .local python, but if I delete that it still happens but a lot less lines till failure:

```
[2024-06-14 13:46:58,682: INFO/ForkPoolWorker-1] single_commands: cat /opt/variantgrid/data/import_processing/classification_import_4864/classification_import.vcf | python3 /opt/variantgrid/manage.py vcf_clean_and_filter --genome-build GRCh38 --replace-header /opt/variantgrid/data/import_processing/pipeline_9027/clean_vcf_dir/classification_import.header.vcf --skipped-contigs-stats-file /opt/variantgrid/data/import_processing/pipeline_9027/classification_import.skipped_contigs.tsv --skipped-records-stats-file /opt/variantgrid/data/import_processing/pipeline_9027/classification_import.skipped_records.tsv --skipped-filters-stats-file /opt/variantgrid/data/import_processing/pipeline_9027/classification_import.skipped_filters.tsv | bcftools norm --multiallelics=- --rm-dup=exact --check-ref=w --old-rec-tag=BCFTOOLS_OLD_VARIANT --fasta-ref=/data/annotation/fasta/GCF_000001405.39_GRCh38.p13_genomic.fna.gz - | bcftools view --no-header - | split - classification_import --additional-suffix=.vcf.gz --numeric-suffixes --lines 50000 --filter='sh -c "{ cat /opt/variantgrid/data/import_processing/pipeline_9027/clean_vcf_dir/classification_import.header.vcf; cat; } | bgzip -c > /opt/variantgrid/data/import_processing/pipeline_9027/split_vcf/$FILE"'
[2024-06-14 13:46:58,775: INFO/ForkPoolWorker-1] single command pipe/shell completed - return code: 0
[2024-06-14 13:46:58,775: ERROR/ForkPoolWorker-1] b'Traceback (most recent call last):\n  File "/opt/variantgrid/manage.py", line 8, in <module>\n    from django.core.management import execute_from_command_line\nModuleNotFoundError: No module named \'django\'\nError in sys.excepthook:\nTraceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook\n    from apport.fileutils import likely_packaged, get_recent_crashes\n  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>\n    from apport.report import Report\n  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>\n    import apport.fileutils\n  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 28, in <module>\n    from apport.packaging_impl import impl as packaging\n  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>\n    import apt\nModuleNotFoundError: No module named \'apt\'\n\nOriginal exception was:\nTraceback (most recent call last):\n  File "/opt/variantgrid/manage.py", line 8, in <module>\n    from django.core.management import execute_from_command_line\nModuleNotFoundError: No module named \'django\'\nFailed to read from standard input: unknown file type\nFailed to read from standard input: unknown file type\n'
```

**Comment by davmlaw** [comment]
It appears that when running in subprocess with shell=True it is not keeping the virtual environment:

This is because you needed to update the PYTHON variable (and thus settings.MANAGEMENT_COMMAND) if you are running in a virtual environment.

I think I have fixed this by making settings use:

```
PYTHON_COMMAND = sys.executable
```

Which means it should inherit whatever it was launched with 

TODO:

While I'm here, there is still a bug with annotation, which needs fixing:

```
  File "/opt/variantgrid/annotation/tasks/annotate_variants.py",  ... RCh38' and VEP command line differ, KEY: 'ensembl_io' annotation: '110.b1a0d57', vcf: '110.0edbb93'
```

**Comment by davmlaw** [comment]
This has been fixed, not really user testable (other than seeing that it worked or not)
