### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#110]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/1953/](https://rollbar.com/jimmy.andrews/VariantGrid/items/1953/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/variantgrid/flags/views/views.py", line 346, in get
    return Response(flag_helper.to_json())
  File "/mnt/variantgrid/flags/views/views.py", line 210, in to_json
    'lab': user_settings.default_lab.name if not user.is_superuser else 'admin'
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by davmlaw** [comment]
Must not have assigned that person a lab

**Comment by davmlaw** [comment]
Looks like @TheMadBug fixed this on 20/10/2020, and hasn't reoccured since upgrade
