### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '1)'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#111]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/1984/](https://rollbar.com/jimmy.andrews/VariantGrid/items/1984/)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/variantopedia/search.py", line 349, in search_within
    build_results = get_results_func(self.search_string,
  File "/mnt/variantgrid/variantopedia/search.py", line 469, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/mnt/variantgrid/genes/hgvs.py", line 223, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1392, in parse_hgvs_name
    transcript = get_transcript(hgvs.transcript)
  File "/mnt/variantgrid/genes/hgvs.py", line 217, in get_pyhgvs_transcript
    return TranscriptVersion.get_refgene(self.genome_build, transcript_name,
  File "/mnt/variantgrid/genes/models.py", line 568, in get_refgene
    transcript_id, version = TranscriptVersion.get_transcript_id_and_version(transcript_name)
  File "/mnt/variantgrid/genes/models.py", line 535, in get_transcript_id_and_version
    version = int(parts[1])
ValueError: invalid literal for int() with base 10: '1)'
```

**Comment by davmlaw** [comment]
Someone searched for: ```NM_001193307.1):c.170T>C```

Need to make parser a little bit better to deal with stuff like that

**Comment by davmlaw** [comment]
Moved into #124 - More forgiging HGVS search
