### ISSUE TITLE
Liftover failure - ValueError: invalid literal for int() with base 10: 'Allele 33300 (CA2838033041)'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1144]
This is due to recent liftover refactoring - where I accidentally wrote ```str(allele)``` rather than ```allele.pk```

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5344](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5344)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 73, in run
    items_processed = self.process_items(upload_step)
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_tasks.py", line 112, in process_items
    items_processed = import_vcf_file(upload_step, bulk_inserter)
  File "/mnt/variantgrid/upload/vcf/vcf_import.py", line 265, in import_vcf_file
    bulk_inserter.finish()
  File "/mnt/variantgrid/upload/vcf/bulk_minimal_vcf_processor.py", line 56, in finish
    self.batch_process_check(0)  # Insert anything that is there
  File "/mnt/variantgrid/upload/vcf/bulk_minimal_vcf_processor.py", line 52, in batch_process_check
    self.batch_handle_variant_ids(variant_ids)
  File "/mnt/variantgrid/upload/vcf/bulk_allele_linking_vcf_processor.py", line 48, in batch_handle_variant_ids
    allele_id = int(allele_id)
ValueError: invalid literal for int() with base 10: 'Allele 33306 (CA2838033043)'
```

**Comment by davmlaw** [comment]
Deployed to vg.com - Deleted previous liftovers and re-run. Worked
