### ISSUE TITLE
DoesNotExist: ClassificationModification matching query does not exist.

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#1155]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5365](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5365)

```
Traceback (most recent call last):
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/opt/variantgrid/classification/views/views.py", line 257, in create_classification
    return redirect(create_classification_object(request).get_edit_url())
  File "/opt/variantgrid/classification/views/views.py", line 303, in create_classification_object
    copy_from = ClassificationModification.objects.get(pk=copy_from_id)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
DoesNotExist: ClassificationModification matching query does not exist.
```

**Comment by TheMadBug** [comment]
Seems to happen when creating a Classification without copying from an existing one, copying from an existing one works fine. (in my limited testing)

**Comment by davmlaw** [comment]
The classification does seem to be created

It says copy_from_id=0 and the line above is ```if copy_from_id``` so I don't understand how it ever got there

Might try updating code and trying to recreate

**Comment by davmlaw** [comment]
cool have moved off Shariant release. 1 less to slow down release

**Comment by davmlaw** [comment]
🤖 Written by Claude

The copy-from path was rewritten (ef34570e0, bcf3018ff), and `_get_copy_from` in `classification/views/views.py` now skips empty or '0' ids, which was the reported case.
