### ISSUE TITLE
Liftover Run - PermissionDenied: You must be a super user to view this page

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1158]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5010](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5010)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/library/django_utils/__init__.py", line 60, in wrapper
    raise PermissionDenied("You must be a super user to view this page")
PermissionDenied: You must be a super user to view this page
```

**Comment by davmlaw** [comment]
User wasn't an admin

Referrer was: https://variantgrid.com/variantopedia/view_allele/122358

Was trying to work out how this was even possible, however we DO show the liftover link to non-admin users while the variant is being created/lifted over (briefly) 

So to recreate, as a non-admin user:

* Go to a variant that hasn't yet been liftover to both builds (maybe create an existing variant with new allele, eg "NC_000003.11:g.128193760G>A")
* Click Allele link to go to allele page
* Click "Create variant" for a different genome build
* This should reload the page with a link 

> This variant is being lifted over via ClinGen Allele Registry (last updated <1 min ago )

Clicking this link causes the 403

**Comment by davmlaw** [comment]
testing - VariantGrid only - in Shariant non-admin are not allowed to lift over variants

**Comment by davmlaw** [comment]
testing - verified ok, deployed to variantgrid.com
