### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "snpdb_clingenallele_pkey"
DETAIL:  Key (id)=(923726328) already exists.


### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#116]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2025/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2025/)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/variantopedia/search.py", line 349, in search_within
    build_results = get_results_func(self.search_string,
  File "/mnt/variantgrid/variantopedia/search.py", line 636, in search_clingen_allele
    clingen_allele = get_clingen_allele(search_string)
  File "/mnt/variantgrid/snpdb/clingen_allele.py", line 300, in get_clingen_allele
    clingen_allele = ClinGenAllele.objects.create(pk=clingen_allele_id, api_response=api_response)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django_extensions/db/models.py", line 22, in save
    super().save(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 892, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 930, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1249, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "snpdb_clingenallele_pkey"
DETAIL:  Key (id)=(923726328) already exists.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
UniqueViolation: duplicate key value violates unique constraint "snpdb_clingenallele_pkey"
DETAIL:  Key (id)=(923726328) already exists.
Traceback (most recent call last):
  File "/mnt/variantgrid/snpdb/clingen_allele.py", line 294, in get_clingen_allele
    clingen_allele = ClinGenAllele.objects.get(pk=clingen_allele_id)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
DoesNotExist: ClinGenAllele matching query does not exist.
```

**Comment by davmlaw** [comment]
Race condition - I don't think it matters but we should at least double check we're handling ok and not crash etc

**Comment by davmlaw** [comment]
I thought this was just behind the scenes but it happened to Sarah she got an error message

**Comment by davmlaw** [comment]
Replaced with:

```
thread_safe_unique_together_get_or_create
```

Tested via breakpoint in debugger to recreate race condition - worked ok.

Not sure if this can be tested easily so just going to close it
