### ISSUE TITLE
DoesNotExist: Organization matching query does not exist.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1169]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5379](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5379)

```
Traceback (most recent call last):
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/auth/admin.py", line 119, in add_view
    return self._add_view(request, form_url, extra_context)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/auth/admin.py", line 147, in _add_view
    return super().add_view(request, form_url, extra_context)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1886, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1747, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1798, in _changeform_view
    self.save_model(request, new_object, form, not add)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/admin/options.py", line 1227, in save_model
    obj.save()
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/contrib/auth/base_user.py", line 76, in save
    super().save(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/db/models/base.py", line 892, in save_base
    post_save.send(
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 177, in send
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/variantgrid/snpdb/signals/signal_handlers.py", line 33, in user_post_save_handler
    organization = Organization.objects.get(group_name=org_group_name)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/variantgrid/library/django_utils/django_object_managers.py", line 52, in get
    result = super().get(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
DoesNotExist: Organization matching query does not exist.
```

**Comment by davmlaw** [comment]
verified on vg test - not used in Shariant
