### ISSUE TITLE
Error creating cohort - IntegrityError: null value in column "format" of relation "snpdb_cohortgenotype_collection_2221" violates not-null constraintDETAIL:  Failing row contains (1022146694, .....E........., {-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1}, {-1,-1,-1,-1,-1,0,-1,

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1175]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4822](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4822)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/mnt/variantgrid/snpdb/tasks/cohort_genotype_tasks.py", line 196, in cohort_genotype_task
    run_sql(insert_sql)
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
  File "/mnt/variantgrid/library/utils/database_utils.py", line 15, in run_sql
    value = cursor.execute(sql, params)  # Remember it only accepts '%s' not %d etc.
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
IntegrityError: null value in column "format" of relation "snpdb_cohortgenotype_collection_2221" violates not-null constraint
DETAIL:  Failing row contains (1022146694, .....E........., {-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1}, {-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1}, 242050667, 2221, 1, 0, {-1,-1,-1,-1,-1,47,-1,-1,-1,-1,-1,-1,-1,-1,-1}, {-1,-1,-1,-1,-1,35,-1,-1,-1,-1,-1,-1,-1,-1,-1}, {-1,-1,-1,-1,-1,0.4,-1,-1,-1,-1,-1,-1,-1,-1,-1}, 0, null, {NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NUL..., 0, null, null).
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
NotNullViolation: null value in column "format" of relation "snpdb_cohortgenotype_collection_2221" violates not-null constraint
DETAIL:  Failing row contains (1022146694, .....E........., {-1,-1,-1,-1,-1,14,-1,-1,-1,-1,-1,-1,-1,-1,-1}, {-1,-1,-1,-1,-1,0,-1,-1,-1,-1,-1,-1,-1,-1,-1}, 242050667, 2221, 1, 0, {-1,-1,-1,-1,-1,47,-1,-1,-1,-1,-1,-1,-1,-1,-1}, {-1,-1,-1,-1,-1,35,-1,-1,-1,-1,-1,-1,-1,-1,-1}, {-1,-1,-1,-1,-1,0.4,-1,-1,-1,-1,-1,-1,-1,-1,-1}, 0, null, {NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NUL..., 0, null, null).

```

**Comment by davmlaw** [comment]
VG only - not Shariant

**Comment by davmlaw** [comment]
@PeerArts - fixed and deployed on variantgrid.com (will try and find your new email too)

**Comment by davmlaw** [comment]
Fixed, deployed, no errors reported for 16 days
