### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1177]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5424](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5424)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
  File "/mnt/variantgrid/analysis/tasks/analysis_grid_export_tasks.py", line 112, in export_cohort_to_downloadable_file
    _write_node_to_cached_generated_file(cgf, analysis, node, cohort.name, export_type)
  File "/mnt/variantgrid/analysis/tasks/analysis_grid_export_tasks.py", line 68, in _write_node_to_cached_generated_file
    update_size = max(1000, total_records / 100)  # 1% or every 1k records
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by davmlaw** [comment]
This is VG only (not Shariant)

**Comment by davmlaw** [comment]
tested, fixed, deployed
