### ISSUE TITLE
RuntimeError: Search Backend failed: Couldn't resolve #PMQuerySrv_2_0?dbaf=pubmed, the address table is empty.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1184]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4494](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4494)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/variantgrid/classification/views/views.py", line 128, in get
    auto_data = generate_auto_populate_data(
  File "/data/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 76, in generate_auto_populate_data
    data.update(get_evidence_fields_for_variant(genome_build, variant,
  File "/data/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 229, in get_evidence_fields_for_variant
    'data.update(get_evidence_fields_from_transcript...me_build, variant, clingen_allele, hgvs_matcher,'
  File "/data/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 296, in get_evidence_fields_from_transcript_data
    'data.update(get_evidence_fields_from_preferred_...me_build, variant, clingen_allele, hgvs_matcher,'
  File "/data/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 384, in get_evidence_fields_from_preferred_transcript
    gs_count = GeneSymbolPubMedCount.get_for_gene_symbol(gene_symbol_id)
  File "/data/variantgrid/annotation/models/models.py", line 1057, in get_for_gene_symbol
    record = Entrez.read(h)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Entrez/__init__.py", line 508, in read
    record = handler.read(handle)
  File "/usr/local/lib/python3.8/dist-packages/Bio/Entrez/Parser.py", line 304, in read
    self.parser.ParseFile(handle)
  File "../Modules/pyexpat.c", line 459, in EndElement
  File "/usr/local/lib/python3.8/dist-packages/Bio/Entrez/Parser.py", line 666, in endErrorElementHandler
    raise RuntimeError(value)
RuntimeError: Search Backend failed: An error occurred while processing request. Status: 500. Source: /api/search/?r= Details: Search is temporarily unavailable. Please try again later. Details: Cannot connect to SOLR
```

**Comment by davmlaw** [comment]
API issue

Threw RuntimeError was expecting different one, now caught also

Need to deploy to SAP

**Comment by davmlaw** [comment]
Create classifications - not Shariant core functionality but still there for admins. Probably doesn't need testing there
