### ISSUE TITLE
Create classifications broken on system with CohortGenotypeCommonFilterVersion for gnomAD version not found in annotation version

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1187]
I forgot to change ```settings.VCF_IMPORT_COMMON_FILTERS``` gnomAD version, and this created an old 3.1 version for 38

There was no annotation for it, so it broke below.

We should make sure that in ```variants_classification_changed``` we only use ```CohortGenotypeCommonFilterVersion``` that has a cohort genotype collection associated with it

DoesNotExist: Can't find VariantAnnotationVersion({'gnomad': '3.1', 'genome_build': <GenomeBuild: GRCh38>})

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5461](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5461)

```
Traceback (most recent call last):
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/opt/variantgrid/classification/views/views.py", line 236, in create_classification
    return redirect(create_classification_object(request).get_edit_url())
  File "/opt/variantgrid/classification/views/views.py", line 267, in create_classification_object
    classification = create_classification_for_sample_and_variant_objects(request.user, sample,
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 52, in create_classification_for_sample_and_variant_objects
    allele_info.set_variant_and_save(matched_variant=variant)
  File "/opt/variantgrid/classification/models/classification_variant_info_models.py", line 876, in set_variant_and_save
    allele_info_changed_signal.send(sender=ImportedAlleleInfo, allele_info=self)
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 177, in send
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/variantgrid/classification/signals/classification_hooks_variants_classification_changes.py", line 49, in allele_info_changed_update_classifications
    _send_variants_classification_changed_for(allele)
  File "/opt/variantgrid/classification/signals/classification_hooks_variants_classification_changes.py", line 18, in _send_variants_classification_changed_for
    variants_classification_changed_signal.send(sender=Classification,
  File "/opt/variantgrid/env/lib/python3.12/site-packages/django/dispatch/dispatcher.py", line 177, in send
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/variantgrid/snpdb/common_variants.py", line 82, in variants_classification_changed
    for variant in get_classified_high_frequency_variants_qs(cgcfv, alleles=alleles):
  File "/opt/variantgrid/snpdb/common_variants.py", line 54, in get_classified_high_frequency_variants_qs
    raise VariantAnnotationVersion.DoesNotExist(f"Can't find VariantAnnotationVersion({kwargs})")
DoesNotExist: Can't find VariantAnnotationVersion({'gnomad': '3.1', 'genome_build': <GenomeBuild: GRCh38>})
```

**Comment by davmlaw** [comment]
Fixed and deployed to VG prod, classifications have been created ok since
