### ISSUE TITLE
User Feedback : unable to tag variant

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1188]
I encountered an issue with tagging variants in VG3. I was unable to tag a variant, as the drop-down box appeared as a dashed line. After reloading the page, the function temporarily worked, allowing me to tag one variant, then the issue reappeared. 

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5464](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5464)

```
User Feedback : unable to tag variant
```

**Comment by davmlaw** [comment]
http://frgeneseq02.imvs.sa.gov.au:92/analysis/53292/

Browser was:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0
```

**Comment by davmlaw** [comment]
Confirm issue occurs in Edge.

Confirm that warning about obsolete / not tested browser does NOT appear in edge



```
rollbar.min.js:1  The select2('open') method was called on an element that is not using Select2.
e.<computed> @ rollbar.min.js:1
(anonymous) @ VM189:2
each @ jquery-3.3.1.min.a09e13ee94d5.js:2
each @ jquery-3.3.1.min.a09e13ee94d5.js:2
r.fn.select2 @ VM189:2
(anonymous) @ grid.2bb9cb8aea5f.js:395
(anonymous) @ jquery-3.3.1.min.a09e13ee94d5.js:2
each @ jquery-3.3.1.min.a09e13ee94d5.js:2
each @ jquery-3.3.1.min.a09e13ee94d5.js:2
(anonymous) @ jquery-3.3.1.min.a09e13ee94d5.js:2
u @ jquery-3.3.1.min.a09e13ee94d5.js:2
fireWith @ jquery-3.3.1.min.a09e13ee94d5.js:2
k @ jquery-3.3.1.min.a09e13ee94d5.js:2
(anonymous) @ jquery-3.3.1.min.a09e13ee94d5.js:2
t._rollbar_wrapped.t._rollbar_wrapped @ rollbar.min.js:1
load
u @ rollbar.min.js:1
e @ rollbar.min.js:1
(anonymous) @ rollbar.min.js:1
send @ jquery-3.3.1.min.a09e13ee94d5.js:2
ajax @ jquery-3.3.1.min.a09e13ee94d5.js:2
w.fn.load @ jquery-3.3.1.min.a09e13ee94d5.js:2
showTagAutocomplete @ grid.2bb9cb8aea5f.js:379
(anonymous) @ VM205:1
rollbar.min.js:1  Uncaught TypeError: Cannot read properties of undefined (reading 'open')
    at HTMLSelectElement.<anonymous> (<anonymous>:2:74718)
    at Function.each (jquery-3.3.1.min.a09e13ee94d5.js:2:2573)
    at w.fn.init.each (jquery-3.3.1.min.a09e13ee94d5.js:2:1240)
    at r.fn.select2 (<anonymous>:2:74530)
    at HTMLSpanElement.<anonymous> (grid.2bb9cb8aea5f.js:395:19)
    at HTMLSpanElement.<anonymous> (jquery-3.3.1.min.a09e13ee94d5.js:2:82776)
    at Function.each (jquery-3.3.1.min.a09e13ee94d5.js:2:2573)
    at w.fn.init.each (jquery-3.3.1.min.a09e13ee94d5.js:2:1240)
    at Object.<anonymous> (jquery-3.3.1.min.a09e13ee94d5.js:2:82758)
    at u (jquery-3.3.1.min.a09e13ee94d5.js:2:27457)
(anonymous) @ VM189:2
each @ jquery-3.3.1.min.a09e13ee94d5.js:2
each @ jquery-3.3.1.min.a09e13ee94d5.js:2
r.fn.select2 @ VM189:2
(anonymous) @ grid.2bb9cb8aea5f.js:395
(anonymous) @ jquery-3.3.1.min.a09e13ee94d5.js:2
each @ jquery-3.3.1.min.a09e13ee94d5.js:2
each @ jquery-3.3.1.min.a09e13ee94d5.js:2
(anonymous) @ jquery-3.3.1.min.a09e13ee94d5.js:2
u @ jquery-3.3.1.min.a09e13ee94d5.js:2
fireWith @ jquery-3.3.1.min.a09e13ee94d5.js:2
k @ jquery-3.3.1.min.a09e13ee94d5.js:2
(anonymous) @ jquery-3.3.1.min.a09e13ee94d5.js:2
t._rollbar_wrapped.t._rollbar_wrapped @ rollbar.min.js:1
load
u @ rollbar.min.js:1
e @ rollbar.min.js:1
(anonymous) @ rollbar.min.js:1
send @ jquery-3.3.1.min.a09e13ee94d5.js:2
ajax @ jquery-3.3.1.min.a09e13ee94d5.js:2
w.fn.load @ jquery-3.3.1.min.a09e13ee94d5.js:2
showTagAutocomplete @ grid.2bb9cb8aea5f.js:379
(anonymous) @ VM205:1
3trans_defs.js:2747 Imprivata CE >> Process DOM-mutation event (content.js:709)
```

**Comment by davmlaw** [comment]
Also have warning:

[Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.

This message does NOT appear in more modern versions of VariantGrid

Using Edge, I can tag variants ok in variantgrid.com

**Comment by davmlaw** [comment]
Need to patch back to SAP VG3:

abstract_login_bs.html - Set edge required to super high to catch all versions

```
e:9999
```


```
    text_for_e: {
       'msg':'Sorry but we do not support Microsoft Edge in VG3',
       'msgmore': 'Please use Chrome, FireFox or Safari'
    }
```

**Comment by davmlaw** [comment]
Someone reported that this is happening again today.

Tried Chromium Version 131.0.6778.85 (Official Build) snap (64-bit) - Worked ok
Try windows computer

**Comment by davmlaw** [comment]
Upgraded to latest autocomplete and merged in other fixes, confirmed it worked on windows machine.
