### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1189]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5481](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5481)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/views/decorators/vary.py", line 42, in inner_func
    response = func(*args, **kwargs)
  File "/mnt/variantgrid/analysis/views/views_grid.py", line 67, in get
    response = self.get_response(request, *args, **kwargs)
  File "/mnt/variantgrid/analysis/views/node_json_view.py", line 29, in get_response
    data = self._get_data(request, *args, node=node, **kwargs)
  File "/mnt/variantgrid/analysis/views/views_grid.py", line 93, in _get_data
    return grid.get_data(request)
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 347, in get_data
    'rows': list(items),
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 334, in iter_formatted_items
    row[f] = formatter(row, f)
  File "/mnt/variantgrid/analysis/grids.py", line 169, in packed_data_formatter
    val = packed_data[i]
IndexError: list index out of range
```

**Comment by davmlaw** [comment]
🤖 Written by Claude

The traceback is in `library/jqgrid` / `packed_data_formatter`, both removed when variant grids moved to the native DataTables engine (91960ad7d, #1815). This can be reopened if Rollbar shows it on the new grid.
