### ISSUE TITLE
subprocess.CalledProcessError: Command '['bcftools', 'index', '/mnt/variantgrid/data/import_processing/pipeline_7783/split_vcf/dragen_mutect_vardict_shared00.vcf.gz']' returned non-zero exit status 255.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1190]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5480](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5480)

```
UploadPipeline 7783 failed. Filename: VCF Error: Error executing: Command '['bcftools', 'index', '/mnt/variantgrid/data/import_processing/pipeline_7783/split_vcf/dragen_mutect_vardict_shared00.vcf.gz']' returned non-zero exit status 255.
Traceback (most recent call last):
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 73, in run
    items_processed = self.process_items(upload_step)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/variantgrid/upload/tasks/vcf/unknown_variants_task.py", line 115, in process_items
    subprocess.run(cmd_index, capture_output=True, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['bcftools', 'index', '/mnt/variantgrid/data/import_processing/pipeline_7783/split_vcf/dragen_mutect_vardict_shared00.vcf.gz']' returned non-zero exit status 255.

```

**Comment by davmlaw** [comment]
Happened once, 9 months ago, cannot reproduce (rollbar expired)
