### ISSUE TITLE
FieldError: Cannot resolve keyword 'cohortgenotype_840' into field. Choices are: all_zygosity_counts_1, allvariantsnode, alt, alt_id, classification, clinvar, cohortgenotype, cohortgenotype_668, commonvariantclassified, createdmanualvariant, end, germline

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1196]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4811](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4811)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/views/decorators/vary.py", line 42, in inner_func
    response = func(*args, **kwargs)
  File "/mnt/variantgrid/analysis/views/views_grid.py", line 67, in get
    response = self.get_response(request, *args, **kwargs)
  File "/mnt/variantgrid/analysis/views/node_json_view.py", line 29, in get_response
    data = self._get_data(request, *args, node=node, **kwargs)
  File "/mnt/variantgrid/analysis/views/views_grid.py", line 93, in _get_data
    return grid.get_data(request)
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 343, in get_data
    paginator, page, items = self.get_items(request)
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 158, in get_items
    items = self.get_queryset(request)
  File "/mnt/variantgrid/snpdb/grids.py", line 413, in get_queryset
    qs = qs.annotate(**a_kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/models/query.py", line 1590, in annotate
    return self._annotate(args, kwargs, select=True)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/models/query.py", line 1638, in _annotate
    clone.query.add_annotation(
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1133, in add_annotation
    annotation = annotation.resolve_expression(self, allow_joins=True, reuse=None)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/models/expressions.py", line 950, in resolve_expression
    c.source_expressions[pos] = arg.resolve_expression(
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/models/expressions.py", line 829, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1977, in resolve_ref
    join_info = self.setup_joins(
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1824, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1725, in names_to_path
    raise FieldError(
FieldError: Cannot resolve keyword 'cohortgenotype_840' into field. Choices are: all_zygosity_counts_1, allvariantsnode, alt, alt_id, classification, clinvar, cohortgenotype, cohortgenotype_668, commonvariantclassified, createdmanualvariant, end, germline_counts_1, global_variant_zygosity, id, importedalleleinfo, internally_classified, internally_classified_labs, intersectionnode, locus, locus_id, max_internal_classification, max_variant, min_variant, modifiedimportedvariant, nodevariant, resolvedvariantinfo, svlen, tags_global, uploadedvcf, variantallele, variantannotation, variantcollectionrecord, variantgeneoverlap, varianttag, varianttranscriptannotation, variantwiki, variantzygositycount
```

**Comment by davmlaw** [comment]
2 samples from same VCF, with Venn node below with intersection

**Comment by davmlaw** [comment]
This also affects MergeNode

```
  File "/home/dlawrence/localwork/variantgrid/analysis/grids.py", line 169, in packed_data_formatter
    val = packed_data[i]
          ~~~~~~~~~~~^^^
IndexError: string index out of range
```

Problem is in: ```get_variantgrid_zygosity_annotation_kwargs```

We need the annotation kwargs dict to have things in dependency order, but we overwrite ```packed_``` column, which comes first, before adding the second cohort, like so:

```
'packed_samples_filters': Coalesce(F(cohortgenotype_211__samples_filters), Value(['NULL', 'NULL'])), 'cohortgenotype_211': <django.db.models.query_utils.FilteredRelation object at 0x7e7c96ebc910>
```

**Comment by davmlaw** [comment]
Bug was introduced in #766 - I didn't pack all the cohorts together.

Testing vg test:

Reproduced issue in analysis http://test.variantgrid.com/analysis/27/
Will check once deployed
