### ISSUE TITLE
subprocess.CalledProcessError: Command 'bcftools +liftover /mnt/variantgrid/data/import_processing/liftover_4484/source_variants.GRCh37.vcf -- --src-fasta-ref /data/annotation/fasta/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --fasta-ref /data/annot

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1197]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5342](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5342)

```
UploadPipeline 7903 failed. Filename: Liftover Error: Error executing: Command 'bcftools +liftover /mnt/variantgrid/data/import_processing/liftover_4728/source_variants.GRCh37.vcf -- --src-fasta-ref /data/annotation/fasta/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --fasta-ref /data/annotation/fasta/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --chain /data/annotation/liftover/GRCh37_to_GRCh38.chain.gz --reject /mnt/variantgrid/data/import_processing/liftover_4728/rejected_liftover_variants.GRCh38.vcf --write-reject | bcftools sort -Oz -o /mnt/variantgrid/data/import_processing/liftover_4728/liftover_variants.GRCh38.vcf' returned non-zero exit status 255.
Traceback (most recent call last):
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 73, in run
    items_processed = self.process_items(upload_step)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_tasks.py", line 148, in process_items
    reject_vcf, num_rejected = bcftools_liftover(upload_step.input_filename, liftover.source_genome_build,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/variantgrid/snpdb/bcftools_liftover.py", line 80, in bcftools_liftover
    raise CalledProcessError(return_code, cmd_str, output=std_out, stderr=std_err)
subprocess.CalledProcessError: Command 'bcftools +liftover /mnt/variantgrid/data/import_processing/liftover_4728/source_variants.GRCh37.vcf -- --src-fasta-ref /data/annotation/fasta/Homo_sapiens.GRCh37.75.dna.primary_assembly.fa.gz --fasta-ref /data/annotation/fasta/Homo_sapiens.GRCh38.dna.toplevel.fa.gz --chain /data/annotation/liftover/GRCh37_to_GRCh38.chain.gz --reject /mnt/variantgrid/data/import_processing/liftover_4728/rejected_liftover_variants.GRCh38.vcf --write-reject | bcftools sort -Oz -o /mnt/variantgrid/data/import_processing/liftover_4728/liftover_variants.GRCh38.vcf' returned non-zero exit status 255.

```

**Comment by davmlaw** [comment]
This was what failed:

https://variantgrid.com/snpdb/liftover/view_liftover_run/4728

Variant in VCF was written as: HSCHR1_RANDOM_CTG5

This wasn't in the fasta fai - so whole run died. Need to restrict contigs to normal ones
