### ISSUE TITLE
Variant Grid crashing if "tags" not in custom columns

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1198]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5529](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5529)

ValueError: list.remove(x): x not in list

```
Traceback (most recent call last):
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/variantgrid/env/lib/python3.12/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 61, in get
    grid_obj = self._load_grid(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 57, in _load_grid
    return self.create_grid_from_request(request, grid_klass, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 40, in create_grid_from_request
    return grid_klass(**kwargs)
  File "/mnt/variantgrid/variantopedia/grids.py", line 215, in __init__
    fields.remove("tags")
ValueError: list.remove(x): x not in list
```

**Comment by davmlaw** [comment]
This was because the user had removed tags from their custom columns

**Comment by davmlaw** [comment]
tested vg test - passed
