### ISSUE TITLE
ValueError: Variant hash (96, 1456177, 185113, 688451, -983) had no PK in DB!

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#1209]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5566](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/5566)

This is due to importing symbolic variants that had a SVLEN shorter than our 1k limit (eg -989)

I modified the add in a recent change, but also need to do the convert to correct representation in ```get_variant_ids```

```
Traceback (most recent call last):
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 73, in run
    items_processed = self.process_items(upload_step)
  File "/mnt/variantgrid/upload/tasks/vcf/genotype_vcf_tasks.py", line 115, in process_items
    return import_vcf_file(upload_step, bulk_inserter)
  File "/mnt/variantgrid/upload/vcf/vcf_import.py", line 265, in import_vcf_file
    bulk_inserter.finish()
  File "/mnt/variantgrid/upload/vcf/bulk_genotype_vcf_processor.py", line 139, in finish
    self.batch_process_check(0)  # Insert anything that is there
  File "/mnt/variantgrid/upload/vcf/bulk_genotype_vcf_processor.py", line 447, in batch_process_check
    variant_ids = self.variant_pk_lookup.get_variant_ids(self.variant_hashes)
  File "/mnt/variantgrid/snpdb/variant_pk_lookup.py", line 87, in get_variant_ids
    raise ValueError(f"Variant hash {variant_hash} had no PK in DB!")
ValueError: Variant hash (108, 104950928, 262255, 688451, -989) had no PK in DB!
```

**Comment by davmlaw** [comment]
tested, deployed vg.com
