### ISSUE TITLE
BadTranscript: The transcript 'ENST00000264448.6' does not exist in the Ensembl database.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#123]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/1939/](https://rollbar.com/jimmy.andrews/VariantGrid/items/1939/)

```
Traceback (most recent call last):
  File "/opt/variantgrid/classification/models/classification.py", line 1838, in _generate_c_hgvs_extra
    c_hgvs = hgvs_matcher.variant_to_c_hgvs_extra(variant, transcript_id)
  File "/opt/variantgrid/genes/hgvs.py", line 338, in variant_to_c_hgvs_extra
    return self.variant_to_hgvs_extra(variant, transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 308, in variant_to_hgvs_extra
    transcript = self.get_pyhgvs_transcript(transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 222, in get_pyhgvs_transcript
    return TranscriptVersion.get_refgene(self.genome_build, transcript_name,
  File "/opt/variantgrid/genes/models.py", line 589, in get_refgene
    TranscriptVersion.raise_bad_or_missing_transcript(genome_build, transcript_id, version)
  File "/opt/variantgrid/genes/models.py", line 555, in raise_bad_or_missing_transcript
    'raise BadTranscript(f"The transcript \'{accessi...exist in the {annotation_consortium} database.")'
BadTranscript: The transcript 'ENST00000440501.1' does not exist in the Ensembl database.
```

**Comment by davmlaw** [comment]
I think this is due to Agilent using transcripts that have never been released for a particular genome build. A minor fix to make the error messages better would be:

* Check whether the transcript version exists at all - ie the other genome build
* When throwing the exception - state what genome build we looked it up in (and whether it exists in any other build)

**Comment by davmlaw** [comment]
I added genome build to the message, but haven't checked in other build yet.

@TheMadBug this is the issue....

**Comment by davmlaw** [comment]
Moved to variantgrid_private 2152
