### ISSUE TITLE
Need better error handling on bad/unsorted VCFs

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#127]
* Upload a VCF that isn't sorted
* VT will throw lots of warnings/errors due to the VCF not being sorted

Expected behavior: These errors will be shown to the user and say the VCF is not sorted - or just die
Actual behavior: No errors are shown

**Comment by davmlaw** [comment]
We now use bcftools instead of VT but has same issue, ie dies with:

```
[E::hts_idx_push] Unsorted positions on sequence #1: 154560359 followed by 154560345
```

But the error message the user gets is pretty terrible:

```
Error: Error executing: Command '['bcftools', 'index', '/home/dlawrence/localwork/variantgrid/data/import_processing/pipeline_203/split_vcf/IKBKG_VUS00.vcf.gz']' returned non-zero exit status 255. Traceback (most recent call last): File "/home/dlawrence/localwork/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 88, in run items_processed = self.process_items(upload_step) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/dlawrence/localwork/variantgrid/upload/tasks/vcf/unknown_variants_task.py", line 116, in process_items subprocess.run(cmd_index, capture_output=True, check=True) File "/usr/lib/python3.12/subprocess.py", line 571, in run raise CalledProcessError(retcode, process.args, subprocess.CalledProcessError: Command '['bcftools', 'index', '/home/dlawrence/localwork/variantgrid/data/import_processing/pipeline_203/split_vcf/IKBKG_VUS00.vcf.gz']' returned non-zero exit status 255.
```

**Comment by davmlaw** [comment]
tested vg test - passed
