### ISSUE TITLE
DoesNotExist: GenomeBuild matching query does not exist.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#167]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2138/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2138/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1693, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 735, in get_changelist_instance
    return ChangeList(
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/views/main.py", line 99, in __init__
    self.queryset = self.get_queryset(request)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/views/main.py", line 454, in get_queryset
    new_qs = filter_spec.queryset(request, qs)
  File "/mnt/variantgrid/classification/models/admin_forms.py", line 129, in queryset
    substring = GenomeBuild.objects.get(pk=self.value()).name
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
DoesNotExist: GenomeBuild matching query does not exist.
```

**Comment by davmlaw** [comment]
Sarah on RUNX1

* https://runx1db.runx1-fpd.org/admin/classification/classification/
* clicked on 'master' in the By User Filter
* internal server error

**Comment by davmlaw** [comment]
Was due to ```ClassificationImportedGenomeBuildFilter``` having parameter_name = 'user' (same as ClassificationUserFilter)

**Comment by sksmi** [comment]
Passed. 

vg.test admin > classifications > filter on dlawrence > classifications appropriately filtered.
