### ISSUE TITLE
ValueError: None is not a valid UploadedFileTypes

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#185]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2170/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2170/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/upload/views/views.py", line 191, in upload
    file_dicts_list = get_file_dicts_list(upload_settings)
  File "/mnt/variantgrid/upload/views/views.py", line 173, in get_file_dicts_list
    file_dicts.append(uploadedfile_dict(uploaded_file))
  File "/mnt/variantgrid/upload/views/views.py", line 64, in uploadedfile_dict
    'file_type': UploadedFileTypes(uploaded_file.file_type).label,
  File "/usr/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/usr/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/usr/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: None is not a valid UploadedFileTypesTraceback (most recent call last):

ValueError: None is not a valid UploadedFileTypes
```

**Comment by davmlaw** [comment]
I found and fixed this Friday night in prod and redeployed, this is only happening in vg test.

upgraded and issue went away.
