### ISSUE TITLE
IntegrityError: insert or update on table "analysis_analysisnode" violates foreign key constraint "analysis_analysisnod_analysis_id_69fe0d12_fk_analysis_"
DETAIL:  Key (analysis_id)=(1821) is not present in table "analysis_analysis".


### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#210]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2223/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2223/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/mnt/variantgrid/analysis/tasks/node_update_tasks.py", line 76, in update_node_task
    node.save()  # Will set background color etc based on errors
  File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 757, in save
    super_save(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django_extensions/db/models.py", line 22, in save
    super().save(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 750, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 787, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/transaction.py", line 232, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
IntegrityError: insert or update on table "analysis_analysisnode" violates foreign key constraint "analysis_analysisnod_analysis_id_69fe0d12_fk_analysis_"
DETAIL:  Key (analysis_id)=(1826) is not present in table "analysis_analysis".
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
ForeignKeyViolation: insert or update on table "analysis_analysisnode" violates foreign key constraint "analysis_analysisnod_analysis_id_69fe0d12_fk_analysis_"
DETAIL:  Key (analysis_id)=(1826) is not present in table "analysis_analysis".

```

**Comment by davmlaw** [comment]
This is from someone deleting an analysis while it's still running. It should be solved by variantgrid_com issue 2

It doesn't matter, but would be good to check for and handle this as it's annoying to appear in logs

**Comment by davmlaw** [comment]
Done a few things to stop this happening again....

No easy way to test, will just make a note to check rollbar every so often and see if this occurs
