### ISSUE TITLE
ValueError: Out of range float values are not JSON compliant

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#218]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2246/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2246/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 60, in get
    return HttpResponse(grid_obj.get_json(request), content_type="application/json")
  File "/mnt/variantgrid/library/jqgrid.py", line 343, in get_json
    return json_encode(data)
  File "/mnt/variantgrid/library/jqgrid.py", line 49, in json_encode
    return encoder.encode(data)
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

**Comment by davmlaw** [comment]
I think this is due to RVIS

**Comment by sksmi** [comment]
Closing as haven't seen it since upgrade.
