### ISSUE TITLE
VariantAlleleForVariant - handle failure - KeyError: <GenomeBuild: GRCh37 (aka hg19)>

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#22]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/1313/](https://rollbar.com/jimmy.andrews/VariantGrid/items/1313/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/variantgrid/snpdb/views/views_rest.py", line 53, in get
    variant_allele = get_variant_allele_for_variant(genome_build, variant)
  File "/mnt/variantgrid/snpdb/clingen_allele.py", line 218, in get_variant_allele_for_variant
    va = variant_allele_by_build[genome_build]
KeyError: <GenomeBuild: GRCh37 (aka hg19)>Traceback (most recent call last):
  File "/mnt/variantgrid/snpdb/clingen_allele.py", line 191, in get_variant_allele_for_variant
    va = VariantAllele.objects.get(variant=variant)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 406, in get
    raise self.model.DoesNotExist(
DoesNotExist: VariantAllele matching query does not exist.
```

**Comment by davmlaw** [comment]
You can send ClinGen allele registry a GRCh37 coordinate, ie ```NC_000001.10:g.145299792A>G``` and it retrieves record  CA1051218 but the API response doesn't contain GRCh37

So, send in the fact we know this variant/allele are linked, and use as a fallback if API is mysteriously empty
