### ISSUE TITLE
MergeNode - remove cache parents - optimisation with common parents

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#240]
In a recent SA Path benchmark, nodes that used cache took 3x as long to load, while having on average 1/4 the number of variants - so 12x as slow.

Writes are a massive performance hit - we need to remove them.

Given an analysis:
```
            A
          /   \
         B     C
          \   /
          Merge
```

Merge is currently (A&B) | (A&C)

But we could optimise it to be A & (B | C)

To get this, we need to introduce a method that returns a Q for just the node, not after applying parent queries as well

**Analysis Nodes**

```get_arg_q_dict(disable_cache=True)```
See also ```AnalysisNode.merge_arg_q_dicts ``` 

[wiki on nodes](https://github.com/SACGF/variantgrid/wiki/Analysis-Nodes#node-q-objects)

**Comment by davmlaw** [comment]
The original code that put in the cache is here:

[MergeNode - parents don't use NodeCache when modifies_parents is False](https://github.com/SACGF/variantgrid/issues/144)
[Merge Node is slow](https://github.com/SACGF/variantgrid_private/issues/1644)

It was done to speed up the FPDD analysis, ie: https://runx1db.runx1-fpd.org/analysis/783/

I tried quickly replacing the with a simple merge of parent args_q_dict objects, then hand-optimised the SQL (to share common ancestor logical operations) and couldn't get any performance difference out of it, trying a few different things. Maybe the SQL optimiser + the args_q_dict changes now make it unecessary to perform manual last common ancestor optimisations?

I will try recreating the FPDD style analyses and see if that makes a difference.

TODO: If we go through and remove the caches, we should probably go and delete historical caches as they may be taking up lots of space

**Comment by davmlaw** [comment]
FPDD now seems fine. And again, doesn't appear to have any advantage handwriting SQL to remove the redundancies

Thinking about it, the problem the cache tried to address was probably fixed in #580 - so has not been useful since that was done, we just hadn't realised. So yeah just remove all that complexity and don't use the cache

**Comment by davmlaw** [comment]
**Benchmarks**

https://docs.google.com/spreadsheets/d/1LAENyqq4W6mBNfBCNimKxb5zQDPGFHoh7wnLTeYLlyU/edit?usp=sharing

**Testing**

http://localhost:8000/analysis/10650/

FAILED - 12 came up before, now 13 appear

ENST00000319653.9:c.2963C>T NEW one
ENST00000319653.9:c.2828C>T - This was also in impact node above comp het (both HET for FMN2 - not sure why this didn't come through in C het node??)

It looks like the new one is right. Not sure why but need to look into it more

**Comment by davmlaw** [comment]
Working in branch merge_node_optimise

The plan is to find what filters are being commonly applied, then rewrite the query to only include the minimum OR that we need.

I've done this by changing args_q_dict to be a set of q objects (that you apply an AND to at the end) that allows us to find the duplicates before they are squished into Q objects (via AND)

The issue is, however, that we can't easily check Q objects for being identical, because they often use ```Q(pk__in=queryset)``` which hashes differently for different querysets

I think perhaps the way to deal with this is to generate a hash for each node's configuration, and use ```{node_hash: Q}``` instead of ```set(Q)``` 

```analysis.models.nodes.filters.merge_node.MergeNode._get_arg_q_dict_from_parents_and_node```

**Comment by davmlaw** [comment]
I've tried a few different things and not convinced I can re-arrange things to be faster.

Should try and benchmark say a merge at the bottom nodes of trio analysis.

Should also introduce a test for merge node where the count has to be greater than the highest parent (to detect any errors in the joining)

**Comment by davmlaw** [comment]
TODO: still small issue when connecting 2 source nodes together - probably because they don't have anything in the args_q_dict[None]

```
[2022-11-02 16:57:23,962: INFO/ForkPoolWorker-2] Node 7597/6 status: E (old: Q) errored: Traceback (most recent call last):
  File "/home/dlawrence/localwork/variantgrid/analysis/tasks/node_update_tasks.py", line 44, in update_node_task
    node.load()
  File "/home/dlawrence/localwork/variantgrid/analysis/models/nodes/analysis_node.py", line 884, in load
    status, count = self.node_counts()
  File "/home/dlawrence/localwork/variantgrid/analysis/models/nodes/analysis_node.py", line 855, in node_counts
    retrieved_label_counts = get_node_counts_and_labels_dict(self, counts_to_get)
  File "/home/dlawrence/localwork/variantgrid/analysis/models/nodes/node_counts.py", line 74, in get_node_counts_and_labels_dict
    qs = node.get_queryset(inner_query_distinct=True)
  File "/home/dlawrence/localwork/variantgrid/analysis/models/nodes/analysis_node.py", line 522, in get_queryset
    arg_q_dict = self.get_arg_q_dict(disable_cache=disable_cache)
  File "/home/dlawrence/localwork/variantgrid/analysis/models/nodes/analysis_node.py", line 410, in get_arg_q_dict
    arg_q_dict = self._get_arg_q_dict_from_parents_and_node()
  File "/home/dlawrence/localwork/variantgrid/analysis/models/nodes/filters/merge_node.py", line 144, in _get_arg_q_dict_from_parents_and_node
    return self._get_merged_q_dict(parent_arg_q_dict)
  File "/home/dlawrence/localwork/variantgrid/analysis/models/nodes/filters/merge_node.py", line 129, in _get_merged_q_dict
    if q := self._split_common_filters(parent_arg_q_dict):
  File "/home/dlawrence/localwork/variantgrid/analysis/models/nodes/filters/merge_node.py", line 60, in _split_common_filters
    most_common = sorted(arg_q_nodes.items(), key=lambda x: len(x[1]), reverse=True)[0]
IndexError: list index out of range
```

**Comment by davmlaw** [comment]
tested and benchmarked thoroughly including in SA path patchback
