### ISSUE TITLE
Discordance Report Admin page breaks

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#254]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2113/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2113/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 1568, in _changeform_view
    ModelForm = self.get_form(
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 711, in get_form
    raise FieldError(
FieldError: 'report_started_date' cannot be specified for DiscordanceReport model form as it is a non-editable field. Check fields/fieldsets/exclude attributes of class ModelAdminBasics.Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/admin/options.py", line 709, in get_form
    return modelform_factory(self.model, **defaults)
  File "/usr/local/lib/python3.8/dist-packages/django/forms/models.py", line 555, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/usr/local/lib/python3.8/dist-packages/django/forms/models.py", line 253, in __new__
    fields = fields_for_model(
  File "/usr/local/lib/python3.8/dist-packages/django/forms/models.py", line 150, in fields_for_model
    raise FieldError(
FieldError: 'report_started_date' cannot be specified for DiscordanceReport model form as it is a non-editable field
```

**Comment by TheMadBug** [comment]
Discordance Report Admin page should work as expected now.

**Comment by EmmaTudini** [comment]
Testing:
- Logged in to Shariant test with admin account
- Went to admin>classification>discordance reports
- Clicked on discordance report 13

Expected output: No error

Actual output: Passed

**Comment by TheMadBug** [comment]
I patched this to production (along with the improved admin page for discordance) so we could use it for the meeting (back when there was no other difference between test and prod)
