### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#270]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2376/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2376/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/patients/views.py", line 37, in view_patient
    patient = form.save()
  File "/mnt/variantgrid/patients/forms.py", line 54, in save
    patient.save(phenotype_approval_user=self.user)
  File "/mnt/variantgrid/patients/models.py", line 200, in save
    HasPhenotypeDescriptionMixin.save_phenotype(self, pheno_kwargs)
  File "/mnt/variantgrid/annotation/models/has_phenotype_description_mixin.py", line 116, in save_phenotype
    self.process_phenotype_if_changed(**kwargs)
  File "/mnt/variantgrid/annotation/models/has_phenotype_description_mixin.py", line 67, in process_phenotype_if_changed
    phenotype_matcher = PhenotypeMatcher()
  File "/mnt/variantgrid/annotation/phenotype_matcher.py", line 77, in __init__
    self.omim_pks = self._get_omim_pks_by_term()
  File "/mnt/variantgrid/annotation/phenotype_matcher.py", line 336, in _get_omim_pks_by_term
    term = term.strip().lower().replace(",", "")
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by TheMadBug** [comment]
Null OMIM names cause problems with the patient phenotype matcher.

There are 3 possible solutions to this:
* Get an OMIM license for each environment (even if this fixes the problem, it doesn't guarentee we wont get a future OMIM ID that we don't know about)
* Make sure all code can handle null names
* Change the ontology builder so `def _add_term_stub(self, term_id: str):` will add `"name":term_id` to the defaults. Repeating the term_id for the name isn't great, but it means the name will be unique and phenotype_to_genes doesn't give us anything else to work with.

**Comment by davmlaw** [comment]
Yeah I will apply for an OMIM licence

Need to fix if missing though, as it should never be mandatory though, only an optional add on

**Comment by davmlaw** [comment]
To reproduce: enter "thrombocytopenia" in patient phenotype

**Comment by sksmi** [comment]
any ideas how to test this one?

**Comment by sksmi** [comment]
Closing as haven't seen it for a while. Will re-open if error returns.
