### ISSUE TITLE
ContigNotInBuildError: 'NC_000010.10' not in GRCh38

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#272]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2378/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2378/)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/variantopedia/search.py", line 357, in search_within
    build_results = get_results_func(self.search_string,
  File "/mnt/variantgrid/variantopedia/search.py", line 484, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/mnt/variantgrid/genes/hgvs.py", line 234, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1405, in parse_hgvs_name
    chrom, start, _, ref, alt = get_vcf_allele(hgvs, genome, transcript)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 673, in get_vcf_allele
    ref = get_genomic_sequence(genome, chrom, start, end)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 518, in get_genomic_sequence
    return str(genome[str(chrom)][start - 1:end]).upper()
  File "/mnt/variantgrid/library/genomics/fasta_wrapper.py", line 36, in __getitem__
    contig = self.convert_chrom_func(contig)
  File "/mnt/variantgrid/snpdb/models/models_genome.py", line 306, in convert_chrom_to_fasta_sequence
    raise Contig.ContigNotInBuildError(f"'{chrom}' not in {self.genome_build}")
ContigNotInBuildError: 'NC_000010.10' not in GRCh38
```

**Comment by davmlaw** [comment]
Not a bug but an annoying error that means nothing.

This is due to always searching g.HGVS in each build.

We could tell what genome build its in by the contig, and it'll never be in the other ones

**Comment by davmlaw** [comment]
To test, search for eg "NC_000015.10:g.84657289G>T" - make sure no rollbar message appears, and search behaves as before
