### ISSUE TITLE
Enter variants - fails with lowercase chrom

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#277]
Eg enter: "x:152771417 C>G"

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2395/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2395/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/snpdb/views/views.py", line 431, in manual_variant_entry
    create_manual_variants(request.user, genome_build, variants_text)
  File "/mnt/variantgrid/annotation/manual_variant_entry.py", line 50, in create_manual_variants
    variants_list.extend(get_manual_variant_tuples(mve))
  File "/mnt/variantgrid/annotation/tasks/process_manual_variants_task.py", line 29, in get_manual_variant_tuples
    variant_tuples.append(Variant.get_tuple_from_string(mve.entry_text, mve.genome_build))
  File "/mnt/variantgrid/snpdb/models/models_variant.py", line 331, in get_tuple_from_string
    contig = genome_build.chrom_contig_mappings[chrom]
KeyError: 'x'
```

**Comment by davmlaw** [comment]
The following 2 used to fail (now works)

x:152771417 C>G
chrx:152771417 C>G

**Comment by sksmi** [comment]
Tested examples above. PASS.
