### ISSUE TITLE
Patient - AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#278]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2396/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2396/)

Phenotype is:

"Renal vein thrombosis, Renal cortical infarction"

Note: This works on my machine

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/patients/views.py", line 50, in view_patient
    return render(request, 'patients/view_patient.html', context)
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 401, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/mnt/variantgrid/uicore/templatetags/ui_tabs_builder.py", line 127, in render
    content: str = self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/library.py", line 214, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/mnt/variantgrid/patients/templatetags/phenotype_tags.py", line 17, in phenotype_entry
    patient_results = phenotype_description.get_results()
  File "/mnt/variantgrid/annotation/models/models_phenotype_match.py", line 43, in get_results
    results.extend(sentence.get_results())
  File "/mnt/variantgrid/annotation/models/models_phenotype_match.py", line 84, in get_results
    results.append(r.to_dict())
  File "/mnt/variantgrid/annotation/models/models_phenotype_match.py", line 126, in to_dict
    "name": self.record.name,
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by davmlaw** [comment]
Needed to run manual steps:

```
python3.8 manage.py match_patient_phenotypes --clear
```
