### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one ConditionTextMatch -- it returned 2!

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#281]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2388/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2388/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/opt/variantgrid/classification/views/classification_view.py", line 378, in post
    result = importer.insert(record_data)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/variantgrid/classification/views/classification_view.py", line 306, in insert
    raise e
  File "/opt/variantgrid/classification/views/classification_view.py", line 239, in insert
    record.publish_latest(share_level=share_level, user=user)
  File "/opt/variantgrid/classification/models/classification.py", line 1309, in publish_latest
    latest_edited.publish(share_level=share_level, user=user, vc=self)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/opt/variantgrid/classification/models/classification.py", line 2072, in publish
    classification_post_publish_signal.send(
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/variantgrid/classification/models/condition_text_matching.py", line 581, in published
    'ConditionTextMatch.sync_condition_text_classifi...hed, attempt_automatch=True, update_counts=True)'
  File "/opt/variantgrid/classification/models/condition_text_matching.py", line 349, in sync_condition_text_classification
    gene_level, new_gene_level = ConditionTextMatch.objects.get_or_create(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
MultipleObjectsReturned: get() returned more than one ConditionTextMatch -- it returned 2!
```

**Comment by TheMadBug** [comment]
This happened to CHW, presumably causing issues with the import.
Logically the get_or_create code needs to result in there only being 1 record.

This happened during the ensuring there was a record at the gene level (ConditionTextMatches), ConditionTextMatches are a bit complicated as they represent themselves at different levels.

Should also make it so any failure with ConditionTextMatching does not bubble in such a way to interfere with the rest of the import process.
