### ISSUE TITLE
AttributeError: 'OntologyTerm' object has no attribute 'description'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#283]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2397/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2397/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/vary.py", line 38, in inner_func
    response = func(*args, **kwargs)
  File "/mnt/variantgrid/snpdb/views/views.py", line 1251, in user_global_sample_gene_matrix
    return global_sample_gene_matrix(request)
  File "/mnt/variantgrid/snpdb/views/views.py", line 1290, in global_sample_gene_matrix
    'return sample_gene_matrix(request, variant_anno...rsion, samples_list, gene_list, gene_count_type,'
  File "/mnt/variantgrid/snpdb/views/views.py", line 1095, in sample_gene_matrix
    omim_text = " ".join(map(format_min, omim))
  File "/mnt/variantgrid/snpdb/views/views.py", line 1091, in format_min
    return f"<div title='{mim}'>{mim.description}</div>"
AttributeError: 'OntologyTerm' object has no attribute 'description'
```

**Comment by TheMadBug** [comment]
Feel free to make a @property description if you think this happens more than once.
Otherwise it's definition now (It was a mix of the two between HPO/OMIM/MONDO in their previous tables)

**Comment by davmlaw** [comment]
https://runx1db.runx1-fpd.org/snpdb/user_global_sample_gene_matrix works again
