### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'panel_app_panel'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#288]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2402/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2402/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/vary.py", line 38, in inner_func
    response = func(*args, **kwargs)
  File "/mnt/variantgrid/analysis/views/views.py", line 265, in node_view
    return view(request, pk=node_id, version_id=node_version, extra_filters=extra_filters)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/edit.py", line 190, in get
    return super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/edit.py", line 133, in get
    return self.render_to_response(self.get_context_data())
  File "/mnt/variantgrid/analysis/views/nodes/gene_list_node_view.py", line 57, in get_context_data
    context.update(self._get_panel_app_context())
  File "/mnt/variantgrid/analysis/views/nodes/gene_list_node_view.py", line 85, in _get_panel_app_context
    panel_app_panel = gln_pap.panel_app_panel_local_cache_gene_list.panel_app_panel
AttributeError: 'NoneType' object has no attribute 'panel_app_panel'
```

**Comment by davmlaw** [comment]
Not sure how this would have ever happened (maybe some race condition or celery job being killed?), but I handle it now

**Comment by a1618617** [comment]
Is this issue why we can't filter using the panelapp gene lists?

Eg. https://variantgrid.com/analysis/790/ > tried using the skeletal dysplasia panel from PanelApp Aus, but got nothing

**Comment by davmlaw** [comment]
What node? The bottom right one? I haven't touched it, but this one looks ok to me, see https://variantgrid.com/analysis/790/422294

**Comment by davmlaw** [comment]
The genes in there look like garbage - will have to check what panel app is sending us:


VARIANTS
UNKNOWN
UNIVERSITY

**Comment by a1618617** [comment]
![image](https://user-images.githubusercontent.com/16040469/111089110-4ed4b800-857a-11eb-8795-181755382625.png)

The node with 477 variants is using the inbuilt panelapp panels gene list, the node with 23 variants is my user supplied gene list.

**Comment by sksmi** [comment]
Related to SAP #77 - HPO & OMIM gene matching fail?

**Comment by davmlaw** [comment]
This is due to #294 - GeneListNode PanelApp filters don't work on systems without pathology tests enabled

**Comment by davmlaw** [comment]
@a1618617 should be fixed now - thanks for bug report

**Comment by a1618617** [comment]
@davmlaw thanks!

**Comment by sksmi** [comment]
PASS

http://frgeneseq02.imvs.sa.gov.au:90/analysis/5328/
https://variantgrid.com/analysis/2527/
