### ISSUE TITLE
InvalidHGVSName: Invalid HGVS cDNA allele "2014_2071inv"

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#292]
This is GRCh37 variant:

17:41244589 TGATGGGAAAAAGTGGTGGTATACGATATGGGTTTTGTAAAAGTCCATGTTTATTTGG>CCAAATAAACATGGACTTTTACAAAACCCATATCGTATACCACCACTTTTTCCCATCA

Dies on "external search terms" - only that should fail not take out whole page

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2414/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2414/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/variantopedia/views.py", line 253, in view_variant
    return variant_details(request, variant_id, template=template, extra_context=extra_context)
  File "/mnt/variantgrid/variantopedia/views.py", line 371, in variant_details
    'return variant_details_annotation_version(reque... template=template, extra_context=extra_context)'
  File "/mnt/variantgrid/variantopedia/views.py", line 491, in variant_details_annotation_version
    return render(request, template, context)
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 401, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 192, in render
    return template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/mnt/variantgrid/uicore/templatetags/ui_utils.py", line 204, in render
    output = self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 514, in render
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 514, in <dictcomp>
    values = {key: val.resolve(context) for key, val in self.extra_context.items()}
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/mnt/variantgrid/annotation/models/models.py", line 733, in get_search_terms
    return get_variant_search_terms(self.transcript_annotation)
  File "/mnt/variantgrid/annotation/external_search_terms.py", line 94, in get_variant_search_terms
    return _get_search_terms(variant_transcripts_list, formatter='"%s"')
  File "/mnt/variantgrid/annotation/external_search_terms.py", line 57, in _get_search_terms
    gene_symbol, terms = _get_gene_and_terms(vta, **kwargs)
  File "/mnt/variantgrid/annotation/external_search_terms.py", line 19, in _get_gene_and_terms
    hgvs_name = HGVSName(vta.hgvs_c)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 853, in parse_allele
    self.parse_cdna(details)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 906, in parse_cdna
    raise Inval

**Comment by davmlaw** [comment]
Fixed crash.

Will get inversions to work later in #293

**Comment by sksmi** [comment]
Create variant works.
