### ISSUE TITLE
FieldError: Cannot resolve keyword 'locus' into field. Choices are: af_1kg, af_uk10k, amino_acids, annotation_run, annotation_run_id, cadd_phred, cadd_raw, canonical, codons, consequence, cosmic_count, cosmic_id, cosmic_legacy_id, dbscsnv_ada_score, dbscs

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#302]
To recreate:

* Get annotation run with error (ie set error_exception = "blah" and save)
* View it, click reload
* Error occurs during deletion - should only have that contig Q go in for Variant objects, not all classes

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2429/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2429/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/variantgrid/annotation/tasks/annotate_variants.py", line 27, in delete_annotation_run
    annotation_run.delete()
  File "/data/variantgrid/annotation/models/models.py", line 453, in delete
    self.delete_related_objects()
  File "/data/variantgrid/annotation/models/models.py", line 449, in delete_related_objects
    qs = get_queryset_for_annotation_version(klass, annotation_version)
  File "/data/variantgrid/annotation/annotation_version_querysets.py", line 47, in get_queryset_for_annotation_version
    qs = qs.filter(Variant.get_contigs_q(annotation_version.genome_build))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1237, in build_filter
    return self._add_q(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
FieldError: Cannot resolve keyword 'locus' into field. Choices are: af_1kg, af_uk10k, amino_acids, annotation_run, annotation_run_id, cadd_phred, cadd_raw, canonical, codons, consequence, cosmic_count, cosmic_id, cosmic_legacy_id, dbscsnv_ada_score, dbscsnv_rf_score, dbsnp_rs_id, distance, domains, ensembl_protein, exon, fathmm_pred, fathmm_pred_most_damaging, flags, gene, gene_id, gene_text, gerp_pp_rs, gnomad2_liftover_af, gnomad_ac, gnomad_af, gnomad_afr_af, gnomad_amr_af, gnomad_an, gnomad_asj_af, gnomad_eas_af, gnomad_filtered, gnomad_fin_af, gnomad_hom_alt, gnomad_nfe_af, gnomad_oth_af, gnomad_popmax, gnomad_popmax_ac, gnomad_popmax_af, gnomad_popmax_an, gnomad_popmax_hom_alt, gnomad_sas_af, grantham, hgnc_id, hgvs_c, hgvs_p, id, impact, interpro_domain, intron, loftool, mastermind_count_1_cdna, mastermind_count_2_cdna_prot, mastermind_count_3_aa_change, mastermind_mmid3, maxentscan_alt, maxentscan_diff, maxentscan_percent_diff_ref, maxentscan_ref, mutation_assessor_pred, mutation_assessor_pred_most_damaging, mutation_taster_pred, mutation_taster_pred_most_damaging, overlapping_symbols, phastcons_100_way_vertebrate, phastcons_30_way_mammalian, phastcons_46_way_mammalian, phylop_100_way_vertebrate, phylop_30_way_mammalian, phylop_46_way_mammalian, polyphen2_hvar_pred, polyphen2_hvar_pred_most_damaging, predictions_num_benign, predictions_num_pathogenic, protein_position, pubmed, repeat_masker, revel_score, sift, somatic, splice_region, spliceai_gene_symbol, spliceai_pred_dp_ag, spliceai_pred_dp_al, spliceai_pred_dp_dg, spliceai_pred_dp_dl, spliceai_pred_ds_ag, spliceai_pred_ds_al, spliceai_pred_ds_dg, spliceai_pred_ds_dl, swissprot, symbol, symbol_source, topmed_af, transcript, transcript_id, transcript_version, transcript_version_id, trembl, uniparc, uniprot, uniprot_id, variant, variant_class, variant_id, vep_skipped_reason, version, version_id
```

**Comment by TheMadBug** [comment]
Note this was Rollbar auto-opening after it re-occured. (Almost a full year since it last happened)

**Comment by davmlaw** [comment]
This was resolved over the weekend

First time was in master, second time was in SA Path after I patched back 1st part of change (but not the change that fixed this issue)
