### ISSUE TITLE
ProgrammingError: syntax error at or near ","
LINE 5: ...s_zygosity, 1, 1), '.')) = 'O') THEN 1 ELSE 0 END,,coalesce(...
                                                             ^


### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#307]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2447/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2447/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/variantgrid/snpdb/tasks/cohort_genotype_tasks.py", line 179, in cohort_genotype_task
    run_sql(insert_sql)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/data/variantgrid/library/database_utils.py", line 9, in run_sql
    value = cursor.execute(sql, params)  # Remember it only accepts '%s' not %d etc.
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
ProgrammingError: syntax error at or near ","
LINE 5: ...s_zygosity, 1, 1), '.')) = 'O') THEN 1 ELSE 0 END,,coalesce(...
                                                             ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
SyntaxError: syntax error at or near ","
LINE 5: ...s_zygosity, 1, 1), '.')) = 'O') THEN 1 ELSE 0 END,,coalesce(...
                                                             ^

```

**Comment by davmlaw** [comment]
Bug due to my recent changes that allowed unknown variants for somatic VCFs

**Comment by sksmi** [comment]
Might need a few more details on how to test this one...

**Comment by davmlaw** [comment]
Create a cohort with samples from different VCFs, then click save

**Comment by sksmi** [comment]
That's a lot easier than what I was thinking!

FAIL. 

PASS: Create cohort from 3 samples from different vcfs. 

FAIL: Create trio analysis from cohort. 
Perform trio analysis button works, but has no effect: http://frgeneseq02.imvs.sa.gov.au:92/snpdb/view_cohort/1920

**Comment by davmlaw** [comment]
Ah, that's an issue with the button - it was inside a form so submitted the page - need to make it just work like a normal button and call the trio wizard

**Comment by sksmi** [comment]
PASS. (Env. VG test)
