### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#309]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2448/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2448/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/variantgrid/variantopedia/views.py", line 496, in variant_sample_information
    vsi = VariantSampleInformation(request.user, variant)
  File "/data/variantgrid/snpdb/variant_sample_information.py", line 33, in __init__
    for row in values_qs:
  File "/data/variantgrid/snpdb/variant_sample_information.py", line 126, in _cohort_genotype_to_sample_genotypes
    zygosity = samples_zygosity[i]
IndexError: string index out of range
```

**Comment by davmlaw** [comment]
Dies extracting data from CohortGenotypeCollection: 

```
i = cgc.get_array_index_for_sample_id(sample_id)
zygosity = samples_zygosity[i]
```

This should have been fixed with:

```
python3.8 manage.py fix_cohort_genotype_packed_field_index
```

Need to run a query to find out how many of these are wrong - then fix them. Code is in variantgrid_private
