### ISSUE TITLE
AttributeError: Got AttributeError when attempting to get a value for field `gene` on serializer `PathologyTestGeneModificationRequestSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `PathologyTestGene

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#334]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2609/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2609/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/variantgrid/pathtests/views_rest.py", line 31, in get
    return Response(serializer.data)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 562, in data
    ret = super().data
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 529, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 677, in to_representation
    return [
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 516, in to_representation
    attribute = field.get_attribute(instance)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/fields.py", line 487, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `gene` on serializer `PathologyTestGeneModificationRequestSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `PathologyTestGeneModificationRequest` instance.
Original exception text was: 'PathologyTestGeneModificationRequest' object has no attribute 'gene'.Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/fields.py", line 454, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/fields.py", line 94, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'PathologyTestGeneModificationRequest' object has no attribute 'gene'
```

**Comment by davmlaw** [comment]
Trying to import Pathology test into gene grid

**Comment by sksmi** [comment]
Confirmed that path test now loads, but can't get the exome coverage to display (20+ mins), will try on something other than the mammoth mendeliome - not sure if errored out due to deploy whilst loading.

![image.png](https://images.zenhubusercontent.com/5bc5465086f3a678d497c0be/e20a8f5b-eebc-41b7-9fb4-f47124005921)

**Comment by sksmi** [comment]
Yep, works fine on other path tests (active & inactive)

**Comment by sksmi** [comment]
Can't get mendeliome to completely load (always a bit hit & miss with the super large gene lists - issue for future dev). 
Closing as works fine with other tests.
