### ISSUE TITLE
Disable analysis templates for non-sample/trio/cohort etc

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#341]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2569/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2569/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/data/variantgrid/analysis/views/views_json.py", line 358, in analysis_template_variable
    class_name = AnalysisVariable.get_node_field_class_name(node, field)
  File "/data/variantgrid/analysis/models/models_analysis.py", line 302, in get_node_field_class_name
    raise ValueError(f"Don't know how to handle {node}.{field} (internal type: {internal_type})")
ValueError: Don't know how to handle test10-any db.percent (internal type: FloatField)
```

**Comment by sksmi** [comment]
**PASS**
