### ISSUE TITLE
SampleAnalysisTemplateRun not found

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#342]
Problem was this returned None:

```
analysis_template.analysistemplateversion_set.filter(active=True).first()
```

Must not have had an active version set?

-------------

AttributeError: 'NoneType' object has no attribute 'analysis_snapshot'

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2636/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2636/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/variantgrid/snpdb/views/views.py", line 314, in sample_variants_tab
    analysis = get_sample_analysis(sample, analysis_template)
  File "/data/variantgrid/analysis/analysis_templates.py", line 70, in get_sample_analysis
    at_run = run_analysis_template(analysis_template, sample.genome_build, sample=sample)
  File "/data/variantgrid/analysis/analysis_templates.py", line 15, in run_analysis_template
    template_run = AnalysisTemplateRun.create(analysis_template, genome_build, user=user)
  File "/data/variantgrid/analysis/models/models_analysis.py", line 418, in create
    analysis = template_version.analysis_snapshot.clone()
AttributeError: 'NoneType' object has no attribute 'analysis_snapshot'Traceback (most recent call last):
  File "/data/variantgrid/analysis/analysis_templates.py", line 65, in get_sample_analysis
    satr = SampleAnalysisTemplateRun.objects.get(sample=sample,
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
DoesNotExist: SampleAnalysisTemplateRun matching query does not exist.
```

**Comment by davmlaw** [comment]
Was because v1 was not set to active:

http://frgeneseq02.imvs.sa.gov.au:92/analysis/analysis_template/17/list/

I clicked "save" to make a v2 and that fixed the issue
