### ISSUE TITLE
AttributeError: 'PhenotypeNode' object has no attribute 'celery_task'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#360]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2742/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2742/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "/data/variantgrid/analysis/views/views.py", line 502, in node_cancel_load
    if node.celery_task:
AttributeError: 'PhenotypeNode' object has no attribute 'celery_task'
```

**Comment by davmlaw** [comment]
To recreate: click cancel node while loading, used to throw a rollbar error

**Comment by sksmi** [comment]
**PASS**

Cancelled during mendeliome gene list node loading. No rollbar error.
