### ISSUE TITLE
Deleting unused variants/loci

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#373]
We currently have no way to delete variants that are no longer used (in cohort genotype, tag, classification etc)

Probably best to add PROTECT to anything touching a variant first.

Then, you could make a task that finds unused variants, then deletes annotaiton, variants and loci. Eg to delete a locus that isn't used:

```
DELETE
FROM "snpdb_locus"
where id in (
	SELECT "snpdb_locus"."id" FROM "snpdb_locus" LEFT OUTER JOIN "snpdb_variant" ON ("snpdb_locus"."id" = "snpdb_variant"."locus_id") WHERE "snpdb_variant"."id" IS null limit 100000
)
```

We'll need this once we delete the gigantic VCF on variantgrid.com to reclaim lots of disk

**Comment by davmlaw** [comment]
Estimate of unused variant/locus data on vg.com now:

```
SELECT count(*) FROM "snpdb_locus" LEFT OUTER JOIN "snpdb_variant" ON ("snpdb_locus"."id" = "snpdb_variant"."locus_id") WHERE "snpdb_variant"."id" IS null;
 count 
-------
  2862
```

Not really worth clearing out loci

Total variants:
129,235,198

Not guaranteed to be exactly right but quick count of unused variants (het/hom/ref/unk) = 9,893,378 - so probably not worth worrying about really.

Number of reference variants is: 60,973,879

This is around 1/2 of all variants (though they're not annotated - only have 67,620,085 VariantAnnotation records)

We insert this but almost never link anything against it:

```
upload.tasks.vcf.unknown_variants_task.BulkUnknownVariantInserter.process_vcf_line

# Always insert a reference with every non-ref alt variant
for alt in {alt, Variant.REFERENCE_ALT}:
```

**Comment by davmlaw** [comment]
There are also some variants that have ref=alt (presumably from legacy?)

Also - can't see any info on reference variants, eg 1:169519049 T>= has clinvar - should be able to see that.

**Comment by davmlaw** [comment]
Ran on vg test, and it failed:

```
2021-06-22 14:08:03.867 UTC [1440] LOG:  server process (PID 15059) was terminated by signal 9: Killed
2021-06-22 14:08:03.867 UTC [1440] DETAIL:  Failed process was running: DELETE FROM "snpdb_variantcollectionrecord" WHERE "snpdb_variantcollectionrecord"."variant_id" IN (241615482, 241615484, 241615486, 241615488, 241615490, 241615491, 241615493, 241615495, 241615497, 241615500, 241615502, 241615504
```

Should probably also exclude variants with variantcollectionrecords in the delete....

But another question is why those were still there. We should also clean up the collection records that are no longer used - is this a venn beneath a sample node that was deleted?

**Comment by davmlaw** [comment]
Disabled auto vacuum on these tables in vg test, remember to re-enable again:

```
alter table snpdb_variant set (autovacuum_enabled = false);
alter table snpdb_variantzygositycount set (autovacuum_enabled = false);
```

**Comment by davmlaw** [comment]
This is likely to take >60 hours on vg test which is way smaller than VG prod... Django delete is taking way too long as it has model signals and handles the cascades etc etc.

There is a way to do deletes quickly - without signals / cascades etc, via:

```
qs._raw_delete(qs.db)
```

However we'd need to handle all the cascade deletion ourselves.

The only thing that should get deleted is:

* Variant
* VariantZygosityCount
* VariantAnnotation (only when alt is not "=")

**Comment by davmlaw** [comment]
Ran on weekend, got up to  29828427

Modified code on vg.com - haven't pushed yet. Also need to modify code to also delete unused loci

**Comment by davmlaw** [comment]
Died. Can probably just resume but recording what happened:

```
7.49% done - doing range lock 1646: AnnotationRangeLock: (v. v7. (17 July 2020) VEP: 100/Ensembl/GRCh37) 161338752 - 162078722
161338752 - 161375750 (36998)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: SSL SYSCALL error: EOF detected


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/dist-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/mnt/variantgrid/snpdb/management/commands/delete_unused_variants.py", line 69, in handle
    num_deleted = qs._raw_delete(qs.db)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 763, in _raw_delete
    cursor = query.get_compiler(using).execute_sql(CURSOR)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.OperationalError: SSL SYSCALL error: EOF detected
```

**Comment by davmlaw** [comment]
```
# on vg aws
python3 manage.py delete_unused_variants --min-variant=161338752
```
