### ISSUE TITLE
IntegrityError: insert or update on table "analysis_nodeversion" violates foreign key constraint "analysis_nodecache_node_id_398fdce2_fk_analysis_analysisnode_id"
DETAIL:  Key (node_id)=(45228) is not present in table "analysis_analysisnode".


### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#377]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2808/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2808/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/vary.py", line 38, in inner_func
    response = func(*args, **kwargs)
  File "/mnt/variantgrid/analysis/views/node_json_view.py", line 45, in get
    return self.json_response(request, *args, **kwargs)
  File "/mnt/variantgrid/analysis/views/node_json_view.py", line 17, in json_response
    data = self._get_data(request, *args, **kwargs)
  File "/mnt/variantgrid/analysis/views/views_grid.py", line 26, in _get_data
    grid = _variant_grid_from_request(request)
  File "/mnt/variantgrid/analysis/views/views_grid.py", line 102, in _variant_grid_from_request
    return grids.VariantGrid(request.user, node, extra_filters, **kwargs)
  File "/mnt/variantgrid/analysis/grids.py", line 89, in __init__
    node_count = NodeCount.load_for_node(self.node, extra_filters)
  File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 970, in load_for_node
    return NodeCount.load_for_node_version(NodeVersion.get(node), label=label)
  File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 916, in get
    return NodeVersion.objects.get_or_create(node=node, version=node.version)[0]
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 576, in get_or_create
    return self._create_object_from_params(kwargs, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 610, in _create_object_from_params
    obj = self.create(**params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/transaction.py", line 232, in __exit__
    connection.commit()
  File "/usr/local/lib/python3.8/dist-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 266, in commit
    self._commit()
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
IntegrityError: insert or update on table "analysis_nodeversion" violates foreign key constraint "analysis_nodecache_node_id_398fdce2_fk_analysis_analysisnode_id"
DETAIL:  Key (node_id)=(45228) is not present in table "analysis_analysisnode".
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/base/base.py", line 242, in _commit
    return self.connection.commit()
ForeignKeyViolation: insert or update on table "analysis_nodeversion" violates foreign key constraint "analysis_nodecache_node_id_398fdce2_fk_analysis_analysisnode_id"
DETAIL:  Key (node_id)=(45228) is not present in table "analysis_analysisnode".
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
DoesNotExist: NodeVersion matching query does not exist.
```

**Comment by davmlaw** [comment]
This happens when the NodeVersion is deleted underneath you. We should detect this and throw a NodeOutOfDateException or whatever it's called

**Comment by davmlaw** [comment]
Can also happen when copying a node that is currently updating

**Comment by davmlaw** [comment]
When I added NodeVersion it might not have always been made so I did a get_or_create from wherever I needed it.

Now just make it always in AnalysisNode.save(), so don't need to do the get_or_create, which led to that error due to race conditions.

If it happens now during cloning, it'll work but we'll just not have a cache from the original

**Comment by sksmi** [comment]
Hasn't occurred today with lots of node changing. Will leave open for a while to see if it's gone.

**Comment by sksmi** [comment]
**PASS**

Happening a lot in vg.com (not updated). Not seen in :92 for >10days.  Closing.

**Comment by sksmi** [comment]
Reopening - occurred on tha's analysis:  :92/analysis/9805/

**Comment by sksmi** [comment]
[rollbar 2919 IntegrityError: insert or update on table "analysis_nodeversion" violates foreign key constraint "analysis_nodecache_node_id_398fdce2_fk_analysis_analysisnode_id" DETAIL: Key (node_id)=(98354) is not present in table "analysis_analysisnode".](https://rollbar.com/jimmy.andrews/VariantGrid/items/2919/?item_page=0&#traceback)

**Comment by sksmi** [comment]
@davmlaw can you take a look at this one?

**Comment by davmlaw** [comment]
Same issue of node being deleted while loading, there were 3 instances that we didn't get:

```
thread_safe_unique_together_get_or_create(NodeVersion
```

* gene_counts
* analysis_node line 382 (node_version)
* analysis_node line 1005 (get_counts_for_node)

**Comment by davmlaw** [comment]
Commit - need to decide to hotfix?

https://github.com/SACGF/variantgrid/commit/77c8f69d2bd9e8d03e4abecc7e9cfdd237aaf9ce

Fixed the most common issue (node deleted while loading) which would crash JS and thus give an analysis error message box. Now deleting node at this point will just do nothing (as node is deleted)

It's still possible to crash out a node via deleting it while the columns summary grid is loading (never happened before - and this will be a real pain to handle)  but at least now that will say that the node was deleted while loading so the error message is better

**Comment by davmlaw** [comment]
This is really difficult to test as it requires race conditions - will just have to monitor rollbar

**Comment by davmlaw** [comment]
Last occured 65 days ago
