### ISSUE TITLE
ContigNotInBuildError: 'NC_000001.11' not in GRCh37

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#390]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2860/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2860/)

```
Traceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 357, in search_within
    build_results = get_results_func(self.search_string,
  File "/data/variantgrid/variantopedia/search.py", line 500, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/data/variantgrid/genes/hgvs.py", line 390, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1405, in parse_hgvs_name
    chrom, start, _, ref, alt = get_vcf_allele(hgvs, genome, transcript)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 673, in get_vcf_allele
    ref = get_genomic_sequence(genome, chrom, start, end)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 518, in get_genomic_sequence
    return str(genome[str(chrom)][start - 1:end]).upper()
  File "/data/variantgrid/library/genomics/fasta_wrapper.py", line 36, in __getitem__
    contig = self.convert_chrom_func(contig)
  File "/data/variantgrid/snpdb/models/models_genome.py", line 306, in convert_chrom_to_fasta_sequence
    raise Contig.ContigNotInBuildError(f"'{chrom}' not in {self.genome_build}")
ContigNotInBuildError: 'NC_000001.11' not in GRCh37Traceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 490, in search_hgvs
    if fixed_hgvs := HGVSMatcher.fix_swapped_gene_transcript(hgvs_string):
  File "/data/variantgrid/genes/hgvs.py", line 533, in fix_swapped_gene_transcript
    hgvs = HGVSName(hgvs_name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 857, in parse_allele
    self.parse_genome(details)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 997, in parse_genome
    raise InvalidHGVSName(details, 'genomic allele')
InvalidHGVSName: Invalid HGVS genomic allele "11792368 CTCT>CT"
```

**Comment by davmlaw** [comment]
This shouldn't be an error as we shouldn't have searched in that build for that contig

**Comment by davmlaw** [comment]
Ah, this only happened when the HGVS was wrong and needed to be cleaned - ie "NC_000001.11:g.10475002 G>T" (shouldn't have been a space there)

Needed to handle the contig not in build for clean up case

**Comment by sksmi** [comment]
**PASS**

Tested using example above: NC_000001.11:g.10475002 G>T
no error generated.
