### ISSUE TITLE
Single variant lookup - huge indel causes - ClinGenAlleleAPIException: Representation has size 31033 which exceeds ClinGen max of 10000

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#391]
```
In [10]: v = Variant.objects.get(pk=29715607)                                                                           

In [11]: len(v.alt.seq)                                                                                                 
Out[11]: 30999
```

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2864/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2864/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/variantgrid/snpdb/views/views_rest.py", line 52, in get
    variant_allele = get_variant_allele_for_variant(genome_build, variant)
  File "/data/variantgrid/snpdb/clingen_allele.py", line 211, in get_variant_allele_for_variant
    va = variant_allele_clingen(genome_build, variant)
  File "/data/variantgrid/snpdb/clingen_allele.py", line 229, in variant_allele_clingen
    raise ClinGenAlleleAPIException(msg)
ClinGenAlleleAPIException: Representation has size 31033 which exceeds ClinGen max of 10000Traceback (most recent call last):
  File "/data/variantgrid/snpdb/clingen_allele.py", line 205, in get_variant_allele_for_variant
    va = VariantAllele.objects.get(variant=variant, genome_build=genome_build)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
DoesNotExist: VariantAllele matching query does not exist.
```

**Comment by EmmaTudini** [comment]
@davmlaw Would it be possible for you could expand on these issues a bit (e.g. what the change was). Makes testing quite difficult when I dont know what is meant to change. 

Here's my best guess...
Testing:
- Logged in to Shariant test as admin (emma.Tudini@qimrberghofer.edu.au)
- Imported NM_001256850.1(TTN):c.1_12000del (over 10k bases)
Expected output: Clingen would fail but would still lift over with NCBI remap?
Actual output: Passed

**Comment by davmlaw** [comment]
Hi, yeah sorry that was a bit slack - what used to happen is it completely crashed out.

Now, it:

* Doesn't die, accepts it can't get clingen allele ID
* Stores error message: Variation given on the input is too long. There is 10000 bp limit for variation's length
* Goes through other liftover pipelines etc

**Comment by TheMadBug** [comment]
Cool, we can confirm that was indeed the behaviour of that allele.
