### ISSUE TITLE
SSLError: HTTPSConnectionPool(host='rest.ensembl.org', port=443): Max retries exceeded with url: /lookup/id/ENST00000352632 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#412]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2948/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2948/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/variantgrid/snpdb/tasks/validation_task.py", line 15, in validate_variant_data
    allele.validate()
  File "/data/variantgrid/snpdb/models/models_variant.py", line 201, in validate
    allele_validate_signal.send(sender=Allele, allele=self)
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 177, in send
    return [
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/data/variantgrid/classification/models/classification_allele_hooks.py", line 39, in compare_chgvs
    chgvs38 = matcher38.variant_to_c_hgvs(v38, transcript)
  File "/data/variantgrid/genes/hgvs.py", line 505, in variant_to_c_hgvs
    if extra := self.variant_to_c_hgvs_extra(variant=variant, transcript_name=transcript_name):
  File "/data/variantgrid/genes/hgvs.py", line 500, in variant_to_c_hgvs_extra
    return self.variant_to_hgvs_extra(variant, transcript_name)
  File "/data/variantgrid/genes/hgvs.py", line 470, in variant_to_hgvs_extra
    transcript = self.get_pyhgvs_transcript(transcript_name)
  File "/data/variantgrid/genes/hgvs.py", line 384, in get_pyhgvs_transcript
    return TranscriptVersion.get_refgene(self.genome_build, transcript_name,
  File "/data/variantgrid/genes/models.py", line 703, in get_refgene
    TranscriptVersion.raise_bad_or_missing_transcript(genome_build, transcript_id, version)
  File "/data/variantgrid/genes/models.py", line 665, in raise_bad_or_missing_transcript
    annotation_consortium, exists = transcript_exists(genome_build, identifier, version)
  File "/data/variantgrid/genes/annotation_consortium_api.py", line 12, in transcript_exists
    return AnnotationConsortium.ENSEMBL.label, ensembl_transcript_exists(genome_build, identifier, version)
  File "/data/variantgrid/genes/annotation_consortium_api.py", line 23, in ensembl_transcript_exists
    r = requests.get(url, headers={"Content-Type": "application/json"})
  File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
SSLError: HTTPSConnectionPool(host='rest.ensembl.org', port=443): Max retries exceeded with url: /lookup/id/ENST00000352632 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
MaxRetryError: HTTPSConnectionPool(host='rest.ensembl.org', port=443): Max retries exceeded with url: /lookup/id/ENST00000352632 (Caused by SSLError(SSLError("bad handshake: SysCallError(-1, 'Unexpected EOF')")))Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 491, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
SSLError: ("bad handshake: SysCallError(-1, 'Unexpected EOF')",)Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 485, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1934, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1664, in _raise_ssl_error
    raise SysCallError(-1, "Unexpected EOF")
SysCallError: (-1, 'Unexpected EOF')
```

**Comment by davmlaw** [comment]
Q) If all of your API friends crashed, would you crash too?
A) Yes

**Comment by davmlaw** [comment]
🤖 Written by Claude

Resolved by the transcript-exists rewrite; no further fix needed.

The crash path in this trace (`validate_variant_data` → `Allele.validate()` → `compare_chgvs` → `ensembl_transcript_exists`, a bare `requests.get` with no timeout or error handling) no longer exists. Its replacement, `TranscriptVersion.raise_bad_or_missing_transcript` (`genes/models/models_gene.py`), catches `RequestException` / `URLError`, caches a 1-hour connection-error marker and raises `NoTranscript("... validity unknown")` instead of propagating the network error. Callers in `hgvs_matcher.py` treat `NoTranscript` as "carry on", so an Ensembl/NCBI outage no longer aborts HGVS matching. The Ensembl fetch also has a 60s timeout and Entrez a 30s one.
