### ISSUE TITLE
Can't delete analysis templates from grid

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#415]
This has already been fixed, but thought I'd better document this bug

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2952/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2952/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/variantgrid/library/django_utils/jqgrid_view.py", line 91, in post
    grid_obj.delete_row(pk)
  File "/data/variantgrid/analysis/grids.py", line 397, in delete_row
    analysis_template = AnalysisTemplate.get_for_user(self.user, pk)
  File "/data/variantgrid/library/django_utils/guardian_permissions_mixin.py", line 78, in get_for_user
    obj = get_object_or_404(cls, pk=pk)
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 418, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got 'jqg1'.Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'jqg1'
```

**Comment by sksmi** [comment]
me attempting to delete an analysis template 90/analysis/9548/ if we need to test it's fixed.

**Comment by davmlaw** [comment]
@sksmi - fixed this already - very simple change:

https://github.com/SACGF/variantgrid/commit/921fb4e0adb5b7db30994f29c6096f2b1ee09d6e

Please add to VG3 Hotfix 1 if you want to make it into SAP

**Comment by sksmi** [comment]
**PASS**

Tested using 90/analysis/9548/  - template deleted without error.
