### ISSUE TITLE
AnalysisNode.save() in celery task - causes version issues / EmptyResultSet

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#431]
If you make nodes change really rapidly, ie:

* add/remove lots of tags very quickly
* add/disconnect nodes really quickly

You can launch multiple node update tasks, these called AnalysisNode.save() which could overwrite details of the node, eg the counts / version / color etc.

----

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2960/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2960/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/vary.py", line 38, in inner_func
    response = func(*args, **kwargs)
  File "/data/variantgrid/analysis/views/node_json_view.py", line 57, in get
    return self.get_response(request, *args, **kwargs)
  File "/data/variantgrid/analysis/views/node_json_view.py", line 29, in get_response
    data = self._get_data(request, *args, node=node, **kwargs)
  File "/data/variantgrid/analysis/views/views_grid.py", line 47, in _get_data
    return grid.get_data(request)
  File "/data/variantgrid/library/jqgrid.py", line 346, in get_data
    paginator, page, items = self.get_items(request)
  File "/data/variantgrid/library/jqgrid_sql.py", line 63, in get_items
    return self.get_items_from_queryset(request)
  File "/data/variantgrid/library/jqgrid_sql.py", line 66, in get_items_from_queryset
    sql, params, column_names, is_sorted = self.get_sql_params_and_columns(request)
  File "/data/variantgrid/analysis/grids.py", line 163, in get_sql_params_and_columns
    sql, column_names = self._get_zygosity_sql_and_columns(values_queryset, order_by)
  File "/data/variantgrid/analysis/grids.py", line 170, in _get_zygosity_sql_and_columns
    ret = get_columns_and_sql_parts_for_cohorts(values_queryset, cohorts)
  File "/data/variantgrid/snpdb/grid_columns/grid_sample_columns.py", line 63, in get_columns_and_sql_parts_for_cohorts
    'return _get_columns_and_sql_parts_for_pack_list...lues_queryset, new_column_pack_lists, new_joins)'
  File "/data/variantgrid/snpdb/grid_columns/grid_sample_columns.py", line 67, in _get_columns_and_sql_parts_for_pack_lists_and_joins
    select_part, from_part, where_part = get_queryset_select_from_where_parts(values_queryset)
  File "/data/variantgrid/library/database_utils.py", line 48, in get_queryset_select_from_where_parts
    sql_str = queryset_to_sql(qs)
  File "/data/variantgrid/library/database_utils.py", line 22, in queryset_to_sql
    query, params = queryset.query.sql_with_params()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 264, in sql_with_params
    return self.get_compiler(DEFAULT_DB_ALIAS).as_sql()
  File "/data/variantgrid/library/django_utils/django_queryset_sql_transformer.py", line 16, in as_sql
    sql, params = super().as_sql(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 513, in as_sql
    where, w_params = self.compile(self.where) if self.where is not None else ("", [])
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 430, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/where.py", line 99, in as_sql
    raise EmptyResultSet
EmptyResultSet
```

**Comment by davmlaw** [comment]
```
from analysis.models import AnalysisNode
node = AnalysisNode.objects.get_subclass(pk=98017)
```

**Tags**

```
for x in node.analysis.varianttag_set.all().values_list("created", "tag"):
    print(x)
```

```
(datetime.datetime(2021, 6, 18, 4, 7, 27, 183972, tzinfo=<UTC>), 'SomaticReportable')
(datetime.datetime(2021, 6, 18, 4, 9, 10, 73467, tzinfo=<UTC>), 'SomaticReportable')
(datetime.datetime(2021, 6, 18, 4, 9, 58, 659010, tzinfo=<UTC>), 'RequiresClassification')
(datetime.datetime(2021, 6, 18, 4, 10, 16, 815695, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 18, 4, 11, 34, 74933, tzinfo=<UTC>), 'SomaticReportable')
(datetime.datetime(2021, 6, 18, 4, 11, 41, 167290, tzinfo=<UTC>), 'RequiresClassification')
(datetime.datetime(2021, 6, 18, 4, 14, 17, 362513, tzinfo=<UTC>), 'SomaticReportable')
(datetime.datetime(2021, 6, 18, 5, 53, 6, 142604, tzinfo=<UTC>), 'NOTSomaticReportable')
(datetime.datetime(2021, 6, 18, 5, 58, 27, 173322, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 18, 6, 5, 43, 652316, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 18, 6, 6, 29, 270776, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 18, 6, 10, 23, 196268, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 18, 6, 10, 56, 846854, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 18, 6, 13, 54, 705577, tzinfo=<UTC>), 'NOTSomaticReportable')
(datetime.datetime(2021, 6, 18, 6, 15, 27, 175003, tzinfo=<UTC>), 'NOTSomaticReportable')
(datetime.datetime(2021, 6, 18, 6, 16, 17, 527683, tzinfo=<UTC>), 'NOTSomaticReportable')
(datetime.datetime(2021, 6, 18, 6, 17, 6, 706376, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 18, 6, 17, 31, 938402, tzinfo=<UTC>), 'NOTSomaticReportable')
(datetime.datetime(2021, 6, 21, 4, 32, 48, 602377, tzinfo=<UTC>), 'SomaticReportable')
(datetime.datetime(2021, 6, 21, 4, 32, 53, 963918, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 21, 4, 33, 29, 331885, tzinfo=<UTC>), 'SomaticReportable')
(datetime.datetime(2021, 6, 21, 4, 33, 57, 376583, tzinfo=<UTC>), 'NOTSomaticReportable')
(datetime.datetime(2021, 6, 21, 4, 34, 25, 449212, tzinfo=<UTC>), 'SomaticReportable')
(datetime.datetime(2021, 6, 21, 4, 34, 50, 682503, tzinfo=<UTC>), 'SomaticReportable')
(datetime.datetime(2021, 6, 21, 4, 37, 46, 349123, tzinfo=<UTC>), 'NOTSomaticReportable')
(datetime.datetime(2021, 6, 21, 4, 39, 47, 280127, tzinfo=<UTC>), 'NOTSomaticReportable')
(datetime.datetime(2021, 6, 21, 4, 41, 47, 387199, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 21, 4, 42, 7, 757182, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 21, 4, 42, 52, 980610, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 21, 4, 43, 19, 513045, tzinfo=<UTC>), 'Artefact')
(datetime.datetime(2021, 6, 21, 4, 43, 38, 296503, tzinfo=<UTC>), 'Artefact')
```

**Node Tasks**

```
for x in node.nodetask_set.all().order_by("version").values_list("version", "created", "celery_task"):
    print(x)
```

```
(5, datetime.datetime(2021, 6, 17, 23, 19, 57, 101308, tzinfo=<UTC>), '36d1a78b-3626-41f1-a6e5-f124fba16caa')
(6, datetime.datetime(2021, 6, 17, 23, 54, 7, 927477, tzinfo=<UTC>), '16879298-badb-4de9-900e-850e0f02c66f')
(7, datetime.datetime(2021, 6, 18, 0, 2, 56, 748676, tzinfo=<UTC>), 'ad020054-ee26-4f5c-9029-9cda635edf0b')
(8, datetime.datetime(2021, 6, 18, 0, 4, 1, 705023, tzinfo=<UTC>), '6107341c-3d64-408d-b166-d5d3a6d463e5')
(9, datetime.datetime(2021, 6, 18, 0, 4, 10, 604374, tzinfo=<UTC>), '925cd9fa-e52f-444e-9782-62bf30a07cdc')
(10, datetime.datetime(2021, 6, 18, 0, 4, 19, 48607, tzinfo=<UTC>), 'ff78c743-5bea-45f2-83e4-4bb3b704452b')
(11, datetime.datetime(2021, 6, 18, 0, 4, 48, 513186, tzinfo=<UTC>), 'b164dbca-f6ea-470e-881a-dcdf81235beb')
(12, datetime.datetime(2021, 6, 18, 0, 4, 54, 960619, tzinfo=<UTC>), 'a7334665-572c-41fa-aa41-b81fe80fc5c3')
(13, datetime.datetime(2021, 6, 18, 0, 5, 41, 131505, tzinfo=<UTC>), '6eb94e12-0aed-4aa0-a119-f5c508d36033')
(14, datetime.datetime(2021, 6, 18, 0, 5, 47, 751699, tzinfo=<UTC>), '8c2ea14f-f88c-4680-8b7f-8f033e3ca0d0')
(15, datetime.datetime(2021, 6, 18, 0, 18, 3, 9721, tzinfo=<UTC>), '2712915f-ecde-474c-a9a5-9b98cc7c6e44')
(16, datetime.datetime(2021, 6, 18, 1, 24, 32, 874654, tzinfo=<UTC>), '77558150-ed13-47af-93f3-33d5281c0ec0')
(17, datetime.datetime(2021, 6, 18, 1, 24, 33, 946708, tzinfo=<UTC>), 'cb1761ee-3191-4f30-bdd2-9a83b7784469')
(18, datetime.datetime(2021, 6, 18, 1, 24, 45, 974658, tzinfo=<UTC>), '7fe96417-224b-4166-94f5-ee215632812c')
(19, datetime.datetime(2021, 6, 18, 1, 24, 49, 410352, tzinfo=<UTC>), 'c528cfe7-f8bc-42fb-8936-c33bed14bd96')
(20, datetime.datetime(2021, 6, 18, 2, 38, 21, 30662, tzinfo=<UTC>), '35f0c23d-ba55-4ec3-9805-5fb94d17b55d')
(21, datetime.datetime(2021, 6, 18, 5, 52, 55, 822805, tzinfo=<UTC>), '4e68dc19-a499-4d5c-a18b-460743d7617f')
(22, datetime.datetime(2021, 6, 18, 6, 10, 25, 315416, tzinfo=<UTC>), 'df80054c-698f-4b45-b82a-c3bd3f59f265')
(23, datetime.datetime(2021, 6, 18, 6, 10, 55, 335980, tzinfo=<UTC>), '4c9a49e3-3fb1-484c-ab5e-f1be98b490a5')
(24, datetime.datetime(2021, 6, 23, 4, 29, 5, 475847, tzinfo=<UTC>), '3d76b3cc-d9b2-4012-a8fe-3abb88afdf08')
(25, datetime.datetime(2021, 6, 23, 4, 29, 7, 86605, tzinfo=<UTC>), '527cd1b9-d97b-4335-b2cb-5e9db16bd64e')
(26, datetime.datetime(2021, 6, 23, 4, 29, 8, 712029, tzinfo=<UTC>), '017da653-e7f7-4796-9bf9-9749797c33e6')
```

**Last 3 are all in 3 seconds.**

**TODO**

Pretty sure the problem is due ot deleting "review" tags - so perhaps try and see if you can spot this in NGINX logs, ie:

```
POST /analysis/analysis/set_variant_tag/A/
```

The other thing to look for is celery task ```variant_tag_delete``` and ```create_and_launch_analysis_tasks``` to see what got done

**Comment by davmlaw** [comment]
I thought it was a race condition where a node_update_task for an older node/version overwrote count, but the wrong count of 2 was also written to NodeCounts (which is stored against NodeVersion)

```
from analysis.models import AnalysisNode
node = AnalysisNode.objects.get_subclass(pk=98017)
nv = node.nodeversion_set.get()
for x in nv.nodecount_set.all().values("node_version__node", "node_version__version", "label", "count"):
    print(x)
```

```
{'node_version__node': 98017, 'node_version__version': 26, 'label': 'I', 'count': 0}
{'node_version__node': 98017, 'node_version__version': 26, 'label': 'T', 'count': 2}
{'node_version__node': 98017, 'node_version__version': 26, 'label': 'C', 'count': 0}
{'node_version__node': 98017, 'node_version__version': 26, 'label': 'O', 'count': 2}
{'node_version__node': 98017, 'node_version__version': 26, 'label': 'M', 'count': 0}
{'node_version__node': 98017, 'node_version__version': 26, 'label': 'G', 'count': 0}
{'node_version__node': 98017, 'node_version__version': 26, 'label': 'P', 'count': 0}
```

----------------

Still, ```node.save()``` is dangerous in celery tasks, because an old version may be saved on top of a newer one.

------------------

Also, the 1st access of the grid was ~5 days after the node was saved - so the Q cache would have def expired.

**Comment by davmlaw** [comment]
There are 2 copies of 25/26 here:

```
/var/log/variantgrid/scheduling_single_worker-1.log:[2021-06-23 13:59:07,084: INFO/ForkPoolWorker-1] NodeTask: af5f6e1c-680d-43c6-8a1e-da386e7f3d40 - 98017/25
/var/log/variantgrid/scheduling_single_worker-1.log:[2021-06-23 13:59:07,095: INFO/ForkPoolWorker-1] Got lock for: {98017: 25}
/var/log/variantgrid/scheduling_single_worker-1.log:[2021-06-23 13:59:08,708: INFO/ForkPoolWorker-1] NodeTask: 2f5f4c57-6b20-480a-bb62-f47a14d43ce6 - 98017/26
/var/log/variantgrid/scheduling_single_worker-1.log:[2021-06-23 13:59:08,726: INFO/ForkPoolWorker-1] Got lock for: {98017: 26}
/var/log/variantgrid/scheduling_single_worker-1.log:[2021-06-23 13:59:10,599: INFO/ForkPoolWorker-1] NodeTask: 393e78cd-ea91-4904-b66a-c4df9d3cdee7 - 98017/25
/var/log/variantgrid/scheduling_single_worker-1.log:[2021-06-23 13:59:12,343: INFO/ForkPoolWorker-1] NodeTask: 435fac63-33c1-4dc8-ad8c-77bb6f2b4170 - 98017/26
```

**Comment by davmlaw** [comment]
Most important thing to do is separate out what's currently in AnalysisNode.save() into what is safe to call in celery tasks

Make a util method that you can pass kwargs to and it handles the update based on version

Then maybe some other backup measures:

* Node Q cache should use PK of NodeVersion object instead of f"{node}_{version}" as there is no chance of re-using it
* Node Q cache should also incorporate cohort genotype PK as that will fix the query changes after VCF reloaded issue. Maybe reduce to 4 hours, and delete the cache upon NodeVersion object delete

**Comment by davmlaw** [comment]
Caused at least 1 prod error, so HF to SAP

https://github.com/SACGF/variantgrid/commit/9c431f04a2e11621396642615e04587a8c7ac50d

**Comment by davmlaw** [comment]
** HF Testing SAP Test :90 **

* Added 13 tags. Analysis tag node reloaded and counts matched all the way up
* Clicked so all 13 tags had delete symbol on them
* Rapidly clicked on all to delete as rapidly as possible.
* The tag node went down in count, eventually ended on zero

Tailing logs while I did this, we recreated race conditon and exited appropriately:

```
[2021-07-09 18:01:25,013: WARNING/ForkPoolWorker-8] Node 93160/26 out of date - exiting Celery task
```

**Comment by davmlaw** [comment]
I've had sample nodes not change name when changing samples, this this was broken in this change.

Need to pull that out of save() method so I can call with update

**Comment by davmlaw** [comment]
Have been unable to re-create the sample name doesn't issue. Will keep an eye out for it.

**Comment by davmlaw** [comment]
Last seen 27 days ago
