### ISSUE TITLE
NotImplementedError: unknown kind:  NM_002168.3:c.419G>A

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#452]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3101/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3101/)

```
Traceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 359, in search_within
    build_results = get_results_func(self.search_string,
  File "/data/variantgrid/variantopedia/search.py", line 511, in search_hgvs
    raise original_error  # cleaning didn't work don't tell anyone
  File "/data/variantgrid/variantopedia/search.py", line 492, in search_hgvs
    if fixed_hgvs := HGVSMatcher.fix_swapped_gene_transcript(hgvs_string):
  File "/data/variantgrid/genes/hgvs.py", line 535, in fix_swapped_gene_transcript
    hgvs = HGVSName(hgvs_name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 859, in parse_allele
    raise NotImplementedError("unknown kind: %s" % allele)
NotImplementedError: unknown kind:  NM_002168.3:c.419G>ATraceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 500, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/data/variantgrid/genes/hgvs.py", line 392, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1382, in parse_hgvs_name
    hgvs = HGVSName(hgvs_name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 859, in parse_allele
    raise NotImplementedError("unknown kind: %s" % allele)
NotImplementedError: unknown kind: NM_002168.3:c.419G>A
```

**Comment by davmlaw** [comment]
Easy to be able to handle this "GENESYMBOL HGVS"

**Comment by GracePendlebury** [comment]
Has this been completed as part of #830 ?

**Comment by davmlaw** [comment]
No, I can still recreate this on latest code

IDH2: NM_002168.3:c.419G>A

Gives:

```
Cleaned IDH2: NM_002168.3:c.419G>A to IDH2:NM_002168.3:c.419G>A

IDH2:NM_002168.3:c.419G>A: char 5: expected one of 'c', 'g', 'm', 'n', 'p', or 'r'
```

**Comment by davmlaw** [comment]
On latest code:

```
 Variant via HGVS Search
Cleaned hgvs from
IDH2: NM_002168.3:c.419G>A to
IDH2:NM_002168.3:c.419G>A

Variant via HGVS Search
Invalid HGVS cDNA allele IDH2:NM_002168.3:c.419G>A
```
