### ISSUE TITLE
DoesNotExist: PanelAppPanel matching query does not exist.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#453]
Steps to recreate:

* Go to gene grid
* Add a panel app panel - this works but it modifies the URL badly
* Reload the page, it'll die with the new URL

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2595/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2595/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/variantgrid/genes/views_rest.py", line 50, in get
    data = get_panel_app_panel_as_gene_list_json(panel_app_id)
  File "/data/variantgrid/genes/panel_app.py", line 44, in get_panel_app_panel_as_gene_list_json
    panel_app_panel = PanelAppPanel.objects.get(pk=panel_app_panel_id)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
DoesNotExist: PanelAppPanel matching query does not exist.
```

**Comment by davmlaw** [comment]
What's with the negative numbers?

Not sure if this is the same issue as #405 - handle PanelApp being deleted, but it's happened a lot.

**Comment by davmlaw** [comment]
Pretty easy fix, just need to remove the final dash (which is added a second time somewhere else):

```
genes/panel_app.PANEL_APP_PREFIX = "panel-app-"
```

Might as well patch SAP as it's annoying and easy
