### ISSUE TITLE
ClinGenAllele Registry - DataError: integer out of range

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#455]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3104/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3104/)

```
Traceback (most recent call last):
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/scratch/variantgrid/variantgrid/annotation/views_rest.py", line 65, in get
    clingen_allele = get_clingen_allele_for_variant(variant)
  File "/scratch/variantgrid/variantgrid/annotation/clingen/clingen_allele.py", line 161, in get_clingen_allele_for_variant
    ClinGenAllele.objects.create(pk=clingen_allele_id, api_response=api_response)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django_extensions/db/models.py", line 24, in save
    super(TimeStampedModel, self).save(**kwargs)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1332, in execute_sql
    cursor.execute(sql, params)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
DataError: integer out of range
Traceback (most recent call last):
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
NumericValueOutOfRange: integer out of range
Traceback (most recent call last):
  File "/scratch/variantgrid/variantgrid/annotation/clingen/clingen_allele.py", line 153, in get_clingen_allele_for_variant
    vcga = VariantClinGenAllele.objects.get(variant=variant)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/scratch/variantgrid/venv/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
DoesNotExist: VariantClinGenAllele matching query does not exist.
```

**Comment by davmlaw** [comment]
Search for eg "CA2305102520" 

This is going to require a DB migration

**Comment by davmlaw** [comment]
@TheMadBug - yeah PK change to BigInteger was all it took. 

DONE:

* Upgrade vg-test
* VG test - do a quick smoke test to make sure head is in a safe state

TODO: 

* Patch SA Path VG3 prod
* Upgrade VG3 sapath environments
* Patch SA Path VG2, upgrade
* If vg test ok, Upgrade vg.com
* Patch RUNX1, by making a branch?

**Comment by davmlaw** [comment]
@TheMadBug - this is the code change if you can take a look:

https://github.com/SACGF/variantgrid/commit/b4d4ee0056b554d8d635332c71213ec74e8fe53a

**Comment by EmmaTudini** [comment]
Quick test
- Logged in to Shariant test as non-admin
- Imported NM_080629.2(COL11A1):c.1281+6T>A (previously failed in prod due to this issue)

Expected output: Should be lifted over

Actual output: Passed
