### ISSUE TITLE
PermissionDenied: You do not have permission to access UploadedFile pk=5622

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#458]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3189/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3189/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/variantgrid/upload/views/views.py", line 227, in view_upload_pipeline
    uploaded_file.check_can_view(request.user)
  File "/data/variantgrid/upload/models/models.py", line 64, in check_can_view
    raise PermissionDenied(msg)
PermissionDenied: You do not have permission to access UploadedFile pk=5622
```

**Comment by davmlaw** [comment]
Shouldn't display link if you aren't allowed to see it

**Comment by davmlaw** [comment]
Tested variangrid.com - link not visible for user without permission
