### ISSUE TITLE
ValueError: Timed out after 61 waiting for NodeCache 83818 (v4): Created

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#461]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/2614/](https://rollbar.com/jimmy.andrews/VariantGrid/items/2614/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/data/variantgrid/analysis/tasks/node_update_tasks.py", line 94, in wait_for_cache_task
    raise ValueError(f"Timed out after {num_checks} waiting for {node_cache}")
ValueError: Timed out after 61 waiting for NodeCache 205394 (v7): Created
```

**Comment by davmlaw** [comment]
Affected analyses are the "open analysis" SA Path templates and GOI - all lead into a merge node where the issue is.

To help recreate Lucas says:

"I perform the open analysis, I break the top node from the other ones, I put in the GOI node and add the custom gene list. But when I reattach the nodes, the filtering gets "stuck" and won't carry down to the subsequent nodes. (see attached image)."

**Comment by davmlaw** [comment]
Merge nodes no longer use cache so this is now obsolete
