### ISSUE TITLE
Support HGVS without bases - ie NM_004991.3:c.1174

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#464]
NM_004991.3:c.1174 - could just resolve to coordinates then look up what we have...

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3223/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3223/)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/variantopedia/search.py", line 378, in search_within
    build_results = get_results_func(self.search_string,
  File "/mnt/variantgrid/variantopedia/search.py", line 608, in search_hgvs
    raise original_error  # cleaning didn't work don't tell anyone
  File "/mnt/variantgrid/variantopedia/search.py", line 579, in search_hgvs
    if fixed_hgvs := HGVSMatcher.fix_swapped_gene_transcript(hgvs_string):
  File "/mnt/variantgrid/genes/hgvs.py", line 579, in fix_swapped_gene_transcript
    hgvs = HGVSName(hgvs_name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 853, in parse_allele
    self.parse_cdna(details)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 906, in parse_cdna
    raise InvalidHGVSName(details, 'cDNA allele')
InvalidHGVSName: Invalid HGVS cDNA allele "1174"Traceback (most recent call last):
  File "/mnt/variantgrid/variantopedia/search.py", line 594, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/mnt/variantgrid/genes/hgvs.py", line 411, in get_variant_tuple
    variant_tuple = pyhgvs.parse_hgvs_name(lookup_hgvs_name, self.genome_build.genome_fasta.fasta,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 1384, in parse_hgvs_name
    hgvs = HGVSName(hgvs_name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 758, in __init__
    self.parse(name)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 772, in parse
    self.parse_allele(allele)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 853, in parse_allele
    self.parse_cdna(details)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 906, in parse_cdna
    raise InvalidHGVSName(details, 'cDNA allele')
InvalidHGVSName: Invalid HGVS cDNA allele "1174"
```

**Comment by davmlaw** [comment]
Dupe of #437
