### ISSUE TITLE
IntegrityError: duplicate key value violates unique constraint "genes_transcriptversions_transcript_id_version_df49014e_uniq"
DETAIL:  Key (transcript_id, version)=(ENST00000333602, 14) already exists.


### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#488]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3324/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3324/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/variantgrid/snpdb/tasks/validation_task.py", line 12, in validate_alleles
    allele.validate()
  File "/opt/variantgrid/snpdb/models/models_variant.py", line 217, in validate
    allele_validate_signal.send(sender=Allele, allele=self)
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 180, in send
    return [
  File "/usr/local/lib/python3.8/dist-packages/django/dispatch/dispatcher.py", line 181, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/opt/variantgrid/classification/models/classification_allele_hooks.py", line 39, in compare_chgvs
    chgvs37 = matcher37.variant_to_c_hgvs(v37, transcript)
  File "/opt/variantgrid/genes/hgvs.py", line 789, in variant_to_c_hgvs
    if extra := self.variant_to_c_hgvs_extra(variant=variant, transcript_name=transcript_name):
  File "/opt/variantgrid/genes/hgvs.py", line 784, in variant_to_c_hgvs_extra
    return self._variant_to_hgvs_extra(variant, transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 675, in _variant_to_hgvs_extra
    hgvs_name, hgvs_method = self._variant_to_hgvs(variant, transcript_name)
  File "/opt/variantgrid/genes/hgvs.py", line 763, in _variant_to_hgvs
    raise TranscriptVersion.raise_bad_or_missing_transcript(transcript_name)
  File "/opt/variantgrid/genes/models.py", line 731, in raise_bad_or_missing_transcript
    TranscriptVersionSequenceInfo.get(transcript_accession)  # Throws BadTranscript
  File "/opt/variantgrid/genes/models.py", line 984, in get
    tvi = TranscriptVersionSequenceInfo._get_and_store_from_ensembl_api(transcript_accession)
  File "/opt/variantgrid/genes/models.py", line 1023, in _get_and_store_from_ensembl_api
    return TranscriptVersionSequenceInfo.objects.create(transcript=transcript,
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 453, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django_extensions/db/models.py", line 22, in save
    super().save(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 726, in save
    self.save_base(using=using, force_insert=force_insert,
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 763, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 868, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 906, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1270, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "genes_transcriptversions_transcript_id_version_df49014e_uniq"
DETAIL:  Key (transcript_id, version)=(ENST00000333602, 14) already exists.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
UniqueViolation: duplicate key value violates unique constraint "genes_transcriptversions_transcript_id_version_df49014e_uniq"
DETAIL:  Key (transcript_id, version)=(ENST00000333602, 14) already exists.

```

**Comment by EmmaTudini** [comment]
@davmlaw Not sure what I should be testing for here?

**Comment by TheMadBug** [comment]
The full re-matching every c.hgvs and re-running allele validation would have re-triggered this issue in test if it was still an issue. Think this one is okay to close. (A few of these from Roller come were first caused when Dave started doing a lot of re-matching at the start of the c.hgvs changes. Since then they have not come up again, and especially not for the last few changes where we've just been tweaking transcript choice).
