### ISSUE TITLE
KeyError: 'cds_start'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#524]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3490/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3490/)

Peer tried to classify a variant and it died with stack trace below.

Also - if you visit the page: https://variantgrid.com/variantopedia/view_variant/257955110 it doesn't show the transcripts properly.

This is fixed on my machine, and is probably due to the transcript annotation versions. Will update VG.com as soon as I have a working test environment again (have to migrate NECTAR to intersect)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 159, in get
    context = self.get_context_data(**kwargs)
  File "/mnt/variantgrid/classification/views/views.py", line 521, in get_context_data
    vts = VariantTranscriptSelections(variant, genome_build,
  File "/mnt/variantgrid/annotation/transcripts_annotation_selections.py", line 43, in __init__
    self._populate(variant, annotation_version, initial_transcript_id, initial_transcript_column)
  File "/mnt/variantgrid/annotation/transcripts_annotation_selections.py", line 147, in _populate
    t_data = get_transcript_data(vsta, representative_transcript)
  File "/mnt/variantgrid/annotation/transcripts_annotation_selections.py", line 111, in get_transcript_data
    data["protein_length"] = obj.transcript_version.protein_length
  File "/mnt/variantgrid/genes/models.py", line 726, in protein_length
    return self.num_codons - 1  # stop codon doesn't count
  File "/mnt/variantgrid/genes/models.py", line 722, in num_codons
    return self.coding_length // 3
  File "/mnt/variantgrid/genes/models.py", line 718, in coding_length
    return sum([b-a for a, b in self.cds])
  File "/usr/local/lib/python3.8/dist-packages/lazy/lazy.py", line 28, in __get__
    value = self.__func(inst)
  File "/mnt/variantgrid/genes/models.py", line 562, in cds
    cds_start = self.data["cds_start"]
KeyError: 'cds_start'
```

**Comment by davmlaw** [comment]
fixed, contacted research that it now works
