### ISSUE TITLE
DoesNotExist: VariantGridColumn matching query does not exist.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#532]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3509/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3509/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/analysis/views/views.py", line 661, in analysis_settings_details_tab
    valid = form.is_valid()
  File "/usr/local/lib/python3.8/dist-packages/django/forms/forms.py", line 177, in is_valid
    return self.is_bound and not self.errors
  File "/usr/local/lib/python3.8/dist-packages/django/forms/forms.py", line 172, in errors
    self.full_clean()
  File "/usr/local/lib/python3.8/dist-packages/django/forms/forms.py", line 374, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python3.8/dist-packages/django/forms/forms.py", line 395, in _clean_fields
    value = getattr(self, 'clean_%s' % name)()
  File "/mnt/variantgrid/analysis/forms/forms.py", line 166, in clean_custom_columns_collection
    node_items[fni.filter_node].add(fni.column.label)
  File "/mnt/variantgrid/analysis/models/nodes/filters/filter_node.py", line 117, in column
    return VariantGridColumn.objects.get(variant_column=self.field)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
DoesNotExist: VariantGridColumn matching query does not exist.
```

**Comment by davmlaw** [comment]
https://variantgrid.com/analysis/949/

```
variant_column = het_count
```

This analysis was created in 	2020-01-09, so possibly a legacy column badly migrated

**Comment by davmlaw** [comment]
Will re-test on prod
