### ISSUE TITLE
Searching for COSMIC ID leads to error

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#552]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3566/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3566/)

```
Traceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 360, in search_within
    build_results = get_results_func(self.search_string,
  File "/data/variantgrid/variantopedia/search.py", line 415, in search_cosmic
    results = variant_qs.filter(variantannotation__cosmic_id__contains=search_string)
AttributeError: 'NoneType' object has no attribute 'filter'
```

**Comment by davmlaw** [comment]
This was super easy, was in the build independent section but was expecting variant_qs

**Comment by davmlaw** [comment]
Tested - this works but is really slow. Can't find a way to do it via API though to fix same way as dbSNP search
