### ISSUE TITLE
VEPVersionMismatchError: Annotation/VCF out of sync! Version 'v7. (17 July 2020) VEP: 100/Ensembl/GRCh37' and VCF '/data/annotation_scratch/dump_4541.vep_annotated_GRCh37.vcf.gz' differ, KEY: 'ensembl_variation' annotation: '100.b220ff4', vcf: '100.dd0b3c

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#590]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3050/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3050/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/mnt/variantgrid/annotation/tasks/annotate_variants.py", line 77, in annotate_variants
    import_vcf_annotations(annotation_run)
  File "/mnt/variantgrid/annotation/vcf_files/import_vcf_annotations.py", line 22, in import_vcf_annotations
    'vep_check_version_match(annotation_run.variant_..._version, annotation_run.vcf_annotated_filename)'
  File "/mnt/variantgrid/annotation/vep_annotation.py", line 314, in vep_check_version_match
    raise VEPVersionMismatchError(msg)
VEPVersionMismatchError: Annotation/VCF out of sync! Version 'v7. (17 July 2020) VEP: 100/Ensembl/GRCh37' and VCF '/data/annotation_scratch/dump_5141.vep_annotated_GRCh37.vcf.gz' differ, KEY: 'gnomad' annotation: '2.1.1', vcf: 'r2.1'
```

**Comment by davmlaw** [comment]
Deployed on variantgrid.com - annotation now works w/o error
