### ISSUE TITLE
Can't load singleton analysis

### ISSUE THREAD

**Issue by a1618617** [SACGF/variantgrid#594]
Hey guys,

It's only happening in this particular trio, but I can't load the singleton analysis without it throwing a "parent node error".
Can you please advise/help troubleshoot. 

http://frgeneseq02.imvs.sa.gov.au:92/analysis/23284/

**Comment by davmlaw** [comment]
Hi, I was able to resolve it by copying the identical sample node on the left and using it to replace the sample node in the top right

If this happens again, probably the best thing to do is go to settings, then click "force reload all nodes"

**Trying to figure out what went wrong**

Node 249926 had status of "D" (dirty) with no celery task in NodeTask - this caused children to fail

Node task was:

```
{'id': 135802, 'created': datetime.datetime(2022, 3, 1, 6, 30, 27, 6123, tzinfo=<UTC>), 'modified': datetime.datetime(2022, 3, 1, 6, 30, 27, 6163, tzinfo=<UTC>), 'node_id': 249926, 'version': 5, 'analysis_update_uuid': UUID('a4e0754f-3606-4010-af35-ef8e06ec635d'), 'celery_task': None, 'db_pid': None}
```

The failure occured in create_and_launch_analysis_tasks:

```[2022-03-01 17:00:26,957: INFO/ForkPoolWorker-1] Dirty nodes:
[2022-03-01 17:00:26,960: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249926/5
[2022-03-01 17:00:26,962: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249928/4
[2022-03-01 17:00:26,964: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249939/4
[2022-03-01 17:00:26,966: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249959/8
[2022-03-01 17:00:26,969: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249929/4
[2022-03-01 17:00:26,971: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249933/4
[2022-03-01 17:00:26,973: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249940/4
[2022-03-01 17:00:26,976: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249945/4
[2022-03-01 17:00:26,978: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249956/4
[2022-03-01 17:00:26,980: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249957/4
[2022-03-01 17:00:26,982: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249948/4
[2022-03-01 17:00:26,984: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249934/4
[2022-03-01 17:00:26,986: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249941/4
[2022-03-01 17:00:26,988: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249946/5
[2022-03-01 17:00:26,990: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249955/5
[2022-03-01 17:00:26,992: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249949/5
[2022-03-01 17:00:26,994: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249953/5
[2022-03-01 17:00:26,996: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249951/4
[2022-03-01 17:00:26,998: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249954/4
[2022-03-01 17:00:27,000: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249960/4
[2022-03-01 17:00:27,002: INFO/ForkPoolWorker-1] NodeTask: a4e0754f-3606-4010-af35-ef8e06ec635d - 249961/4
[2022-03-01 17:00:27,054: INFO/ForkPoolWorker-1] Got lock for: {249926: 5, 249928: 4, 249939: 4, 249959: 8, 249929: 4, 249933: 4, 249940: 4, 249945: 4, 249956: 4, 249957: 4, 249948: 4, 249934: 4, 249941: 4, 249946: 5, 249955: 5, 249949: 5, 249953: 5, 249951: 4, 249954: 4, 249960: 4, 249961: 4}
[2022-03-01 17:00:27,289: ERROR/ForkPoolWorker-1] Traceback (most recent call last):
  File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 951, in get
    return NodeVersion.objects.get(node=node, version=node.version)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 429, in get
    raise self.model.DoesNotExist(
analysis.models.nodes.analysis_node.NodeVersion.DoesNotExist: NodeVersion matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/variantgrid/analysis/tasks/analysis_update_tasks.py", line 25, in create_and_launch_analysis_tasks
    tasks = _get_analysis_update_tasks(analysis_id)
  File "/data/variantgrid/analysis/tasks/analysis_update_tasks.py", line 89, in _get_analysis_update_tasks
    group_cache_jobs = _add_jobs_for_group(node_versions_to_update, dependencies, grp, groups, all_cache_jobs)
  File "/data/variantgrid/analysis/tasks/analysis_update_tasks.py", line 127, in _add_jobs_for_group
    task_args_objs_set = node.get_cache_task_args_objs_set()
  File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 207, in get_cache_task_args_objs_set
    node_cache, created = NodeCache.get_or_create_for_node(self)
  File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 966, in get_or_create_for_node
    variant_collection = VariantCollection.objects.create(name=f"NodeCache {node.node_version}")
  File "/usr/local/lib/python3.8/dist-packages/lazy/lazy.py", line 28, in __get__
    value = self.__func(inst)
  File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 390, in node_version
    return NodeVersion.get(self)
  File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 953, in get
    node.check_still_valid()
  File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 97, in check_still_valid
    raise NodeOutOfDateException()
analysis.exceptions.NodeOutOfDateException: The node was updated while loading.


```

Rollbar https://rollbar.com/jimmy.andrews/VariantGrid/items/3306/occurrences/215334804170/

However - looking now, there is a NodeVersion of v5 (node's current version) and the ID is quite old.

Must be a race condition with where NodeVersion was supposed to be created (Node.save()) and the celery task being executed.

**Comment by a1618617** [comment]
I did force reload all nodes and it didn't work.

Best wishes,
Thuong

Thuong Ha, PhD
Medical Scientist, Department of Genetics & Molecular Pathology
Centre for Cancer Biology, SA Pathology
HB8-11, The Bradley Building, University of South Australia
North Terrace, Adelaide SA 5000, Australia

P: +61 8 8222 3963 | E: ***@***.*** | E: ***@***.***
________________________________

**Comment by davmlaw** [comment]
The problem occured in NodeCache - so this likely won't happen again now that MergeNode doesn't use that anymore

So - will close this as fixed and hope it doesn't show up again
