### ISSUE TITLE
Duplicated VariantAllele

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#598]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3646/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3646/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/variantgrid/classification/views/views.py", line 128, in get
    auto_data = generate_auto_populate_data(
  File "/data/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 76, in generate_auto_populate_data
    data.update(get_evidence_fields_for_variant(genome_build, variant,
  File "/data/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 195, in get_evidence_fields_for_variant
    'clingen_allele, evidence_value, message = get_c...vidence_value_for_variant(genome_build, variant)'
  File "/data/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 174, in get_clingen_allele_and_evidence_value_for_variant
    clingen_allele = get_clingen_allele_for_variant(genome_build, variant)
  File "/data/variantgrid/snpdb/clingen_allele.py", line 323, in get_clingen_allele_for_variant
    va = get_variant_allele_for_variant(genome_build, variant, clingen_api=clingen_api)
  File "/data/variantgrid/snpdb/clingen_allele.py", line 238, in get_variant_allele_for_variant
    va = VariantAllele.objects.get(variant=variant, genome_build=genome_build)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
MultipleObjectsReturned: get() returned more than one VariantAllele -- it returned 2!
```

**Comment by davmlaw** [comment]
I deleted the bad one to fix the issue, but here they were - think it's a race condition of some kind:

```
{'id': 97280, 'created': datetime.datetime(2022, 3, 8, 4, 30, 5, 165793, tzinfo=<UTC>), 'modified': datetime.datetime(2022, 3, 8, 4, 30, 5, 165826, tzinfo=<UTC>), 'variant_id': 28506442, 'genome_build_id': 'GRCh38', 'allele_id': 52238, 'origin': 'D', 'conversion_tool': 'CA', 'error': None}
{'id': 97281, 'created': datetime.datetime(2022, 3, 8, 4, 30, 10, 862663, tzinfo=<UTC>), 'modified': datetime.datetime(2022, 3, 8, 4, 30, 10, 862733, tzinfo=<UTC>), 'variant_id': 28506442, 'genome_build_id': 'GRCh38', 'allele_id': 52239, 'origin': 'D', 'conversion_tool': '', 'error': {'message': "Error contacting ClinGen Allele Registry. Method: 'PUT', Response: 502", 'errorType': 'ServerError', 'inputLine': 'NC_000011.10:g.108325395C>T', 'description': 'Error connecting to server: Connection refused'}}
```

**Comment by davmlaw** [comment]
Could also have handled this by only returning the one that was good

**Comment by davmlaw** [comment]
vg test:

* Created a fake allele, and variant allele (same variant/build)
* Checked in db there were 2 variant alleles linked to variant
* Was able to create a classification for variant OK

**Comment by davmlaw** [comment]
This has also occured in SA Path - need to patch back

**Comment by davmlaw** [comment]
The VariantAllele is unique together with variant/genome_build/allele - problem is there are duplicate alleles - there's an issue about it:
https://github.com/SACGF/variantgrid/issues/400

**Comment by davmlaw** [comment]
tested after prod deploy. Works ok
