### ISSUE TITLE
FieldError: Related Field got invalid lookup: icontains

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#601]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3664/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3664/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/dal/views.py", line 59, in dispatch
    return super(ViewMixin, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "/mnt/variantgrid/library/django_utils/autocomplete_utils.py", line 35, in get_queryset
    qs = qs.filter(q)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 974, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 992, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 999, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1375, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1252, in build_filter
    return self._add_q(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1396, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1329, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 1171, in build_lookup
    raise FieldError('Related Field got invalid lookup: {}'.format(lookup_name))
FieldError: Related Field got invalid lookup: icontains
```

**Comment by davmlaw** [comment]
GeneGrid gene annotation release auto complete had genome_build as field, should have been genome_build__name

**Comment by davmlaw** [comment]
Tested on vg test - was pretty easy to recreate: gene grid, open gene annotation release

**Comment by davmlaw** [comment]
This occured on SA Path - should patch it back as HF has happened a few times

**Comment by davmlaw** [comment]
Cherry picked bf75e0bdd9c9ae7a76ac716c8c411e3761cefe2a into vg3_sapath_prod

Still need to add the hotfix bitbucket entries etc
