### ISSUE TITLE
ValueError: Context Object LITAF does not have metrics_logging_key property

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#608]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3683/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3683/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/genes/views.py", line 370, in view_classifications
    return render(request, "genes/view_gene_symbol_classifications.html", {
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 176, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 101, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 977, in render
    return SafeString(''.join([
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 978, in <listcomp>
    node.render_annotated(context) for node in self
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 938, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/library.py", line 215, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
  File "/opt/variantgrid/classification/templatetags/classification_tags.py", line 111, in classification_groups
    raise ValueError(f"Context Object {context_object} does not have metrics_logging_key property")
ValueError: Context Object LITAF does not have metrics_logging_key propertyTraceback (most recent call last):
  File "/opt/variantgrid/classification/templatetags/classification_tags.py", line 108, in classification_groups
    logging_key = context_object.metrics_logging_key
AttributeError: 'str' object has no attribute 'metrics_logging_key'
```

**Comment by TheMadBug** [comment]
Now fixed
