### ISSUE TITLE
ProgrammingError: non-integer constant in ORDER BY
LINE 1: ...))) AND T8."genome_build_id" = 'GRCh38') ORDER BY 'GRCh38' A...
                                                             ^


### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#652]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3879/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3879/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/variantgrid/library/django_utils/jqgrid_view.py", line 60, in get
    return HttpResponse(grid_obj.get_json(request), content_type="application/json")
  File "/data/variantgrid/library/jqgrid.py", line 355, in get_json
    data = self.get_data(request)
  File "/data/variantgrid/library/jqgrid.py", line 350, in get_data
    'rows': list(items),
  File "/data/variantgrid/library/jqgrid.py", line 334, in iter_formatted_items
    for row in rows:
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1303, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 111, in __iter__
    for row in compiler.results_iter(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size):
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1106, in results_iter
    results = self.execute_sql(MULTI, chunked_fetch=chunked_fetch, chunk_size=chunk_size)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
ProgrammingError: non-integer constant in ORDER BY
LINE 1: ...))) AND T8."genome_build_id" = 'GRCh38') ORDER BY 'GRCh38' A...
                                                             ^
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
SyntaxError: non-integer constant in ORDER BY
LINE 1: ...))) AND T8."genome_build_id" = 'GRCh38') ORDER BY 'GRCh38' A...
                                                             ^

```

**Comment by davmlaw** [comment]
Recreated on dev, 

* go to view sample page, of a sample that has a variant tag
* scroll to bottom of page to variant tags grid
* Click the genome build header, to sort by that column
* sends in ```sidx=view_genome_build``` then crashes with exception above

**Comment by davmlaw** [comment]
confirmed vg test - can no longer sort genome build column variant grid on sample page
