### ISSUE TITLE
Tagged variants, all variants grid - count times out

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#676]
OperationalError: canceling statement due to statement timeout

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3936/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3936/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 62, in get
    return HttpResponse(grid_obj.get_json(request), content_type="application/json")
  File "/mnt/variantgrid/library/jqgrid.py", line 355, in get_json
    data = self.get_data(request)
  File "/mnt/variantgrid/library/jqgrid.py", line 346, in get_data
    paginator, page, items = self.get_items(request)
  File "/mnt/variantgrid/library/jqgrid_sql.py", line 60, in get_items
    if self.is_empty():
  File "/mnt/variantgrid/library/jqgrid_sql.py", line 41, in is_empty
    return self.get_count() == 0
  File "/mnt/variantgrid/snpdb/grids.py", line 363, in get_count
    return self.queryset.count()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 470, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 552, in get_count
    number = obj.get_aggregation(using, ["__count"])["__count"]
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/query.py", line 537, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
OperationalError: canceling statement due to statement timeout
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
QueryCanceled: canceling statement due to statement timeout

```

**Comment by davmlaw** [comment]
Made the tags query a bit faster. Also made the grid cache counts (was calling twice)

Also discovered a bug where the grid counts weren't taking into account the filter

For the variant one, the bad performance was when it was doing a "contains" gene search. We could perhaps add a built in filter for genes - that uses the more efficient gene overlap code.

We could also pre-calculate per-contig counts of variants and maybe variants with zygosity > 0, then add them up to obtain the count. But that seems a lot of work...

**Comment by davmlaw** [comment]
Made the tags query a bit faster. Also made the grid cache counts (was calling twice)

Also discovered a bug where the grid counts weren't taking into account the filter

For the variant one, the bad performance was when it was doing a "contains" gene search. We could perhaps add a built in filter for genes - that uses the more efficient gene overlap code.

We could also pre-calculate per-contig counts of variants and maybe variants with zygosity > 0, then add them up to obtain the count. But that seems a lot of work...

**Comment by davmlaw** [comment]
Benchmarks on test.variantgrid.com (slow HD)

tags variant grid (3), reload: 35.7, 37.125, 37.0
all variants grid, (1765421) reload: 15.2s, 15.9, 18.1

**Comment by davmlaw** [comment]
vg.com tags grid comes up really fast now
