### ISSUE TITLE
TypeError: '>' not supported between instances of 'NoneType' and 'int'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#678]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3947/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3947/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/vary.py", line 42, in inner_func
    response = func(*args, **kwargs)
  File "/mnt/variantgrid/analysis/views/views.py", line 276, in node_view
    return view(request, pk=node_id, version_id=node_version, extra_filters=extra_filters)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/edit.py", line 204, in get
    return super().get(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "/mnt/variantgrid/analysis/views/nodes/sample_node_view.py", line 11, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/mnt/variantgrid/analysis/views/nodes/gene_coverage_node_view.py", line 9, in get_context_data
    context = super().get_context_data(**kwargs)
  File "/mnt/variantgrid/analysis/views/nodes/node_view.py", line 31, in get_context_data
    grid = VariantGrid(self.request.user, self.object, extra_filters)
  File "/mnt/variantgrid/analysis/grids.py", line 78, in __init__
    self.fields, override = self._get_fields_and_overrides(node, af_show_in_percent)
  File "/mnt/variantgrid/analysis/grids.py", line 233, in _get_fields_and_overrides
    fields.extend(node.get_extra_columns())
  File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 685, in get_extra_columns
    if self.is_valid():
  File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 729, in is_valid
    return not self.get_errors()
  File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 625, in get_errors
    errors.extend((NodeErrorSource.CONFIGURATION, ce) for ce in self._get_configuration_errors())
  File "/mnt/variantgrid/analysis/models/nodes/sources/sample_node.py", line 192, in _get_configuration_errors
    errors = super()._get_configuration_errors()
  File "/mnt/variantgrid/analysis/models/nodes/cohort_mixin.py", line 227, in _get_configuration_errors
    if uv.max_variant_id > lowest_unannotated_variant:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
```

**Comment by davmlaw** [comment]
tested, no longer occurs
