### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one Variant -- it returned 4!

### ISSUE THREAD

**Issue by TheMadBug** [SACGF/variantgrid#681]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3957/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3957/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/opt/variantgrid/classification/views/views.py", line 227, in create_classification
    return redirect(create_classification_object(request).get_edit_url())
  File "/opt/variantgrid/classification/views/views.py", line 255, in create_classification_object
    classification = create_classification_for_sample_and_variant_objects(request.user, sample,
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 45, in create_classification_for_sample_and_variant_objects
    classification_auto_populate_fields(classification, genome_build,
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 99, in classification_auto_populate_fields
    auto_data = generate_auto_populate_data(
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 76, in generate_auto_populate_data
    data.update(get_evidence_fields_for_variant(genome_build, variant,
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 228, in get_evidence_fields_for_variant
    'data.update(get_evidence_fields_from_variant_qu...t_columns, ekey_formatters, annotation_version))'
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 476, in get_evidence_fields_from_variant_query
    values = qs.values(*columns).get()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 499, in get
    raise self.model.MultipleObjectsReturned(
MultipleObjectsReturned: get() returned more than one Variant -- it returned 4!
```

**Comment by TheMadBug** [comment]
Occurred when trying to make a classification via the web interface here:
https://test.shariant.org.au/classification/create_for_variant/55855/GRCh38

**Comment by TheMadBug** [comment]
This seems to be happeneing for all variants and all genome builds.

While we don't need to make classifications via the web form in Shariant, would be nice to get to the bottom of this when you get a chance @davmlaw

**Comment by davmlaw** [comment]
This was due to joining to gene annotation / dbNSFP without a constraint - as that's only done if gene annotation version is non-None

So, now we only include columns that use gene annotation if the setting is enabled.

Deployed and tested in Shariant test

**Comment by davmlaw** [comment]
Needs to be tested w/Shariant - was discovered there as gene annotaiton disabled

**Comment by TheMadBug** [comment]
Just creating a classification via the web forms would cause this prior to the fix. That was the only known place this specific bug was known to manifest.
