### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#707]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4044/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4044/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/vary.py", line 38, in inner_func
    response = func(*args, **kwargs)
  File "/data/variantgrid/analysis/views/node_json_view.py", line 57, in get
    return self.get_response(request, *args, **kwargs)
  File "/data/variantgrid/analysis/views/node_json_view.py", line 29, in get_response
    data = self._get_data(request, *args, node=node, **kwargs)
  File "/data/variantgrid/analysis/views/views_grid.py", line 51, in _get_data
    return grid.get_data(request)
  File "/data/variantgrid/library/jqgrid.py", line 346, in get_data
    paginator, page, items = self.get_items(request)
  File "/data/variantgrid/library/jqgrid_sql.py", line 63, in get_items
    return self.get_items_from_queryset(request)
  File "/data/variantgrid/library/jqgrid_sql.py", line 66, in get_items_from_queryset
    sql, params, column_names, is_sorted = self.get_sql_params_and_columns(request)
  File "/data/variantgrid/analysis/grids.py", line 156, in get_sql_params_and_columns
    values_queryset = self.get_values_queryset()
  File "/data/variantgrid/analysis/grids.py", line 134, in get_values_queryset
    self.queryset = self._get_queryset()
  File "/data/variantgrid/analysis/grids.py", line 120, in _get_queryset
    qs = self.node.get_queryset()
  File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 464, in get_queryset
    arg_q_dict = self.get_arg_q_dict(disable_cache=disable_cache)
  File "/data/variantgrid/analysis/models/nodes/analysis_node.py", line 384, in get_arg_q_dict
    arg_q_dict = self._get_arg_q_dict_from_parents_and_node()
  File "/data/variantgrid/analysis/models/nodes/filters/merge_node.py", line 140, in _get_arg_q_dict_from_parents_and_node
    return self._get_merged_q_dict(parent_arg_q_dict)
  File "/data/variantgrid/analysis/models/nodes/filters/merge_node.py", line 125, in _get_merged_q_dict
    if q := self._split_common_filters(parent_arg_q_dict):
  File "/data/variantgrid/analysis/models/nodes/filters/merge_node.py", line 70, in _split_common_filters
    combine_q &= MergeNode._split_common_filters(combine_parent_arg_q_dict)
  File "/data/variantgrid/analysis/models/nodes/filters/merge_node.py", line 87, in _split_common_filters
    merged_q = reduce(operator.and_, remaining_q_set)
TypeError: reduce() of empty sequence with no initial value
```

**Comment by davmlaw** [comment]
Snuck in quick deploy on SA Path prod, no longer occurs where it once did

**Comment by davmlaw** [comment]
This was due to "same variant via different paths" which when you converted the querysets into lists, caused the same Q hash so got removed and there was nothing else to combine in the querysets
