### ISSUE TITLE
PermissionDenied: You must be a super user to view this page

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#709]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4012/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4012/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/variantgrid/library/django_utils/__init__.py", line 57, in wrapper
    raise PermissionDenied("You must be a super user to view this page")
PermissionDenied: You must be a super user to view this page
```

**Comment by davmlaw** [comment]
I thought I had patched back a pages user permission so A could access this page
