### ISSUE TITLE
InvalidHGVSName: Invalid HGVS name "NM_000535(PMS2):c.736_741delins11": alt=NNNNNNNNNNN contains non-standard (A,C,G,T) bases: NNNNNNNNNNN

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#713]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4053/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4053/)

```
Traceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 360, in search_within
    build_results = get_results_func(self.search_string,
  File "/data/variantgrid/variantopedia/search.py", line 512, in search_hgvs
    raise original_error  # cleaning didn't work don't tell anyone
  File "/data/variantgrid/variantopedia/search.py", line 496, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/data/variantgrid/genes/hgvs.py", line 412, in get_variant_tuple
    raise pyhgvs.InvalidHGVSName(hgvs_name, reason=reason)
InvalidHGVSName: Invalid HGVS name "NM_000535.7(PMS2):c.736_741delins11": alt=NNNNNNNNNNN contains non-standard (A,C,G,T) bases: NNNNNNNNNNNTraceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 501, in search_hgvs
    variant_tuple = hgvs_matcher.get_variant_tuple(hgvs_string)
  File "/data/variantgrid/genes/hgvs.py", line 412, in get_variant_tuple
    raise pyhgvs.InvalidHGVSName(hgvs_name, reason=reason)
InvalidHGVSName: Invalid HGVS name "NM_000535.7(PMS2):c.736_741delins11": alt=NNNNNNNNNNN contains non-standard (A,C,G,T) bases: NNNNNNNNNNN
```

**Comment by davmlaw** [comment]
Someone kept dumping that into search many times

Perhaps we can search for stuff by using the ref even though we don't know the alt?

Or give a better warning saying why it's invalid

**Comment by davmlaw** [comment]
Biocommons HGVS fails as well with:

```
hgvs.exceptions.HGVSParseError: NM_000535(PMS2):c.736_741delins11: char 32: expected EOF
```

Variant validator doesn't accept it - gives:

```
The length of the variant is not formatted following the HGVS guidelines. Please rewrite e.g. 10 to N[10](where N is an unknown nucleotide)
```

**Comment by EmmaTudini** [comment]
@davmlaw Happy for this to fail. See my suggestion for a nicer "error" in variantgrid_private #2027

**Comment by TheMadBug** [comment]
Can confirm both pyhgvs and biocommons fail with this, search suggests a lot of things because it subtitutes NNNN with everything (for admins anyway, only 1 resolves to 1 record for non admins).
Error message in resolution isn't great, but I hope we don't get any records imports like this in the first place.
