### ISSUE TITLE
Create manual variant fails - KeyError: 'NM_000162.3'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#715]
Occurs in latest master - search for "NM_033517.1(SHANK3):2956 G>T"

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3462/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3462/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/variantgrid/annotation/views.py", line 450, in create_manual_variant_entry_from_text
    create_manual_variants(request.user, genome_build, variants_text)
  File "/data/variantgrid/annotation/manual_variant_entry.py", line 52, in create_manual_variants
    variants_list.extend(get_manual_variant_tuples(mve))
  File "/data/variantgrid/annotation/tasks/process_manual_variants_task.py", line 29, in get_manual_variant_tuples
    variant_tuples.append(Variant.get_tuple_from_string(mve.entry_text, mve.genome_build))
  File "/data/variantgrid/snpdb/models/models_variant.py", line 348, in get_tuple_from_string
    contig = genome_build.chrom_contig_mappings[chrom]
KeyError: 'NM_033517.1(SHANK3)'
```

**Comment by davmlaw** [comment]
This is because the "NM_033517.1(SHANK3):2956 G>T" is missing a "c." and thus matches to type variant

* Tightened up variant match
* Loosened HGVS match to be able to catch this
* Added to clean hgvs ability to add c. or g. if starts with transcript and has colon but missing c or g

**Comment by davmlaw** [comment]
Tested VG test - fail - doesn't seem to handle "NM_033517.1(SHANK3):2956 G>T" properly

**Comment by davmlaw** [comment]
I handled the missing "c." - to test search for "NM_000492.3(CFTR): 1438G>T"

But the shank search died because it had resolution errors. I now made that show up as an error rather than "no results"

**Comment by davmlaw** [comment]
Testing on test.variantgrid.com:

This now gives better error (can't resolve for other reasons)

**NM_033517.1(SHANK3):2956 G>T**
```
HGVS: Invalid HGVS allele "2956 G>T": expected kind "c.", "p.", "g.", etc (GRCh37, GRCh38)
HGVS: Could not convert NM_033517.1(SHANK3):c.2956G>T - tried: ClinGen Allele Registry (GRCh37, GRCh38)
```

**NM_000492.3(CFTR): 1438G>T**

Gives warning and resolves:

```
Warning: Cleaned 'NM_000492.3(CFTR): 1438G>T' => 'NM_000492.3(CFTR):c.1438G>T'
```
