### ISSUE TITLE
UniProt resource failing

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#716]
Reloading UniProt cached web resource task (annotation page) fails with:

```
[2022-11-17 17:48:33,206: INFO/ForkPoolWorker-2] Downloading 'uniprot_sprot_human.dat.gz' via FTP
[2022-11-17 17:50:53,640: INFO/ForkPoolWorker-2] Extracting data
[2022-11-17 17:50:53,669: ERROR/ForkPoolWorker-2] Traceback (most recent call last):
  File "/home/dlawrence/localwork/variantgrid/annotation/tasks/cached_web_resource_tasks.py", line 24, in run
    self._load_cached_web_resource(cached_web_resource)
  File "/home/dlawrence/localwork/variantgrid/genes/tasks/cached_web_resource_tasks.py", line 57, in _load_cached_web_resource
    store_uniprot_from_web(cached_web_resource)
  File "/home/dlawrence/localwork/variantgrid/genes/cached_web_resource/uniprot.py", line 31, in store_uniprot_from_web
    store_uniprot(cached_web_resource, text_f)
  File "/home/dlawrence/localwork/variantgrid/genes/cached_web_resource/uniprot.py", line 36, in store_uniprot
    uniprot_data = extract_uniprot_sprot(file_object)
  File "/home/dlawrence/localwork/variantgrid/genes/cached_web_resource/uniprot.py", line 62, in extract_uniprot_sprot
    for record in reader:
  File "/usr/local/lib/python3.10/dist-packages/Bio/SwissProt/__init__.py", line 239, in parse
    record = _read(handle)
  File "/usr/local/lib/python3.10/dist-packages/Bio/SwissProt/__init__.py", line 371, in _read
    _read_ft(record, line)
  File "/usr/local/lib/python3.10/dist-packages/Bio/SwissProt/__init__.py", line 830, in _read_ft
    key = keys[-1]
IndexError: list index out of range
```

**Comment by davmlaw** [comment]
Have a look, if it's hard maybe just skip that record

**Comment by davmlaw** [comment]
This has been fixed in BioPython: https://github.com/biopython/biopython/issues/4021

They don't have a release that fixes it yet, so I changed requirements to use github. Fixed commit to today. Tested and works fine
