### ISSUE TITLE
Somalier VCF task fails for genome in a bottle VCF

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#721]
```
'NoneType' object is not iterable
Traceback (most recent call last):
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 70, in run
    items_processed = self.process_items(upload_step)
  File "/mnt/variantgrid/upload/tasks/vcf/genotype_vcf_tasks.py", line 166, in process_items
    somalier_vcf_id(vcf.pk)
  File "/usr/local/lib/python3.8/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 735, in __protected_call__
    return orig(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/app/task.py", line 392, in __call__
    return self.run(*args, **kwargs)
  File "/mnt/variantgrid/snpdb/tasks/somalier_tasks.py", line 37, in somalier_vcf_id
    vcf_filename = _write_somalier_vcf(cfg, processing_dir, vcf_extract)
  File "/mnt/variantgrid/snpdb/tasks/somalier_tasks.py", line 66, in _write_somalier_vcf
    sample_zygosity_count = vcf_export_to_file(vcf, exported_vcf_filename, original_qs=sites_qs,
  File "/mnt/variantgrid/snpdb/variants_to_vcf.py", line 109, in vcf_export_to_file
    for i, (z, ad, dp, af) in enumerate(zip(samples_zygosity, allele_depth, read_depth, allele_frequency)):
TypeError: 'NoneType' object is not iterable
```

**Comment by davmlaw** [comment]
This is because some of the VCF records don't have what we need, eg this one is missing DP

```
chr6	30806580	.	G	A	30	.	.	GT:AD:PS	1/1:0,2
```

Attached example:

[missing_genotype_fields.vcf.gz](https://github.com/SACGF/variantgrid/files/10073040/missing_genotype_fields.vcf.gz)

**Comment by davmlaw** [comment]
Looks like the missing GT etc fields work fine in analysis sample node. So the problem isn't that we shouldn't store null values, but the VCF export code should handle blanks

**Comment by davmlaw** [comment]
VG test - tested ok
