### ISSUE TITLE
All variants node fails when ref value entered

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#725]
Create all variants node

Set ref=1, save. Dies w/error:

```
Internal Error: Traceback (most recent call last):
File "/mnt/variantgrid/analysis/tasks/node_update_tasks.py", line 44, in update_node_task node.load()
File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 884, in load status, count = self.node_counts()
File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 855, in node_counts retrieved_label_counts = get_node_counts_and_labels_dict(self, counts_to_get)
File "/mnt/variantgrid/analysis/models/nodes/node_counts.py", line 74, in get_node_counts_and_labels_dict qs = node.get_queryset(inner_query_distinct=True)
File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 542, in get_queryset raise Exception(f"arg_q_dict filters {arg_q_dict.keys()} not applied (missing annotation_kwargs)") Exception: arg_q_dict filters dict_keys(['global_variant_zygosity__ref_count']) not applied (missing annotation_kwargs) 
```

Also affects SA Path prod, patch back

**Comment by davmlaw** [comment]
Commit in 565eebc098f9aac8d38906f4aef121cd9f4ea021  - need to patch back to SAP

**Comment by davmlaw** [comment]
Patched back to SAP - need to test

**Comment by davmlaw** [comment]
The following occured, though I don't know how to recreate it

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/vary.py", line 42, in inner_func
    response = func(*args, **kwargs)
  File "/opt/variantgrid/analysis/views/views_grid.py", line 45, in get
    response = self.get_response(request, *args, **kwargs)
  File "/opt/variantgrid/analysis/views/node_json_view.py", line 29, in get_response
    data = self._get_data(request, *args, node=node, **kwargs)
  File "/opt/variantgrid/analysis/views/views_grid.py", line 71, in _get_data
    return grid.get_data(request)
  File "/opt/variantgrid/library/jqgrid.py", line 346, in get_data
    paginator, page, items = self.get_items(request)
  File "/opt/variantgrid/library/jqgrid_sql.py", line 67, in get_items
    return self.get_items_from_queryset(request)
  File "/opt/variantgrid/library/jqgrid_sql.py", line 105, in get_items_from_queryset
    raise e
  File "/opt/variantgrid/library/jqgrid_sql.py", line 100, in get_items_from_queryset
    cursor.execute(sql)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.10/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.10/dist-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
django.db.utils.ProgrammingError: syntax error at or near "LEFT"
LINE 47: LEFT OUTER JOIN "snpdb_cohortgenotype_collection_30" ON ("sn...
```

**Comment by davmlaw** [comment]
Any fix needs to go back to SAP as well

**Comment by davmlaw** [comment]
Appears to be due to the left join being added after the order by

```
select *
FROM "snpdb_variant"
LEFT OUTER JOIN "snpdb_cohortgenotype" cohortgenotype_30 ON ("snpdb_variant"."id" = cohortgenotype_30."variant_id" AND (cohortgenotype_30."collection_id" IN (30, 29)))
LEFT OUTER JOIN "snpdb_variantzygositycount" global_variant_zygosity ON ("snpdb_variant"."id" = global_variant_zygosity."variant_id" AND (global_variant_zygosity."collection_id" = 1))
INNER JOIN "snpdb_locus" ON ("snpdb_variant"."locus_id" = "snpdb_locus"."id")
INNER JOIN "snpdb_contig" ON ("snpdb_locus"."contig_id" = "snpdb_contig"."id")
INNER JOIN "snpdb_sequence" ON ("snpdb_locus"."ref_id" = "snpdb_sequence"."id")
INNER JOIN "snpdb_sequence" T7 ON ("snpdb_variant"."alt_id" = T7."id")
LEFT OUTER JOIN "annotation_variantannotation_version_8" ON ("snpdb_variant"."id" = "annotation_variantannotation_version_8"."variant_id") LEFT OUTER JOIN "genes_transcriptversion" ON ("annotation_variantannotation_version_8"."transcript_version_id" = "genes_transcriptversion"."id")
LEFT OUTER JOIN "genes_geneversion" ON ("genes_transcriptversion"."gene_version_id" = "genes_geneversion"."id")
LEFT OUTER JOIN "genes_gene" ON ("annotation_variantannotation_version_8"."gene_id" = "genes_gene"."identifier")
LEFT OUTER JOIN "annotation_geneannotation_version_5" ON ("genes_gene"."identifier" = "annotation_geneannotation_version_5"."gene_id")
LEFT OUTER JOIN "annotation_dbnsfpgeneannotation" ON ("annotation_geneannotation_version_5"."dbnsfp_gene_id" = "annotation_dbnsfpgeneannotation"."id") LEFT OUTER JOIN "annotation_clinvar_version_2" ON ("snpdb_variant"."id" = "annotation_clinvar_version_2"."variant_id") LEFT OUTER JOIN "genes_hgnc" ON ("genes_geneversion"."hgnc_id" = "genes_hgnc"."id")
LEFT OUTER JOIN "genes_uniprot" ON ("genes_hgnc"."uniprot_id" = "genes_uniprot"."accession")
ORDER BY "snpdb_variant"."id" ASC NULLS FIRST
	LEFT OUTER JOIN "snpdb_cohortgenotype_collection_30" ON ("snpdb_variant"."id" = "snpdb_cohortgenotype_collection_30"."variant_id")
	 LIMIT 10 OFFSET 0
```

The is also the problem where cohort node is doing a left OUTER join - should be inner - as we need to restrict records to it...

**Comment by davmlaw** [comment]
If you specified a min of 0, it didn't apply it as it did a falsey check not a is None. This caused both problems

**Comment by davmlaw** [comment]
Tested in SAP test, works ok
