### ISSUE TITLE
Cohort analysis template - leads to cohort node error

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#726]
Creating a new cohort node is fine. Just whatever the cohort template is doing causes an error:

```
Internal Error: Traceback (most recent call last):
File "/mnt/variantgrid/analysis/tasks/node_update_tasks.py", line 44, in update_node_task node.load()
File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 884, in load status, count = self.node_counts()
File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 855, in node_counts retrieved_label_counts = get_node_counts_and_labels_dict(self, counts_to_get)
File "/mnt/variantgrid/analysis/models/nodes/node_counts.py", line 74, in get_node_counts_and_labels_dict qs = node.get_queryset(inner_query_distinct=True)
File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 522, in get_queryset arg_q_dict = self.get_arg_q_dict(disable_cache=disable_cache)
File "/mnt/variantgrid/analysis/models/nodes/analysis_node.py", line 415, in get_arg_q_dict arg_q_dict[None] = {} TypeError: 'NoneType' object does not support item assignment 
```

Occurs in VG AWS and local dev.

Need to check if SA Path is ok

**Comment by davmlaw** [comment]
Commit if we need to patch back https://github.com/SACGF/variantgrid/commit/eec3cf0bd0b4ff5de83a59fd4b19f9c7643ee706

**Comment by davmlaw** [comment]
Testing VG test - created cohort analysis and worked ok

Patched back - need to test in SAP

**Comment by davmlaw** [comment]
Tested SAP test, works ok
