### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one Variant -- it returned 2!

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#735]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3460/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3460/)

```
Traceback (most recent call last):
  File "/data/variantgrid/variantopedia/search.py", line 360, in search_within
    build_results = get_results_func(self.search_string,
  File "/data/variantgrid/variantopedia/search.py", line 530, in search_hgvs
    variant = results.get()
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
MultipleObjectsReturned: get() returned more than one Variant -- it returned 2!
```

**Comment by davmlaw** [comment]
This is only legacy SA Path - was issue #295 - patched fix for that back to SA Path
