### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one GeneList -- it returned 2!

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#748]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4052/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4052/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/variantgrid/library/django_utils/jqgrid_view.py", line 45, in get
    grid_obj = self._load_grid(request, *args, **kwargs)
  File "/data/variantgrid/library/django_utils/jqgrid_view.py", line 41, in _load_grid
    return grid_klass(**kwargs)
  File "/data/variantgrid/genes/grids.py", line 87, in __init__
    gene_list = GeneList.get_for_user(user, gene_list_id, success_only=False)
  File "/data/variantgrid/genes/models.py", line 1133, in get_for_user
    return GeneList.filter_for_user(user, success_only).get(pk=gene_list_id)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
MultipleObjectsReturned: get() returned more than one GeneList -- it returned 2!
```

**Comment by davmlaw** [comment]
Patched back to SA Path:

testing - before this used to produce the error in sa path test:

```
from snpdb.models import User
from genes.models import GeneList
ihidlaw = User.objects.get(username='ihidlaw')
GeneList.get_for_user(ihidlaw, 16816)
```

**Comment by davmlaw** [comment]
Fix works on sa path test
Also loaded gene list from dropdown in gene grid and gene list node
Gene list page grid also works ok

**Comment by davmlaw** [comment]
previously failing url works now after prod deploy
