### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#764]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4206/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4206/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/variantgrid/classification/views/views.py", line 182, in get
    auto_data = generate_auto_populate_data(
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 86, in generate_auto_populate_data
    data.update(get_evidence_fields_for_variant(genome_build, variant,
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 232, in get_evidence_fields_for_variant
    'data.update(get_evidence_fields_from_variant_qu...t_columns, ekey_formatters, annotation_version))'
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 487, in get_evidence_fields_from_variant_query
    set_evidence(data, evidence_key, value, immutable, ekey_formatters, note=note)
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 402, in set_evidence
    value = formatter(value)
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 150, in pubmed_formatter
    return "\n".join([f"PMID:{p}" for p in value.split(VEP_SEPARATOR)])
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by davmlaw** [comment]
Works on dev as well - example variant of NC_000017.11:g.43074436_43074437insGG

**Comment by davmlaw** [comment]
tested vg test - no longer occurs
