### ISSUE TITLE
PanelApp gene lists not set to public share permissions

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#772]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3271/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3271/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 47, in get
    grid_obj = self._load_grid(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 43, in _load_grid
    return grid_klass(**kwargs)
  File "/mnt/variantgrid/genes/grids.py", line 92, in __init__
    gene_list = GeneList.get_for_user(user, gene_list_id, success_only=False)
  File "/mnt/variantgrid/genes/models.py", line 1696, in get_for_user
    raise PermissionDenied(msg)
PermissionDenied: You don't have permission to access gene_list 6522Traceback (most recent call last):
  File "/mnt/variantgrid/genes/models.py", line 1690, in get_for_user
    return GeneList.filter_for_user(user, success_only).get(pk=gene_list_id)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 496, in get
    raise self.model.DoesNotExist(
DoesNotExist: GeneList matching query does not exist.
```

**Comment by davmlaw** [comment]
Ran manually on vg.com

```
        for gene_list in GeneList.objects.filter(category__name=GeneListCategory.PANEL_APP_CACHE):
            add_public_group_read_permission(gene_list)
```

**Comment by davmlaw** [comment]
Every panel app cache should be shared with logged in users
