### ISSUE TITLE
gene_symbol_info_tab errors on non-HGNC gene - NoReverseMatch: Reverse for 'view_gene_symbol' with arguments '('',)' not found.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#773]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4220/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4220/)

This was referred to via variant page NC_000016.9:g.70316572A>G - AARS is a non-HGNC gene

http://localhost:8000/genes/gene_symbol_info_tab/AARS/tool_tips/True

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/mnt/variantgrid/genes/views.py", line 580, in gene_symbol_info_tab
    return render(request, 'genes/gene_symbol_info_tab.html', context=context)
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 62, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 111, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/mnt/variantgrid/uicore/templatetags/ui_utils.py", line 245, in render
    output = self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 958, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'view_gene_symbol' with arguments '('',)' not found. 1 pattern(s) tried: ['genes/view_gene_symbol/(?P<gene_symbol>[^/]+)\\Z']
```

**Comment by davmlaw** [comment]
This does not affect shariant (view variant annotations)
