### ISSUE TITLE
Export tags grid - NodeOutOfDateException: The node was updated while loading.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#789]
I watched a user delete a tag (this caused tag node to become out of date etc), then try and export a grid. This crashed.

I think we can assume that the user wants the latest version of a node. Perhaps we should just have a timeout option and just wait until the node loads then export the latest version?

Or - we could have a notice come up saying the node was changed during the operation and to retry (better than a crash!)

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/3288/](https://rollbar.com/jimmy.andrews/VariantGrid/items/3288/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/variantgrid/analysis/views/views_grid.py", line 179, in node_grid_export
    node = _node_from_request(request)
  File "/data/variantgrid/analysis/views/views_grid.py", line 220, in _node_from_request
    return get_node_subclass_or_non_fatal_exception(request.user, node_id, version=version_id)
  File "/data/variantgrid/analysis/views/analysis_permissions.py", line 44, in get_node_subclass_or_non_fatal_exception
    return _get_node(user, node_id, write=write, version=version)
  File "/data/variantgrid/analysis/views/analysis_permissions.py", line 23, in _get_node
    raise NodeOutOfDateException(f"{node.pk}: requested: {version}, DB: {node.version}")
NodeOutOfDateException: The node was updated while loading.
```

**Comment by davmlaw** [comment]
From issue #1363 

We swallowed this error elsewhere.

In this particular case. I think it may be worth NOT checking if the node is out of date. As if someone is in the editor and switching, it's probably someone else updating it, and they just wanted the info on what they asked for


---------


View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/3930](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/3930)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/variantgrid/analysis/views/views.py", line 787, in node_method_description
    node = get_node_subclass_or_404(request.user, node_id, version=node_version)
  File "/data/variantgrid/analysis/views/analysis_permissions.py", line 36, in get_node_subclass_or_404
    return _get_node(user, node_id, write=write, version=version)
  File "/data/variantgrid/analysis/views/analysis_permissions.py", line 23, in _get_node
    raise NodeOutOfDateException(f"{node.pk}: requested: {version}, DB: {node.version}")
NodeOutOfDateException: The node was updated while loading.
```
