### ISSUE TITLE
MultipleObjectsReturned: get() returned more than one CohortGenotypeCollection -- it returned 7!

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#791]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4255/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4255/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/variantgrid/snpdb/views/views.py", line 1045, in view_cohort
    cohort_genotype_collection = cohort.cohort_genotype_collection
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/mnt/variantgrid/snpdb/models/models_cohort.py", line 152, in cohort_genotype_collection
    return CohortGenotypeCollection.objects.get(cohort=cohort, cohort_version=cohort.version)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 499, in get
    raise self.model.MultipleObjectsReturned(
MultipleObjectsReturned: get() returned more than one CohortGenotypeCollection -- it returned 7!
```

**Comment by davmlaw** [comment]
The cohort (PED245_quad) was made yesterday. All the samples are from the same VCF, yet it has no vcf field set (must be manual?)

There are 7 cohortgenotypecollection records for v0
There are 7 cohortgenotypecollection records for v4

```
In [30]: c.cohortgenotypecollection_set.all().filter(cohort_version=0).values("id", "uncommon")
Out[30]: <QuerySet [{'id': 1002, 'uncommon': 1006}, {'id': 1003, 'uncommon': 1007}, {'id': 1004, 'uncommon': 1008}, {'id': 1005, 'uncommon': 1009}, {'id': 1010, 'uncommon': 1013}, {'id': 1011, 'uncommon': 1014}, {'id': 1012, 'uncommon': 1015}]>

In [31]: c.cohortgenotypecollection_set.all().filter(cohort_version=4).values("id", "uncommon")
Out[31]: <QuerySet [{'id': 1006, 'uncommon': None}, {'id': 1007, 'uncommon': None}, {'id': 1008, 'uncommon': None}, {'id': 1009, 'uncommon': None}, {'id': 1013, 'uncommon': None}, {'id': 1014, 'uncommon': None}, {'id': 1015, 'uncommon': None}]>
```

**Comment by davmlaw** [comment]
The reason for it looking like the same task was launched multiple times is because we run update code (so the final task just clobbers the others)

The question is why was it launched so often. Looks like it was done from the web:

```
/var/log/nginx/access.log.1:143.216.105.219 - - [28/Mar/2023:03:29:55 +0000] "GET /snpdb/cohort/create_cohort_genotype/1005 HTTP/1.1" 200 86 "https://variantgrid.com/snpdb/view_cohort/1005" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
/var/log/nginx/access.log.1:143.216.105.219 - - [28/Mar/2023:03:31:55 +0000] "GET /snpdb/cohort/create_cohort_genotype/1005 HTTP/1.1" 499 0 "https://variantgrid.com/snpdb/view_cohort/1005" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
/var/log/nginx/access.log.1:143.216.105.219 - - [28/Mar/2023:03:32:15 +0000] "GET /snpdb/cohort/create_cohort_genotype/1005 HTTP/1.1" 499 0 "https://variantgrid.com/snpdb/view_cohort/1005" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
/var/log/nginx/access.log.1:143.216.105.219 - - [28/Mar/2023:03:32:15 +0000] "GET /snpdb/cohort/create_cohort_genotype/1005 HTTP/1.1" 499 0 "https://variantgrid.com/snpdb/view_cohort/1005" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
/var/log/nginx/access.log.1:143.216.105.219 - - [28/Mar/2023:03:32:16 +0000] "GET /snpdb/cohort/create_cohort_genotype/1005 HTTP/1.1" 499 0 "https://variantgrid.com/snpdb/view_cohort/1005" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
/var/log/nginx/access.log.1:143.216.105.219 - - [28/Mar/2023:03:33:52 +0000] "GET /snpdb/cohort/create_cohort_genotype/1005 HTTP/1.1" 200 86 "https://variantgrid.com/snpdb/view_cohort/1005" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
/var/log/nginx/access.log.1:143.216.105.219 - - [28/Mar/2023:03:33:52 +0000] "GET /snpdb/cohort/create_cohort_genotype/1005 HTTP/1.1" 200 86 "https://variantgrid.com/snpdb/view_cohort/1005" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
/var/log/nginx/access.log.1:143.216.105.219 - - [28/Mar/2023:03:33:53 +0000] "GET /snpdb/cohort/create_cohort_genotype/1005 HTTP/1.1" 200 86 "https://variantgrid.com/snpdb/view_cohort/1005" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"
```

**Comment by davmlaw** [comment]
ok problem looks to me like the user hit the button multiple times. This happens as we only hide the button upon RESPONSE not when we click it.

We should also use versions, and have unique_together in the database etc to prevent this happening again

**Comment by davmlaw** [comment]
Disable button upon clicking. Also did JS linting of var to let/const. Made create_cohort_genotype a POST

**Comment by davmlaw** [comment]
clicked resolve in slack - forgot it closed it - still need to test / deploy
