### ISSUE TITLE
Check coordinate range within contig length

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#792]
View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4261/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4261/)

```
Traceback (most recent call last):
  File "/mnt/variantgrid/upload/tasks/vcf/import_vcf_step_task.py", line 70, in run
    items_processed = self.process_items(upload_step)
  File "/mnt/variantgrid/annotation/tasks/process_manual_variants_task.py", line 84, in process_items
    populate_clingen_alleles_for_variants(mvec.genome_build, variants_qs)
  File "/mnt/variantgrid/snpdb/clingen_allele.py", line 176, in populate_clingen_alleles_for_variants
    variant_hgvs.append(hgvs_matcher.variant_to_g_hgvs(v))
  File "/mnt/variantgrid/genes/hgvs.py", line 954, in variant_to_g_hgvs
    g_hgvs = self.variant_to_hgvs(variant)
  File "/mnt/variantgrid/genes/hgvs.py", line 939, in variant_to_hgvs
    hgvs_extra = self._variant_to_hgvs_extra(variant=variant, transcript_name=transcript_name)
  File "/mnt/variantgrid/genes/hgvs.py", line 827, in _variant_to_hgvs_extra
    hgvs_name, _ = self._variant_to_hgvs(variant, transcript_name)
  File "/mnt/variantgrid/genes/hgvs.py", line 930, in _variant_to_hgvs
    'hgvs_name = pyhgvs.variant_to_hgvs_name(chrom, ... ref, alt, self.genome_build.genome_fasta.fasta,'
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/__init__.py", line 270, in variant_to_hgvs_name
    chrom, offset, ref, [alt] = normalize_variant(
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/models/variants.py", line 146, in normalize_variant
    return NormalizedVariant(position, ref_sequence, alt_sequences,
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/models/variants.py", line 180, in __init__
    self._align(justify)
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/models/variants.py", line 254, in _align
    start, end, allele = justify_genomic_indel(
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/models/variants.py", line 115, in justify_genomic_indel
    indel_start, indel_end, indel = justify_indel(
  File "/usr/local/lib/python3.8/dist-packages/pyhgvs/models/variants.py", line 76, in justify_indel
    while start > 0 and seq[start - 1] == indel[-1]:
IndexError: string index out of range
```

**Comment by davmlaw** [comment]
X:399336776 TG>T

X is 155M so position 399M is quite a lot out of range. We should probably validate start/end at Variant creation time

**Comment by davmlaw** [comment]
fixed the search as well, you used to be able to create a variant like "99:123123 A>C"

Now it checks contig is legin and position is less than contig length

**Comment by davmlaw** [comment]
tested vg test ok
