### ISSUE TITLE
Tags - crashes due to FieldError: Expression contains mixed types: TextField, CharField. You must set output_field.

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#829]
http://test.variantgrid.com/variantopedia/tagged_variants/grid/GRCh38/handler/?_search=false&nd=1685671757651&rows=10&page=1&sidx=locus__position&sord=asc

Can't seem to reproduce on dev

View details in Rollbar: [https://rollbar.com/jimmy.andrews/VariantGrid/items/4350/](https://rollbar.com/jimmy.andrews/VariantGrid/items/4350/)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/variantgrid/library/django_utils/jqgrid_view.py", line 62, in get
    return HttpResponse(grid_obj.get_json(request), content_type="application/json")
  File "/opt/variantgrid/library/jqgrid/jqgrid.py", line 344, in get_json
    data = self.get_data(request)
  File "/opt/variantgrid/library/jqgrid/jqgrid.py", line 335, in get_data
    paginator, page, items = self.get_items(request)
  File "/opt/variantgrid/library/jqgrid/jqgrid_sql.py", line 64, in get_items
    return self.get_items_from_queryset(request)
  File "/opt/variantgrid/library/jqgrid/jqgrid_sql.py", line 67, in get_items_from_queryset
    sql, params, column_names, is_sorted = self.get_sql_params_and_columns(request)
  File "/opt/variantgrid/snpdb/grids.py", line 440, in get_sql_params_and_columns
    sql, column_names = self._get_sql_and_columns(values_queryset, order_by)
  File "/opt/variantgrid/snpdb/grids.py", line 449, in _get_sql_and_columns
    'new_columns, select_part, from_part, where_part...columns_select_from_where_parts(values_queryset)'
  File "/opt/variantgrid/snpdb/grids.py", line 462, in _get_new_columns_select_from_where_parts
    select_part, from_part, where_part = get_queryset_select_from_where_parts(values_queryset)
  File "/opt/variantgrid/library/utils/database_utils.py", line 69, in get_queryset_select_from_where_parts
    sql_str = queryset_to_sql(qs)
  File "/opt/variantgrid/library/utils/database_utils.py", line 28, in queryset_to_sql
    query, params = queryset.query.sql_with_params()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 284, in sql_with_params
    return self.get_compiler(DEFAULT_DB_ALIAS).as_sql()
  File "/opt/variantgrid/library/django_utils/django_queryset_sql_transformer.py", line 18, in as_sql
    sql, params = super().as_sql(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 573, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 64, in pre_sql_setup
    self.setup_query()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 55, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 284, in get_select
    sql, params = self.compile(col)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 496, in compile
    sql, params = node.as_sql(self, self.connection)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 1268, in as_sql
    subquery_sql, sql_params = query.as_sql(compiler, connection)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 1151, in as_sql
    sql, params = self.get_compiler(connection=connection).as_sql()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 573, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 64, in pre_sql_setup
    self.setup_query()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 55, in setup_query
    self.select, self.klass_info, self.annotation_col_map = self.get_select()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 295, in get_select
    sql, params = col.select_format(self, sql, params)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 419, in select_format
    if hasattr(self.output_field, "select_format"):
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 280, in output_field
    output_field = self._resolve_output_field()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 313, in _resolve_output_field
    source for source in self.get_source_fields() if source is not None
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/aggregates.py", line 48, in get_source_fields
    return [e._output_field_or_none for e in super().get_source_expressions()]
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/aggregates.py", line 48, in <listcomp>
    return [e._output_field_or_none for e in super().get_source_expressions()]
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 293, in _output_field_or_none
    return self.output_field
  File "/usr/local/lib/python3.10/dist-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 280, in output_field
    output_field = self._resolve_output_field()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 318, in _resolve_output_field
    raise FieldError(
FieldError: Expression contains mixed types: TextField, CharField. You must set output_field.
```

**Comment by davmlaw** [comment]
This seems to have been fixed by upgrading Django

VG test was 4.0.2
My dev was 4.1
Upgraded test to 4.2 and issue disappeared

Will keep this around as a reminder to upgrade vg.com version as well
