### ISSUE TITLE
View allele page fails if not lifted over to each build

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#865]
You need a variant that hasn't been lifted over (eg not a classification/tag etc).

It's not clear whether this is actually possible in Shariant as they should always have lifted over (unless there was an issue)

* As admin, search for a variant, eg create a new coordinate and search for "NM_007294.3:c.5097dup" then create

On the allele page, as the other variant hasn't been lifted over yet, you get an error

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4495](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4495)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/variantopedia/views.py", line 463, in view_allele
    return render(request, "variantopedia/view_allele.html", context)
  File "/usr/local/lib/python3.8/dist-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/local/lib/python3.8/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/test/utils.py", line 112, in instrumented_test_render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.8/dist-packages/django/template/base.py", line 966, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.8/dist-packages/django/template/defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'view_variant' with arguments '('',)' not found. 1 pattern(s) tried: ['variantopedia/view_variant/(?P<variant_id>[0-9]+)\\Z']
```

**Comment by TheMadBug** [comment]
Developer testing

Created https://test.shariant.org.au/variantopedia/view_allele/22222 by annotating NM_007294.3:c.5097dup as an admin and went to the resulting allele page.
There was only a 37 variant (at the time) and the page didn't break.
PASSED

Find an HGVS Imported that's missing 1 build e.g. https://test.shariant.org.au/variantopedia/view_allele/20742
Expected result: page renders fine but with blanks where 37 is meant to be
PASSED

WARNING the g.HGVS value doesn't have a gray dash in it if it has no value per the default behaviour (not sure why it's not showing), but this is such a rare occurrance and that bug is so small not worth actioning.

**Comment by EmmaTudini** [comment]
@TheMadBug @davmlaw I'd like to check if this is actually possible anymore. My understanding is that if we can't lift over to the alternative build coordinates, then we just fail the whole variant?

**Comment by EmmaTudini** [comment]
@TheMadBug @davmlaw I'd like to check if this is actually possible anymore. My understanding is that if we can't lift over to the alternative build coordinates, then we just fail the whole variant?

**Comment by EmmaTudini** [comment]
Imported 
NM_001733.7(C1R):c.1201del as GRCh38 - expected - create allele and leave GRCh37 blank
Actual output: Passed 
Note: @davmlaw @TheMadBug The variant matching in progress icon sticks around even though it says that it's matched to a variant. I think we know about this but wanted to bring it up in case it's new.

**Comment by TheMadBug** [comment]
I can confirm the variant matching in progress icon is there when you see it in classification listing.

This is, as you'd imagine, because the VCF liftover failed, and from the looks of ClinGen there might not be a 37 equivilant.
In these cases we can mark the ImportedAlleleInfo as complete.

(Clicking on "Mark as Complete" will change the status from Matched Variant to Matched All Builds and remove the matching icon).

![CleanShot 2023-10-06 at 09 38 55@2x](https://github.com/SACGF/variantgrid/assets/2100255/a3940b78-1cd2-4b76-ad5f-734ebf664ea9)

So the "good" news is:
* This is extremely rare
* This is what would currently happen in prod
* We are notified of variant matching issues in Slack, so we can find these and manually mark them as complete

It would definately be suprior if whatever was causing the VCF to not be accessible (probably was never created as there was no valid data for it?) was fixed, and the variant matching was automatically marked as complete - but that task could be done separately to all these other variant matching improvements.

**Comment by TheMadBug** [comment]
Can confirm https://shariant.org.au/variantopedia/view_allele/20742 loads properly despite not having a 37 variant.
