### ISSUE TITLE
JSONDecodeError: [Errno Expecting value] <!doctype html>
<html lang="en" class="vf-no-js">
  <head>
    <script>
// Detect if JS is on and swap vf-no-js for vf-js on the html element
(function(H){H.className=H.className.replace(/\bvf-no-js\b/,'vf-js')})(d

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#869]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4511](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4511)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/genes/views/views.py", line 476, in view_transcript_version
    tv_sequence_info = TranscriptVersionSequenceInfo.get(accession)
  File "/opt/variantgrid/genes/models.py", line 1300, in get
    tvi = TranscriptVersionSequenceInfo._get_and_store_from_ensembl_api(transcript_accession)
  File "/opt/variantgrid/genes/models.py", line 1347, in _get_and_store_from_ensembl_api
    data = r.json()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
JSONDecodeError: [Errno Expecting value] <!doctype html>
<html lang="en" class="vf-no-js">
  <head>
    <script>
// Detect if JS is on and swap vf-no-js for vf-js on the html element
(function(H){H.className=H.className.replace(/\bvf-no-js\b/,'vf-js')})(document.documentElement);
</script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" media="all" href="/css/styles.css?" /> -->
    <title>Error: 500 | EMBLâs European Bionformatics Institute</title>



    <link rel="icon" type="image/x-icon"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/favicon.ico" />
<link rel="icon" type="image/png"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="192Ã192"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/android-chrome-192x192.png" />
<!-- Android (192px) -->
<link rel="apple-touch-icon-precomposed" sizes="114x114"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-114x114.png" />
<!-- For iPhone 4 Retina display (114px) -->
<link rel="apple-touch-icon-precomposed" sizes="72x72"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-72x72.png" />
<!-- For iPad (72px) -->
<link rel="apple-touch-icon-precomposed" sizes="144x144"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-144x144.png" />
<!-- For iPad retinat (144px) -->
<link rel="apple-touch-icon-precomposed"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-57x57.png" />
<!-- For iPhone (57px) -->
<link rel="mask-icon"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/safari-pinned-tab.svg"
  color="#ffffff" /> <!-- Safari icon for pinned tab -->
<meta name="msapplication-TileColor" content="#2b5797" /> <!-- MS Icons -->
<meta name="msapplication-TileImage"
  content="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/mstile-144x144.png" />






    <!-- Search indexing optimisations -->
    <meta class="swiftype" name="what" data-type="string" content="none" />
    <meta class="swiftype" name="where" data-type="string" content="EMBL-EBI" />


    <!-- Descriptive meta -->
    <meta name="title" content="Error: 500">
    <meta name="author" content="European Bioinformatics Institute">
    <meta name="robots" content="index, follow">
    <meta name="keywords" content="">
    <meta name="description" content="">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.ebi.ac.uk/info/error-pages/500-standalone/">
    <meta property="og:title" content="Error: 500">
    <meta property="og:description" content="">


    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="og:url" content="https://www.ebi.ac.uk/info/error-pages/500-standalone/">
    <meta property="twitter:title" content="Error: 500">
    <meta property="twitter:description" content="">


    <!-- Content descriptors -->
    <meta name="embl:who" content="EMBL-EBI Web Dev">
    <meta name="embl:where" content="EMBL-EBI">
    <meta name="embl:what" content="none">
    <meta name="embl:active" content="where">

    <!-- Content role -->
    <meta name="embl:utility" content="10">
    <meta name="embl:reach" content="0">

    <!-- Page infromation -->
    <meta name="embl:maintainer" content="EMBL-EBI Web Dev">
    <meta name="embl:last-review" content="2021.04.01">
    <meta name="embl:review-cycle" content="365">
    <meta name="embl:expiry" content="never">

    <!-- analytics -->
    <meta name="vf:page-type" content="404;dimension1">

    <!-- CSS only -->
<link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.5.7/css/styles.css">
<!-- JS -->
<script src="https://assets.emblstatic.net/vf/v2.5.7/scripts/scripts.js"></script>
<head>
  <body class="vf-body vf-stack vf-stack--400">
    <style>head, title, link, meta, style, script {--vf-stack-margin--custom: 0; }</style>

    <!-- See the EBI Header Footer docs: https://stable.visual-framework.dev/components/ebi-header-footer -->

    <link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.4.5/assets/ebi-header-footer/ebi-header-footer.css" type="text/css" media="all">
    <header id="masthead-black-bar" class="clearfix masthead-black-bar | ebi-header-footer vf-content vf-u-fullbleed"></header>




<style>
  .embl-grid {
    margin-bottom: 48px;
  }
</style>

<section class="vf-intro" id="500">

  <div><!-- empty --></div>

  <div class="vf-stack">

  <h1 class="vf-intro__heading ">Error: 500</h1>
<p class="vf-lede">There was a technical error.</p>


<p class="vf-intro__text">Something has gone wrong with our web server when attempting to make this page.</p><p class="vf-intro__text">Unfortunately, the service you are trying to access is currently unavailable. <br>Please try again later.</p>
  </div>
</section>


<section class="embl-grid embl-grid--has-centered-content">
  <div></div>
 <section>
      <form id="ebi_search" action="/ebisearch/search.ebi" class="vf-form vf-form--search vf-form--search--mini | vf-sidebar vf-sidebar--end">
        <div class="vf-sidebar__inner" style="flex-wrap: nowrap;">
          <div class="vf-form__item">
            <label class="vf-form__label vf-u-sr-only | vf-search__label" for="searchitem">Search</label>
            <input name="query" type="search" placeholder="Find a gene, protein or chemical" id="searchitem" class="vf-form__input" required="" spellcheck="false" data-ms-editor="true">
            <input name="requestFrom" id="requestFrom" type="hidden" class="vf-form__input" value="ebi

**Comment by davmlaw** [comment]
🤖 Written by Claude

Fixed on master in 07eed76a3 (Ensembl API errors: HTML 500 page, connection failures). Moving to Coding Complete.
