### ISSUE TITLE
Cohort Hotspot graph

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#880]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4522](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4522)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
  File "/mnt/variantgrid/genes/views/views_hotspot_graphs.py", line 160, in get_context_data
    transcript_version, method, transcript_options, transcript_urls = self._pick_transcripts
  File "/usr/lib/python3.10/functools.py", line 981, in __get__
    val = self.func(instance)
  File "/mnt/variantgrid/genes/views/views_hotspot_graphs.py", line 154, in _pick_transcripts
    transcript_urls[tv.accession] = reverse(self._transcript_url(), kwargs=kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'gene_symbol_transcript_version_hotspot_graph' with keyword arguments '{'cohort_id': 1087, 'transcript_id': 'ENST00000336642', 'transcript_accession': 'ENST00000336642.9'}' not found. 1 pattern(s) tried: ['genes/hotspot_graph/gene_symbol/(?P<genome_build_name>[^/]+)/(?P<gene_symbol>[^/]+)/transcript/(?P<transcript_accession>[^/]+)\\Z']
```

**Comment by davmlaw** [comment]
This is VG only (not Shariant)

**Comment by davmlaw** [comment]
IT doesn't crash but it doesn't appear to work, either
