### ISSUE TITLE
ValueError: too many values to unpack (expected 4)

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#903]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4568](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4568)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/http.py", line 43, in inner
    return func(request, *args, **kwargs)
  File "/opt/variantgrid/classification/views/views.py", line 232, in create_classification
    return redirect(create_classification_object(request).get_edit_url())
  File "/opt/variantgrid/classification/views/views.py", line 260, in create_classification_object
    classification = create_classification_for_sample_and_variant_objects(request.user, sample,
  File "/opt/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 55, in create_classification_for_sample_and_variant_objects
    liftover_classification_import(vc_import, ImportSource.WEB)
  File "/opt/variantgrid/classification/tasks/classification_import_process_variants_task.py", line 115, in liftover_classification_import
    create_liftover_pipelines(classification_import.user, allele_source, import_source, genome_build)
  File "/opt/variantgrid/snpdb/liftover.py", line 34, in create_liftover_pipelines
    'build_liftover_vcf_tuples = _get_build_liftover...nserted_genome_build, destination_genome_builds)'
  File "/opt/variantgrid/snpdb/liftover.py", line 121, in _get_build_liftover_tuples
    chrom, position, ref, alt = variant_id_or_coordinate
ValueError: too many values to unpack (expected 4)
```

**Comment by EmmaTudini** [comment]
@davmlaw Any testing for this?

**Comment by TheMadBug** [comment]
I don't think so, I can also confirm it hasn't re-occurred in the last 15 days.

**Comment by davmlaw** [comment]
I just did a classification which kicked off an NCBI liftover, and it went through without error - it would have died before, so I think this one is good

**Comment by TheMadBug** [comment]
I thnik the above liftover is all we can do for testing this one. I'll move it to pending release.
