### ISSUE TITLE
Analyses list grid - fails when sorting by tags column

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#920]
Can either define in colmodel, or make column sortable = false 

FieldError: Cannot resolve keyword 'undefined' into field. Choices are: analysis_panel_fraction, analysis_type, analysisclassification, analysislock, analysisnode, analysisnodecountconfiguration, analysistemplate, analysistemplaterun, analysistemplatevers

"sidx=undefined" - fails

https://variantgrid.com/analysis/analyses/grid/handler/?_search=false&nd=1696474842557&rows=10&page=3&sidx=undefined&sord=asc fails

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4597](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4597)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/mnt/variantgrid/library/django_utils/jqgrid_view.py", line 63, in get
    return HttpResponse(grid_obj.get_json(request), content_type="application/json")
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 344, in get_json
    data = self.get_data(request)
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 339, in get_data
    'rows': list(items),
  File "/mnt/variantgrid/library/jqgrid/jqgrid.py", line 323, in iter_formatted_items
    for row in rows:
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 208, in __iter__
    for row in compiler.results_iter(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1513, in results_iter
    results = self.execute_sql(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 1549, in execute_sql
    sql, params = self.as_sql()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 736, in as_sql
    extra_select, order_by, group_by = self.pre_sql_setup(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 85, in pre_sql_setup
    order_by = self.get_order_by()
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/compiler.py", line 460, in get_order_by
    resolved = expr.resolve_expression(self.query, allow_joins=True, reuse=None)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 278, in resolve_expression
    [
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 279, in <listcomp>
    expr.resolve_expression(query, allow_joins, reuse, summarize)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/expressions.py", line 822, in resolve_expression
    return query.resolve_ref(self.name, allow_joins, reuse, summarize)
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 1965, in resolve_ref
    join_info = self.setup_joins(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 1812, in setup_joins
    path, final_field, targets, rest = self.names_to_path(
  File "/usr/local/lib/python3.10/dist-packages/django/db/models/sql/query.py", line 1713, in names_to_path
    raise FieldError(
FieldError: Cannot resolve keyword 'undefined' into field. Choices are: analysis_panel_fraction, analysis_type, analysisclassification, analysislock, analysisnode, analysisnodecountconfiguration, analysistemplate, analysistemplaterun, analysistemplateversion, annotation_version, annotation_version_id, canonical_transcript_collection, canonical_transcript_collection_id, created, custom_columns_collection, custom_columns_collection_id, default_sort_by_column, default_sort_by_column_id, description, genome_build, genome_build_id, id, lock_input_sources, modified, name, node_queryset_filter_contigs, show_igv_links, tags, template_type, user, user_id, varianttag, version, visible
```

**Comment by davmlaw** [comment]
tested vg test - ok
