### ISSUE TITLE
ClinGen - can't recover from errors

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#957]
ClinGen failed - now it works, but we get an error:

IntegrityError: duplicate key value violates unique constraint "snpdb_variantallele_variant_id_genome_build__27987e1b_uniq"DETAIL:  Key (variant_id, genome_build_id, allele_id)=(29232114, GRCh38, 106625) already exists.

View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4703](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4703)

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/data/variantgrid/classification/views/views.py", line 128, in get
    auto_data = generate_auto_populate_data(
  File "/data/variantgrid/classification/autopopulate_evidence_keys/autopopulate_evidence_keys.py", line 76, in generate_auto_populate_data
    data.update(get_evidence_fields_for_variant(genome_build, variant,
  File "/data/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 196, in get_evidence_fields_for_variant
    clingen_allele, evidence_value, message = get_clingen_allele_and_evidence_value_for_variant(genome_build, variant)
  File "/data/variantgrid/classification/autopopulate_evidence_keys/evidence_from_variant.py", line 175, in get_clingen_allele_and_evidence_value_for_variant
    clingen_allele = get_clingen_allele_for_variant(genome_build, variant)
  File "/data/variantgrid/snpdb/clingen_allele.py", line 322, in get_clingen_allele_for_variant
    va = get_variant_allele_for_variant(genome_build, variant, clingen_api=clingen_api)
  File "/data/variantgrid/snpdb/clingen_allele.py", line 240, in get_variant_allele_for_variant
    va = variant_allele_clingen(genome_build, variant, existing_variant_allele=va, clingen_api=clingen_api)
  File "/data/variantgrid/snpdb/clingen_allele.py", line 297, in variant_allele_clingen
    existing_allele_with_clingen.merge(AlleleConversionTool.CLINGEN_ALLELE_REGISTRY,
  File "/data/variantgrid/snpdb/models/models_variant.py", line 176, in merge
    other_allele.variantallele_set.update(allele=self, conversion_tool=conversion_tool)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 784, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1515, in execute_sql
    cursor = super().execute_sql(result_type)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1154, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/dist-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "snpdb_variantallele_variant_id_genome_build__27987e1b_uniq"
DETAIL:  Key (variant_id, genome_build_id, allele_id)=(29232114, GRCh38, 106625) already exists.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
UniqueViolation: duplicate key value violates unique constraint "snpdb_variantallele_variant_id_genome_build__27987e1b_uniq"
DETAIL:  Key (variant_id, genome_build_id, allele_id)=(29232114, GRCh38, 106625) already exists.

```

**Comment by davmlaw** [comment]
Short term - we can probably just delete it, if variant allele contains that error message.

Long term solution would be to change how this works, and then update the existing variant allele

**Comment by davmlaw** [comment]
I tried to recreate this in latest code, and can't - it seem to have been fixed:

```
from snpdb.models import GenomeBuild, VariantAllele, AlleleConversionTool, Variant, Allele

v = Variant.objects.filter(variantallele__isnull=True).first() # pk=1
a = Allele.objects.create() # pk = 161

va = VariantAllele.objects.create(variant=v, allele=a, error={'message': "Error contacting ClinGen Allele Registry. Method: 'PUT', Response: 502", 'errorType': 'ServerError', 'inputLine': 'NC_000004.12:g.54285866G>A', 'description': 'Error connecting to server: Bad Gateway'}, genome_build=next(iter(v.genome_builds)))
```

If you go to the variant page it fixes itself.

So, I'll write a 1 off script to fix SA Path then we'll leave it

**Comment by davmlaw** [comment]
```
from snpdb.models import GenomeBuild, VariantAllele, AlleleConversionTool, Variant, Allele

from snpdb.clingen_allele import populate_clingen_alleles_for_variants


va_qs_37 = VariantAllele.objects.filter(error__icontains='Connection refused', genome_build=GenomeBuild.grch37())
va_qs_38 = VariantAllele.objects.filter(error__icontains='Connection refused', genome_build=GenomeBuild.grch38())

variants = set(va_qs_38.values_list("variant", flat=True))
populate_clingen_alleles_for_variants(GenomeBuild.grch38(), Variant.objects.filter(pk__in=variants))
```
