### ISSUE TITLE
ValueError: Cannot find HGNC for T

### ISSUE THREAD

**Issue by davmlaw** [SACGF/variantgrid#999]
View details in Rollbar: [https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4815](https://app.rollbar.com/a/jimmy.andrews/fix/item/VariantGrid/4815)

```
Traceback (most recent call last):
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/variantgrid/env/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/opt/variantgrid/env/lib/python3.11/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/opt/variantgrid/ontology/views_rest.py", line 62, in get
    for otr in ontology_version.gene_disease_relations(self.kwargs['gene_symbol'],
  File "/opt/variantgrid/ontology/models/models_ontology.py", line 799, in gene_disease_relations
    snake = self.terms_for_gene_symbol(gene_symbol, OntologyService.MONDO,
  File "/opt/variantgrid/ontology/models/models_ontology.py", line 794, in terms_for_gene_symbol
    return OntologySnake.terms_for_gene_symbol(gene_symbol, desired_ontology, max_depth=max_depth,
  File "/opt/variantgrid/ontology/models/models_ontology.py", line 1089, in terms_for_gene_symbol
    gene_ontology = OntologyTerm.get_gene_symbol(gene_symbol)
  File "/opt/variantgrid/ontology/models/models_ontology.py", line 447, in get_gene_symbol
    raise ValueError(f"Cannot find HGNC for {gene_symbol}")
ValueError: Cannot find HGNC for T
```

**Comment by davmlaw** [comment]
🤖 Written by Claude

Fixed on master in cf6b7091b and 5bb8122de (GenCC column for symbols with no HGNC record). Moving to Coding Complete.
